#ifndef PS2CONTROLLER_H
#define PS2CONTROLLER_H

// text

// void radControllerInitialize__FP38IRadControllerConnectionChangeCallbacki();
// void radControllerTerminate__Fv();
// void radControllerSystemGet__Fv();
// void radControllerSystemService__Fv();
// void __18rControllerSystem2P38IRadControllerConnectionChangeCallback();
// void _$_18rControllerSystem2();
// void Service__18rControllerSystem2();
// void AddRef__18rControllerSystem2();
// void Release__18rControllerSystem2();
// void GetNumberOfControllers__18rControllerSystem2();
// void GetControllerByIndex__18rControllerSystem2Ui();
// void GetControllerAtLocation__18rControllerSystem2PCc();
// void SetBufferTime__18rControllerSystem2Ui();
// void MapVirtualTime__18rControllerSystem2UiUi();
// void SetVirtualTime__18rControllerSystem2Ui();
// void SetCaptureRate__18rControllerSystem2Ui();
// void RegisterConnectionChangeCallback__18rControllerSystem2P38IRadControllerConnectionChangeCallback();
// void UnRegisterConnectionChangeCallback__18rControllerSystem2P38IRadControllerConnectionChangeCallback();
// void OnTimerDone__18rControllerSystem2UiPv();
// void InitializeLocations__18rControllerSystem2();
// void CreateController__18rControllerSystem2iP20iControllerLocation2PP12rController2();
// void _StartControllerInitialization__18rControllerSystem2P20iControllerLocation2i();
// void _RequestControllerMode__18rControllerSystem2P20iControllerLocation2();
// void _RequestControllerModeDone__18rControllerSystem2P20iControllerLocation2i();
// void _RequestControllerActuator__18rControllerSystem2P20iControllerLocation2();
// void _RequestControllerActuatorDone__18rControllerSystem2P20iControllerLocation2i();
// void _RequestControllerPressure__18rControllerSystem2P20iControllerLocation2();
// void _RequestControllerPressureDone__18rControllerSystem2P20iControllerLocation2i();
// void _CheckControllerAsyncProcessing__18rControllerSystem2P20iControllerLocation2();
// void _ControllerAlmostReady__18rControllerSystem2P20iControllerLocation2ii();
// void _ControllerReady__18rControllerSystem2P20iControllerLocation2ii();
// void SetupControllers__18rControllerSystem2();
// void iGetVirtualTime__18rControllerSystem2();
// void iGetVirtualTimeAdjust__18rControllerSystem2();
// void __20iControllerLocation2ii();
// void _$_20iControllerLocation2();
// void AddRef__20iControllerLocation2();
// void Release__20iControllerLocation2();
// void GetPort__20iControllerLocation2();
// void GetSlot__20iControllerLocation2();
// void GetName__20iControllerLocation2();
// void GetNameBString__20iControllerLocation2PP10IRadString();
// void AttachController__20iControllerLocation2P12rController2();
// void GetAttachedController__20iControllerLocation2PP12rController2();
// void SetControllerState__20iControllerLocation2Q221iIControllerLocation213LocationState();
// void GetControllerState__20iControllerLocation2();
// void SetControllerPrevState__20iControllerLocation2Q221iIControllerLocation213LocationState();
// void GetControllerPrevState__20iControllerLocation2();
// void SetTotalNumModes__20iControllerLocation2i();
// void GetTotalNumModes__20iControllerLocation2();
// void SetCurrentMode__20iControllerLocation2i();
// void GetCurrentMode__20iControllerLocation2();
// void SetModeQueryResult__20iControllerLocation2ii();
// void GetModeQueryResult__20iControllerLocation2i();
// void SetActAlign__20iControllerLocation2ii();
// void SetActDirect__20iControllerLocation2ii();
// void GetActAlignBuffer__20iControllerLocation2();
// void GetActDirectBuffer__20iControllerLocation2();
// void ReconnectIfControllerMatches__20iControllerLocation2iPP12rController2Ui();
// void GetNumActuators__20iControllerLocation2();
// void SetNumActuators__20iControllerLocation2i();
// void __12rController2iiiP10IRadStringPUcT5iUi();
// void _$_12rController2();
// void AddRef__12rController2();
// void Release__12rController2();
// void IsConnected__12rController2();
// void GetClassification__12rController2();
// void GetType__12rController2();
// void GetNumberOfInputPointsOfType__12rController2PCc();
// void GetNumberOfOutputPointsOfType__12rController2PCc();
// void GetInputPointByTypeAndIndex__12rController2PCcUi();
// void GetOutputPointByTypeAndIndex__12rController2PCcUi();
// void GetInputPointByName__12rController2PCc();
// void GetOutputPointByName__12rController2PCc();
// void GetLocation__12rController2();
// void GetNumberOfInputPoints__12rController2();
// void GetInputPointByIndex__12rController2Ui();
// void GetNumberOfOutputPoints__12rController2();
// void GetOutputPointByIndex__12rController2Ui();
// void GetDataBuffer__12rController2();
// void Disconnect__12rController2();
// void Connect__12rController2();
// void iVirtualTimeChanged__12rController2();
// void iPoll__12rController2Ui();
// void iSetBufferTime__12rController2Ui();
// void GetId__12rController2();
// void __25iControllerOutputHandler2iiPUc();
// void _$_25iControllerOutputHandler2();
// void AddRef__25iControllerOutputHandler2();
// void Release__25iControllerOutputHandler2();
// void Connect__25iControllerOutputHandler2();
// void Disconnect__25iControllerOutputHandler2();
// void iOnControllerGainChange__25iControllerOutputHandler2P25IRadControllerOutputPoint();
// void __23rControllerOutputPoint2P33iRIControllerOutputPointCallback2P10IRadStringT2();
// void _$_23rControllerOutputPoint2();
// void AddRef__23rControllerOutputPoint2();
// void Release__23rControllerOutputPoint2();
// void GetName__23rControllerOutputPoint2();
// void GetType__23rControllerOutputPoint2();
// void GetGain__23rControllerOutputPoint2();
// void SetGain__23rControllerOutputPoint2f();
// void __22rControllerInputPoint2P9IRefCountP10IRadStringiUiUi();
// void _$_22rControllerInputPoint2();
// void AddRef__22rControllerInputPoint2();
// void Release__22rControllerInputPoint2();
// void GetName__22rControllerInputPoint2();
// void GetType__22rControllerInputPoint2();
// void SetTolerance__22rControllerInputPoint2f();
// void GetTolerance__22rControllerInputPoint2();
// void RegisterControllerInputPointCallback__22rControllerInputPoint2P32IRadControllerInputPointCallbackUi();
// void UnRegisterControllerInputPointCallback__22rControllerInputPoint2P32IRadControllerInputPointCallback();
// void GetCurrentValue__22rControllerInputPoint2PUi();
// void SetRange__22rControllerInputPoint2ff();
// void GetRange__22rControllerInputPoint2PfT1();
// void CalculateNewValue__22rControllerInputPoint2PUc();
// void iInitialize__22rControllerInputPoint2PUc();
// void iHandleEvent__22rControllerInputPoint2PUcUi();
// void __20LGDevWheelInputPointPC19LGDevInputPointData();
// void _$_20LGDevWheelInputPoint();
// void CalculateNewValue__20LGDevWheelInputPointP13lgDevPosition();
// void HandleEvent__20LGDevWheelInputPointP13lgDevPositionUi();
// void SetTolerance__20LGDevWheelInputPointf();
// void RegisterControllerInputPointCallback__20LGDevWheelInputPointP32IRadControllerInputPointCallbackUi();
// void UnRegisterControllerInputPointCallback__20LGDevWheelInputPointP32IRadControllerInputPointCallback();
// void GetCurrentValue__20LGDevWheelInputPointPUi();
// void GetRange__20LGDevWheelInputPointPfT1();
// void __20LGDevWheelControllerP15lgDevDeviceDesc();
// void iPoll__20LGDevWheelControllerUi();
// void iVirtualTimeChanged__20LGDevWheelController();
// void iSetBufferTime__20LGDevWheelControllerUi();
// void Disconnect__20LGDevWheelController();
// void Connect__20LGDevWheelController();
// void IsConnected__20LGDevWheelController();
// void GetNumberOfInputPointsOfType__20LGDevWheelControllerPCc();
// void GetNumberOfOutputPointsOfType__20LGDevWheelControllerPCc();
// void GetInputPointByTypeAndIndex__20LGDevWheelControllerPCcUi();
// void GetOutputPointByTypeAndIndex__20LGDevWheelControllerPCcUi();
// void GetInputPointByName__20LGDevWheelControllerPCc();
// void GetOutputPointByName__20LGDevWheelControllerPCc();
// void GetInputPointByIndex__20LGDevWheelControllerUi();
// void GetOutputPointByIndex__20LGDevWheelControllerUi();
// void __21LGDevWheelOutputPointPCcUc();
// void _$_21LGDevWheelOutputPoint();
// void GetGain__21LGDevWheelOutputPoint();
// void SetGain__21LGDevWheelOutputPointf();
// void GetEffect__C21LGDevWheelOutputPoint();
// void UpdateEffect__21LGDevWheelOutputPointPC16lgDevForceEffect();
// void Update__21LGDevWheelOutputPointUi();
// void func_003D5B38();
// void func_003D64C0();
// void __tf18rControllerSystem2();
// void __tf20iControllerLocation2();
// void __tf12rController2();
// void __tf25iControllerOutputHandler2();
// void __tf23rControllerOutputPoint2();
// void __tf22rControllerInputPoint2();
// void __tf20LGDevWheelInputPoint();
// void __tf21LGDevWheelOutputPoint();
// void __tf20LGDevWheelController();
// void func_003D6848();
// void __20IRadControllerSystem();
// void __25IRadControllerOutputPoint();
// void GetEffect__C25IRadControllerOutputPoint();
// void UpdateEffect__25IRadControllerOutputPointPC16lgDevForceEffect();
// void Start__25IRadControllerOutputPoint();
// void Stop__25IRadControllerOutputPoint();
// void Update__25IRadControllerOutputPointUi();
// void __24IRadControllerInputPoint();
// void __21iIControllerLocation2();
// void __13iIController2();
// void __33iRIControllerOutputPointCallback2();
// void __23iIControllerInputPoint2();
// void AddRef__20LGDevWheelInputPoint();
// void Release__20LGDevWheelInputPoint();
// void GetName__20LGDevWheelInputPoint();
// void GetType__20LGDevWheelInputPoint();
// void GetTolerance__20LGDevWheelInputPoint();
// void SetRange__20LGDevWheelInputPointff();
// void AddRef__21LGDevWheelOutputPoint();
// void Release__21LGDevWheelOutputPoint();
// void GetName__21LGDevWheelOutputPoint();
// void GetType__21LGDevWheelOutputPoint();
// void Start__21LGDevWheelOutputPoint();
// void Stop__21LGDevWheelOutputPoint();
// void AddRef__20LGDevWheelController();
// void Release__20LGDevWheelController();
// void _$_20LGDevWheelController();
// void GetType__20LGDevWheelController();
// void GetClassification__20LGDevWheelController();
// void GetLocation__20LGDevWheelController();
// void GetNumberOfInputPoints__20LGDevWheelController();
// void GetNumberOfOutputPoints__20LGDevWheelController();
// void func_003D6D48();
// void __tf20IRadControllerSystem();
// void __tf25IRadControllerOutputPoint();
// void __tf24IRadControllerInputPoint();
// void __tf21iIControllerLocation2();
// void __tf13iIController2();
// void __tf33iRIControllerOutputPointCallback2();
// void __tf23iIControllerInputPoint2();
// void __14IRadController();
// void __tf14IRadController();
// void _GLOBAL_$I$radControllerInitialize__FP38IRadControllerConnectionChangeCallbacki();

// data

// extern UNK_TYPE D_0043D808;
// extern UNK_TYPE D_0043D820;
// extern UNK_TYPE D_0043D838;
// extern UNK_TYPE D_0043D870;
// extern UNK_TYPE D_0043D8C0;
// extern UNK_TYPE D_0043D8C8;
// extern UNK_TYPE D_0043D8D0;
// extern UNK_TYPE D_0043D950;

// bss

// extern UNK_TYPE D_004F7F80;
// extern UNK_TYPE D_004F8020;
// extern UNK_TYPE D_004F8140;
// extern UNK_TYPE D_004F8180;

// rodata

// extern UNK_TYPE D_004A6B20;
// extern UNK_TYPE D_004A6B48;
// extern UNK_TYPE D_004A6B58;
// extern UNK_TYPE D_004A6B68;
// extern UNK_TYPE D_004A6B78;
// extern UNK_TYPE D_004A6B88;
// extern UNK_TYPE D_004A6B90;
// extern UNK_TYPE D_004A6BA0;
// extern UNK_TYPE D_004A6BA8;
// extern UNK_TYPE D_004A6BB0;
// extern UNK_TYPE D_004A6BB8;
// extern UNK_TYPE D_004A6BC0;
// extern UNK_TYPE D_004A6BC8;
// extern UNK_TYPE D_004A6BD0;
// extern UNK_TYPE D_004A6BE0;
// extern UNK_TYPE D_004A6BF0;
// extern UNK_TYPE D_004A6C00;
// extern UNK_TYPE D_004A6C08;
// extern UNK_TYPE D_004A6C10;
// extern UNK_TYPE D_004A6C18;
// extern UNK_TYPE D_004A6C20;
// extern UNK_TYPE D_004A6C30;
// extern UNK_TYPE D_004A6C38;
// extern UNK_TYPE D_004A6C40;
// extern UNK_TYPE D_004A6C48;
// extern UNK_TYPE D_004A6C50;
// extern UNK_TYPE D_004A6C58;
// extern UNK_TYPE D_004A6C68;
// extern UNK_TYPE D_004A6C78;
// extern UNK_TYPE D_004A6C88;
// extern UNK_TYPE D_004A6C98;
// extern UNK_TYPE D_004A6CA8;
// extern UNK_TYPE D_004A6CB8;
// extern UNK_TYPE D_004A6CC0;
// extern UNK_TYPE D_004A6CC8;
// extern UNK_TYPE D_004A6CD8;
// extern UNK_TYPE D_004A6CE8;
// extern UNK_TYPE D_004A6CF8;
// extern UNK_TYPE D_004A6D08;
// extern UNK_TYPE D_004A6D18;
// extern UNK_TYPE D_004A6D28;
// extern UNK_TYPE D_004A6D30;
// extern UNK_TYPE D_004A6D40;
// extern UNK_TYPE D_004A6D50;
// extern UNK_TYPE D_004A6D60;
// extern UNK_TYPE D_004A6D70;
// extern UNK_TYPE D_004A6D80;
// extern UNK_TYPE D_004A6D90;
// extern UNK_TYPE D_004A6DA0;
// extern UNK_TYPE D_004A6DC0;
// extern UNK_TYPE D_004A6DD0;
// extern UNK_TYPE D_004A6DE0;
// extern UNK_TYPE D_004A6DF0;
// extern UNK_TYPE D_004A6E00;
// extern UNK_TYPE D_004A6E10;
// extern UNK_TYPE D_004A6E18;
// extern UNK_TYPE jtbl_004A6E20;
// extern UNK_TYPE D_004A6E50;
// extern UNK_TYPE D_004A6E68;
// extern UNK_TYPE D_004A6E70;
// extern UNK_TYPE D_004A6E78;
// extern UNK_TYPE D_004A6EA0;
// extern UNK_TYPE D_004A6EF8;
// extern UNK_TYPE D_004A6F08;
// extern UNK_TYPE D_004A6F18;
// extern UNK_TYPE D_004A6F28;
// extern UNK_TYPE D_004A6F30;
// extern UNK_TYPE _vt$20LGDevWheelController$11radRefCount;
// extern UNK_TYPE _vt$20LGDevWheelController;
// extern UNK_TYPE _vt$21LGDevWheelOutputPoint$11radRefCount;
// extern UNK_TYPE _vt$21LGDevWheelOutputPoint;
// extern UNK_TYPE _vt$20LGDevWheelInputPoint$11radRefCount;
// extern UNK_TYPE _vt$20LGDevWheelInputPoint;
// extern UNK_TYPE _vt$22rControllerInputPoint2$9radObject;
// extern UNK_TYPE _vt$22rControllerInputPoint2;
// extern UNK_TYPE _vt$23rControllerOutputPoint2$9radObject;
// extern UNK_TYPE _vt$23rControllerOutputPoint2;
// extern UNK_TYPE _vt$25iControllerOutputHandler2$9radObject;
// extern UNK_TYPE _vt$25iControllerOutputHandler2;
// extern UNK_TYPE _vt$12rController2$9radObject;
// extern UNK_TYPE _vt$12rController2;
// extern UNK_TYPE _vt$20iControllerLocation2$9radObject;
// extern UNK_TYPE _vt$20iControllerLocation2;
// extern UNK_TYPE _vt$18rControllerSystem2$9radObject;
// extern UNK_TYPE _vt$18rControllerSystem2$17IRadTimerCallback;
// extern UNK_TYPE _vt$18rControllerSystem2;
// extern UNK_TYPE D_004A7568;
// extern UNK_TYPE D_004A7578;
// extern UNK_TYPE D_004A7580;
// extern UNK_TYPE D_004A7588;
// extern UNK_TYPE D_004A7590;
// extern UNK_TYPE D_004A7598;
// extern UNK_TYPE D_004A75A0;
// extern UNK_TYPE D_004A75A8;
// extern UNK_TYPE D_004A75B0;
// extern UNK_TYPE D_004A7628;
// extern UNK_TYPE D_004A7640;
// extern UNK_TYPE D_004A7658;
// extern UNK_TYPE D_004A7670;
// extern UNK_TYPE D_004A7680;
// extern UNK_TYPE D_004A7690;
// extern UNK_TYPE D_004A76A0;
// extern UNK_TYPE D_004A76C0;
// extern UNK_TYPE D_004A76D0;
// extern UNK_TYPE D_004A76F0;
// extern UNK_TYPE D_004A7700;
// extern UNK_TYPE D_004A7720;
// extern UNK_TYPE D_004A7730;
// extern UNK_TYPE D_004A7748;
// extern UNK_TYPE D_004A7758;
// extern UNK_TYPE D_004A7770;
// extern UNK_TYPE D_004A7780;
// extern UNK_TYPE D_004A7798;
// extern UNK_TYPE D_004A77A8;
// extern UNK_TYPE D_004A7850;
// extern UNK_TYPE D_004A7940;
// extern UNK_TYPE _vt$23iIControllerInputPoint2;
// extern UNK_TYPE _vt$33iRIControllerOutputPointCallback2;
// extern UNK_TYPE _vt$13iIController2;
// extern UNK_TYPE _vt$21iIControllerLocation2;
// extern UNK_TYPE _vt$24IRadControllerInputPoint;
// extern UNK_TYPE _vt$25IRadControllerOutputPoint;
// extern UNK_TYPE _vt$20IRadControllerSystem;
// extern UNK_TYPE D_004A7E88;
// extern UNK_TYPE D_004A7EA0;
// extern UNK_TYPE D_004A7EC0;
// extern UNK_TYPE D_004A7EE0;
// extern UNK_TYPE D_004A7EF8;
// extern UNK_TYPE D_004A7F08;
// extern UNK_TYPE D_004A7F30;
// extern UNK_TYPE _vt$14IRadController;
// extern UNK_TYPE D_004A7FE0;

#endif
