#ifndef REQUESTS_HPP
#define REQUESTS_HPP

// text

// void radRequestPoolInitialize__FUii();
// void radRequestPoolTerminate__Fv();
// void __nw__10radRequestUi();
// void __dl__10radRequestPv();
// void __10radRequest();
// void _$_10radRequest();
// void __22CompletionEventRequestP19IRadThreadSemaphoreP8radDrive();
// void _$_22CompletionEventRequest();
// void DoRequest__22CompletionEventRequest();
// void ShouldCancel__22CompletionEventRequestPv();
// void GetOwner__22CompletionEventRequest();
// void ReInit__22CompletionEventRequest();
// void __25CompletionCallbackRequestP10IRadThread();
// void ShouldCancel__25CompletionCallbackRequestPv();
// void IsRegisteredThread__25CompletionCallbackRequestP10IRadThread();
// void ReInit__25CompletionCallbackRequest();
// void __21FileCompletionRequestP10IRadThreadP7radFileP26IRadFileCompletionCallbackPv();
// void _$_21FileCompletionRequest();
// void DoRequest__21FileCompletionRequest();
// void callback__21FileCompletionRequest();
// void GetOwner__21FileCompletionRequest();
// void __22DriveCompletionRequestP10IRadThreadP16radInstanceDriveP27IRadDriveCompletionCallbackPv();
// void _$_22DriveCompletionRequest();
// void DoRequest__22DriveCompletionRequest();
// void callback__22DriveCompletionRequest();
// void GetOwner__22DriveCompletionRequest();
// void __14radFileRequestP7radFile();
// void _$_14radFileRequest();
// void handleError__14radFileRequestQ28radDrive16CompletionStatus12radFileError();
// void ShouldCancel__14radFileRequestPv();
// void GetOwner__14radFileRequest();
// void ReInit__14radFileRequest();
// void GetFilename__14radFileRequest();
// void __15FileOpenRequestP7radFile16radFileOpenFlagsb();
// void DoRequest__15FileOpenRequest();
// void __19SaveGameOpenRequestP7radFile16radFileOpenFlagsbP14radMemcardInfoUi();
// void DoRequest__19SaveGameOpenRequest();
// void __16FileCloseRequestP7radFile();
// void ReInit__16FileCloseRequest();
// void DoRequest__16FileCloseRequest();
// void __17FileCommitRequestP7radFile();
// void DoRequest__17FileCommitRequest();
// void __15FileReadRequestP7radFilePvUi14radMemorySpace();
// void DoRequest__15FileReadRequest();
// void __16FileWriteRequestP7radFilePCvUi14radMemorySpace();
// void DoRequest__16FileWriteRequest();
// void __22FileSetPositionRequestP7radFileUi();
// void DoRequest__22FileSetPositionRequest();
// void __22FileGetPositionRequestP7radFilePUi();
// void DoRequest__22FileGetPositionRequest();
// void __18FileGetSizeRequestP7radFilePUi();
// void DoRequest__18FileGetSizeRequest();
// void __17FileCancelRequestP7radFile();
// void DoRequest__17FileCancelRequest();
// void ReInit__17FileCancelRequest();
// void __15radDriveRequestP16radInstanceDrive();
// void _$_15radDriveRequest();
// void ShouldCancel__15radDriveRequestPv();
// void GetOwner__15radDriveRequest();
// void ReInit__15radDriveRequest();
// void __16DriveOpenRequestP16radInstanceDrive();
// void DoRequest__16DriveOpenRequest();
// void ReInit__16DriveOpenRequest();
// void __17DriveMediaRequestP16radInstanceDrivePQ29IRadDrive9MediaInfo();
// void DoRequest__17DriveMediaRequest();
// void ReInit__17DriveMediaRequest();
// void __18DriveFormatRequestP16radInstanceDrive();
// void DoRequest__18DriveFormatRequest();
// void __27DriveCreateDirectoryRequestP16radInstanceDrivePCc();
// void DoRequest__27DriveCreateDirectoryRequest();
// void __28DriveDestroyDirectoryRequestP16radInstanceDrivePCc();
// void DoRequest__28DriveDestroyDirectoryRequest();
// void __21DriveFindFirstRequestP16radInstanceDrivePCcPQ29IRadDrive13DirectoryInfo();
// void DoRequest__21DriveFindFirstRequest();
// void __20DriveFindNextRequestP16radInstanceDrivePQ29IRadDrive13DirectoryInfo();
// void DoRequest__20DriveFindNextRequest();
// void __21DriveFindCloseRequestP16radInstanceDrive();
// void DoRequest__21DriveFindCloseRequest();
// void ReInit__21DriveFindCloseRequest();
// void __23DriveFileDestroyRequestP16radInstanceDrivePCc();
// void DoRequest__23DriveFileDestroyRequest();
// void __18DriveCancelRequestP16radInstanceDrive();
// void DoRequest__18DriveCancelRequest();
// void ReInit__18DriveCancelRequest();
// void __tf10radRequest();
// void __tf22CompletionEventRequest();
// void __tf25CompletionCallbackRequest();
// void __tf21FileCompletionRequest();
// void __tf22DriveCompletionRequest();
// void __tf14radFileRequest();
// void _$_15FileOpenRequest();
// void __tf15FileOpenRequest();
// void _$_19SaveGameOpenRequest();
// void __tf19SaveGameOpenRequest();
// void _$_16FileCloseRequest();
// void __tf16FileCloseRequest();
// void _$_17FileCommitRequest();
// void __tf17FileCommitRequest();
// void _$_15FileReadRequest();
// void __tf15FileReadRequest();
// void _$_16FileWriteRequest();
// void __tf16FileWriteRequest();
// void _$_22FileSetPositionRequest();
// void __tf22FileSetPositionRequest();
// void _$_22FileGetPositionRequest();
// void __tf22FileGetPositionRequest();
// void _$_18FileGetSizeRequest();
// void __tf18FileGetSizeRequest();
// void _$_17FileCancelRequest();
// void __tf17FileCancelRequest();
// void __tf15radDriveRequest();
// void _$_16DriveOpenRequest();
// void __tf16DriveOpenRequest();
// void _$_17DriveMediaRequest();
// void __tf17DriveMediaRequest();
// void _$_18DriveFormatRequest();
// void __tf18DriveFormatRequest();
// void _$_27DriveCreateDirectoryRequest();
// void __tf27DriveCreateDirectoryRequest();
// void _$_28DriveDestroyDirectoryRequest();
// void __tf28DriveDestroyDirectoryRequest();
// void _$_21DriveFindFirstRequest();
// void __tf21DriveFindFirstRequest();
// void _$_20DriveFindNextRequest();
// void __tf20DriveFindNextRequest();
// void _$_21DriveFindCloseRequest();
// void __tf21DriveFindCloseRequest();
// void _$_23DriveFileDestroyRequest();
// void __tf23DriveFileDestroyRequest();
// void _$_18DriveCancelRequest();
// void __tf18DriveCancelRequest();
// void _$_25CompletionCallbackRequest();

// data

// extern UNK_TYPE D_0043E208;
// extern UNK_TYPE D_0043E20C;

// rodata

// extern UNK_TYPE D_004A9A38;
// extern UNK_TYPE _vt$18DriveCancelRequest;
// extern UNK_TYPE _vt$23DriveFileDestroyRequest;
// extern UNK_TYPE _vt$21DriveFindCloseRequest;
// extern UNK_TYPE _vt$20DriveFindNextRequest;
// extern UNK_TYPE _vt$21DriveFindFirstRequest;
// extern UNK_TYPE _vt$28DriveDestroyDirectoryRequest;
// extern UNK_TYPE _vt$27DriveCreateDirectoryRequest;
// extern UNK_TYPE _vt$18DriveFormatRequest;
// extern UNK_TYPE _vt$17DriveMediaRequest;
// extern UNK_TYPE _vt$16DriveOpenRequest;
// extern UNK_TYPE _vt$15radDriveRequest;
// extern UNK_TYPE _vt$17FileCancelRequest;
// extern UNK_TYPE _vt$18FileGetSizeRequest;
// extern UNK_TYPE _vt$22FileGetPositionRequest;
// extern UNK_TYPE _vt$22FileSetPositionRequest;
// extern UNK_TYPE _vt$16FileWriteRequest;
// extern UNK_TYPE _vt$15FileReadRequest;
// extern UNK_TYPE _vt$17FileCommitRequest;
// extern UNK_TYPE _vt$16FileCloseRequest;
// extern UNK_TYPE _vt$19SaveGameOpenRequest;
// extern UNK_TYPE _vt$15FileOpenRequest;
// extern UNK_TYPE _vt$14radFileRequest;
// extern UNK_TYPE _vt$22DriveCompletionRequest;
// extern UNK_TYPE _vt$21FileCompletionRequest;
// extern UNK_TYPE _vt$25CompletionCallbackRequest;
// extern UNK_TYPE _vt$22CompletionEventRequest;
// extern UNK_TYPE _vt$10radRequest;
// extern UNK_TYPE D_004AA0A0;
// extern UNK_TYPE D_004AA0B0;
// extern UNK_TYPE D_004AA0D0;
// extern UNK_TYPE D_004AA0F0;
// extern UNK_TYPE D_004AA108;
// extern UNK_TYPE D_004AA128;
// extern UNK_TYPE D_004AA140;
// extern UNK_TYPE D_004AA158;
// extern UNK_TYPE D_004AA170;
// extern UNK_TYPE D_004AA188;
// extern UNK_TYPE D_004AA1A0;
// extern UNK_TYPE D_004AA1B8;
// extern UNK_TYPE D_004AA1D0;
// extern UNK_TYPE D_004AA1F0;
// extern UNK_TYPE D_004AA210;
// extern UNK_TYPE D_004AA228;
// extern UNK_TYPE D_004AA240;
// extern UNK_TYPE D_004AA258;
// extern UNK_TYPE D_004AA270;
// extern UNK_TYPE D_004AA288;
// extern UNK_TYPE D_004AA2A0;
// extern UNK_TYPE D_004AA2C0;
// extern UNK_TYPE D_004AA2E0;
// extern UNK_TYPE D_004AA2F8;
// extern UNK_TYPE D_004AA310;
// extern UNK_TYPE D_004AA328;
// extern UNK_TYPE D_004AA348;

#endif
