#ifndef CHANNEL_H
#define CHANNEL_H

// text

// void __8tChanneliP21tAnimationMemoryBlock();
// void CleanUp__8tChannel();
// void FindBracketKeys__C8tChannelfRiT2();
// void __11tIntChanneliP21tAnimationMemoryBlock();
// void CleanUp__11tIntChannel();
// void GetValue__C11tIntChannelfPi();
// void __14tFloat1ChanneliP21tAnimationMemoryBlock();
// void CleanUp__14tFloat1Channel();
// void GetValue__C14tFloat1ChannelfPf();
// void __14tFloat2ChanneliP21tAnimationMemoryBlock();
// void CleanUp__14tFloat2Channel();
// void GetValue__C14tFloat2ChannelfPQ218RadicalMathLibrary7Vector2();
// void __18tVector1DOFChanneliP21tAnimationMemoryBlock();
// void CleanUp__18tVector1DOFChannel();
// void GetValue__C18tVector1DOFChannelfPQ218RadicalMathLibrary6Vector();
// void __18tVector2DOFChanneliP21tAnimationMemoryBlock();
// void CleanUp__18tVector2DOFChannel();
// void GetValue__C18tVector2DOFChannelfPQ218RadicalMathLibrary6Vector();
// void __18tVector3DOFChanneliP21tAnimationMemoryBlock();
// void CleanUp__18tVector3DOFChannel();
// void GetValue__C18tVector3DOFChannelfPQ218RadicalMathLibrary6Vector();
// void __18tQuaternionChanneliP21tAnimationMemoryBlock();
// void CleanUp__18tQuaternionChannel();
// void GetEuler__C18tQuaternionChannelfPQ218RadicalMathLibrary6Vector();
// void GetQuaternion__C18tQuaternionChannelfPQ218RadicalMathLibrary10Quaternion();
// void GetMatrix__C18tQuaternionChannelfPQ218RadicalMathLibrary6Matrix();
// void __28tCompressedQuaternionChanneliP21tAnimationMemoryBlock();
// void CleanUp__28tCompressedQuaternionChannel();
// void GetEuler__C28tCompressedQuaternionChannelfPQ218RadicalMathLibrary6Vector();
// void GetQuaternion__C28tCompressedQuaternionChannelfPQ218RadicalMathLibrary10Quaternion();
// void GetMatrix__C28tCompressedQuaternionChannelfPQ218RadicalMathLibrary6Matrix();
// void __14tStringChanneliP21tAnimationMemoryBlock();
// void CleanUp__14tStringChannel();
// void func_00340680();
// void __14tEntityChanneliP21tAnimationMemoryBlock();
// void CleanUp__14tEntityChannel();
// void GetValue__C14tEntityChannelfPP7tEntity();
// void FindEndKeys__C14tEntityChannelfPfPP7tEntityT2T3();
// void __12tBoolChanneliP21tAnimationMemoryBlock();
// void CleanUp__12tBoolChannel();
// void GetValue__C12tBoolChannelfPb();
// void __14tColourChanneliP21tAnimationMemoryBlock();
// void CleanUp__14tColourChannel();
// void GetValue__C14tColourChannelfP10pddiColour();
// void __13tEventChanneliP21tAnimationMemoryBlock();
// void CleanUp__13tEventChannel();
// void DispatchEvents__C13tEventChannelP15tEventRecipientP12tEventOriginRC5tNameff();
// void LoadChannel__14tChannelLoaderP10tChunkFileP12tEntityStoreP21tAnimationMemoryBlock();
// void LoadIntChannel__14tChannelLoaderP10tChunkFileP12tEntityStoreP21tAnimationMemoryBlock();
// void LoadFloat1Channel__14tChannelLoaderP10tChunkFileP12tEntityStoreP21tAnimationMemoryBlock();
// void LoadFloat2Channel__14tChannelLoaderP10tChunkFileP12tEntityStoreP21tAnimationMemoryBlock();
// void LoadVectorChannel__14tChannelLoaderP10tChunkFileP12tEntityStoreP21tAnimationMemoryBlock();
// void LoadRotationChannel__14tChannelLoaderP10tChunkFileP12tEntityStoreP21tAnimationMemoryBlock();
// void LoadStringChannel__14tChannelLoaderP10tChunkFileP12tEntityStoreP21tAnimationMemoryBlock();
// void LoadEntityChannel__14tChannelLoaderP10tChunkFileP12tEntityStoreP21tAnimationMemoryBlock();
// void LoadBoolChannel__14tChannelLoaderP10tChunkFileP12tEntityStoreP21tAnimationMemoryBlock();
// void LoadColourChannel__14tChannelLoaderP10tChunkFileP12tEntityStoreP21tAnimationMemoryBlock();
// void LoadEventChannel__14tChannelLoaderP10tChunkFileP12tEntityStoreP21tAnimationMemoryBlock();
// void __tf8tChannel();
// void __tf11tIntChannel();
// void __tf14tFloat1Channel();
// void __tf14tFloat2Channel();
// void __tf18tVector1DOFChannel();
// void __tf18tVector2DOFChannel();
// void __tf18tVector3DOFChannel();
// void __tf18tQuaternionChannel();
// void __tf28tCompressedQuaternionChannel();
// void __tf14tStringChannel();
// void __tf14tEntityChannel();
// void __tf12tBoolChannel();
// void __tf14tColourChannel();
// void __tf13tEventChannel();
// void __tf12tNonCopyable();
// void _$_8tChannel();
// void func_00343478();
// void _$_11tIntChannel();
// void _$_14tFloat1Channel();
// void _$_14tFloat2Channel();
// void _$_18tVector1DOFChannel();
// void func_003435E8();
// void _$_18tVector2DOFChannel();
// void func_00343648();
// void _$_18tVector3DOFChannel();
// void _$_18tQuaternionChannel();
// void _$_28tCompressedQuaternionChannel();
// void _$_14tStringChannel();
// void _$_14tEntityChannel();
// void _$_12tBoolChannel();
// void func_00343860();
// void _$_14tColourChannel();
// void _$_13tEventChannel();
// void __6tEvent();
// void func_00343950();
// void __tf14tVectorChannel();
// void __tf16tRotationChannel();
// void func_00343A10();

// rodata

// extern UNK_TYPE D_00491200;
// extern UNK_TYPE D_00491218;
// extern UNK_TYPE jtbl_00491230;
// extern UNK_TYPE D_00491278;
// extern UNK_TYPE D_00491280;
// extern UNK_TYPE _vt$13tEventChannel;
// extern UNK_TYPE _vt$14tColourChannel;
// extern UNK_TYPE _vt$12tBoolChannel;
// extern UNK_TYPE _vt$14tEntityChannel;
// extern UNK_TYPE _vt$14tStringChannel;
// extern UNK_TYPE _vt$28tCompressedQuaternionChannel;
// extern UNK_TYPE _vt$18tQuaternionChannel;
// extern UNK_TYPE _vt$18tVector3DOFChannel;
// extern UNK_TYPE _vt$18tVector2DOFChannel;
// extern UNK_TYPE _vt$18tVector1DOFChannel;
// extern UNK_TYPE _vt$14tFloat2Channel;
// extern UNK_TYPE _vt$14tFloat1Channel;
// extern UNK_TYPE _vt$11tIntChannel;
// extern UNK_TYPE _vt$8tChannel;
// extern UNK_TYPE D_004914C0;
// extern UNK_TYPE D_004914D0;
// extern UNK_TYPE D_004914E0;
// extern UNK_TYPE D_004914F8;
// extern UNK_TYPE D_00491510;
// extern UNK_TYPE D_00491528;
// extern UNK_TYPE D_00491540;
// extern UNK_TYPE D_00491558;
// extern UNK_TYPE D_00491570;
// extern UNK_TYPE D_00491590;
// extern UNK_TYPE D_004915A8;
// extern UNK_TYPE D_004915C0;
// extern UNK_TYPE D_004915D0;
// extern UNK_TYPE D_004915E8;
// extern UNK_TYPE D_004915F8;
// extern UNK_TYPE D_00491630;
// extern UNK_TYPE D_00491648;

#endif
