#ifndef IOSTREAM_H
#define IOSTREAM_H

// text

// void __7istreamiP9streambufP7ostream();
// void skip_ws__FP9streambuf();
// void get__7istreamRc();
// void peek__7istream();
// void ignore__7istreamii();
// void read__7istreamPci();
// void sync__7istream();
// void seekg__7istreaml();
// void seekg__7istreamlQ23ios8seek_dir();
// void tellg__7istream();
// void __rs__7istreamRc();
// void __rs__7istreamPc();
// void func_003F9A30();
// void __rs__7istreamRs();
// void __rs__7istreamRUs();
// void __rs__7istreamRi();
// void __rs__7istreamRUi();
// void __rs__7istreamRl();
// void __rs__7istreamRUl();
// void __rs__7istreamRx();
// void __rs__7istreamRUx();
// void __rs__7istreamRb();
// void __rs__7istreamRr();
// void __rs__7istreamRd();
// void __rs__7istreamRf();
// void __rs__7istreamP9streambuf();
// void __ls__7ostreamc();
// void func_003FA3B8();
// void __ls__7ostreami();
// void __ls__7ostreamUi();
// void __ls__7ostreaml();
// void __ls__7ostreamUl();
// void __ls__7ostreamx();
// void __ls__7ostreamUx();
// void __ls__7ostreamd();
// void __ls__7ostreamPCc();
// void __ls__7ostreamP9streambuf();
// void __7ostreamiP9streambufP7ostream();
// void seekp__7ostreaml();
// void seekp__7ostreamlQ23ios8seek_dir();
// void tellp__7ostream();
// void flush__7ostream();
// void flush__FR7ostream();
// void ws__FR7istream();
// void _skip_ws__7istream();
// void ends__FR7ostream();
// void endl__FR7ostream();
// void lock__FR7istream();
// void unlock__FR7istream();
// void lock__FR7ostream();
// void unlock__FR7ostream();
// void write__7ostreamPCci();
// void do_osfx__7ostream();
// void __8iostreamiP9streambufP7ostream();
// void close__3ios();
// void skip__7istreami();
// void oct__FR3ios();
// void hex__FR3ios();
// void dec__FR3ios();
// void __as__22_IO_ostream_withassignR22_IO_ostream_withassign();
// void __tf22_IO_ostream_withassign();
// void _$_22_IO_ostream_withassign();
// void __as__22_IO_istream_withassignR22_IO_istream_withassign();
// void __tf22_IO_istream_withassign();
// void _$_22_IO_istream_withassign();
// void __8iostreami();
// void __tf8iostream();
// void _$_8iostream();
// void __rs__7istreamPFR7istream_R7istream();
// void __rs__7istreamPFR3ios_R3ios();
// void __rs__7istreamRSc();
// void __rs__7istreamRUc();
// void __rs__7istreamPSc();
// void __rs__7istreamPUc();
// void istreambuf__C7istream();
// void unget__7istreamc();
// void unget__7istream();
// void putback__7istreamc();
// void gcount__7istream();
// void get__7istream();
// void isfx__7istream();
// void ipfx1__7istream();
// void ipfx0__7istream();
// void ipfx__7istreami();
// void read__7istreamPvi();
// void read__7istreamPSci();
// void read__7istreamPUci();
// void getline__7istreamPScic();
// void get__7istreamPScic();
// void get__7istreamRSc();
// void getline__7istreamPUcic();
// void get__7istreamRUc();
// void get__7istreamPUcic();
// void __7istreami();
// void __tf7istream();
// void _$_7istream();
// void ostreambuf__C7ostream();
// void __ls__7ostreamPFR3ios_R3ios();
// void __ls__7ostreamPFR7ostream_R7ostream();
// void __ls__7ostreamr();
// void __ls__7ostreamf();
// void __ls__7ostreamb();
// void __ls__7ostreamUs();
// void __ls__7ostreams();
// void __ls__7ostreamPCSc();
// void __ls__7ostreamPCUc();
// void __ls__7ostreamSc();
// void __ls__7ostreamUc();
// void write__7ostreamPCvi();
// void write__7ostreamPCSci();
// void write__7ostreamPCUci();
// void put__7ostreamSc();
// void put__7ostreamUc();
// void put__7ostreamc();
// void osfx__7ostream();
// void opfx__7ostream();
// void __7ostreami();
// void __tf7ostream();
// void _$_7ostream();

// rodata

// extern UNK_TYPE D_004ACBE0;
// extern UNK_TYPE D_004ACBE8;
// extern UNK_TYPE D_004ACBF0;
// extern UNK_TYPE D_004ACBF8;
// extern UNK_TYPE D_004ACC10;
// extern UNK_TYPE D_004ACC28;
// extern UNK_TYPE _vt$22_IO_ostream_withassign$3ios;
// extern UNK_TYPE _vt$22_IO_istream_withassign$3ios;
// extern UNK_TYPE _vt$8iostream$3ios;
// extern UNK_TYPE _vt$7istream$3ios;
// extern UNK_TYPE _vt$7ostream$3ios;
// extern UNK_TYPE D_004ACC80;
// extern UNK_TYPE D_004ACCA0;
// extern UNK_TYPE D_004ACCA8;
// extern UNK_TYPE D_004ACCC8;
// extern UNK_TYPE D_004ACCD0;
// extern UNK_TYPE D_004ACCE0;
// extern UNK_TYPE D_004ACCF0;
// extern UNK_TYPE D_004ACD00;
// extern UNK_TYPE D_004ACD08;

// data

// extern UNK_TYPE _GLOBAL_$F$__7istreamiP9streambufP7ostream;

#endif
