#ifndef STREAMBUF_HPP
#define STREAMBUF_HPP

// text

// void _un_link__9streambuf();
// void _link_in__9streambuf();
// void switch_to_get_mode__9streambuf();
// void free_backup_area__9streambuf();
// void __overflow__FP9streambufi();
// void underflow__9streambuf();
// void uflow__9streambuf();
// void overflow__9streambufi();
// void xsputn__9streambufPCcl();
// void xsgetn__9streambufPcl();
// void ignore__9streambufi();
// void sync__9streambuf();
// void pbackfail__9streambufi();
// void setbuf__9streambufPci();
// void seekpos__9streambufli();
// void sseekpos__9streambufli();
// void setb__9streambufPcT1i();
// void doallocate__9streambuf();
// void doallocbuf__9streambuf();
// void __9streambufi();
// void _$_9streambuf();
// void seekoff__9streambuflQ23ios8seek_diri();
// void sseekoff__9streambuflQ23ios8seek_diri();
// void sputbackc__9streambufc();
// void sungetc__9streambuf();
// void get_column__9streambuf();
// void set_column__9streambufi();
// void flush_all__9streambuf();
// void flush_all_linebuffered__9streambuf();
// void sys_stat__9streambufPv();
// void sys_read__9streambufPcl();
// void sys_write__9streambufPCcl();
// void sys_seek__9streambuflQ23ios8seek_dir();
// void sys_close__9streambuf();
// void __12streammarkerP9streambuf();
// void _$_12streammarker();
// void delta__12streammarkerR12streammarker();
// void delta__12streammarker();
// void seekmark__9streambufR12streammarkeri();
// void unsave_markers__9streambuf();
// void readable__3ios();
// void writable__3ios();
// void is_open__3ios();
// void _GLOBAL_$D$_un_link__9streambuf();
// void _GLOBAL_$I$_un_link__9streambuf();
// void _$_3ios();
// void __3iosP9streambufP7ostream();
// void init__3iosP9streambufP7ostream();
// void file_ptr__7filebuf();
// void cur_ptr__7filebuf();
// void is_reading__7filebuf();
// void fd__C7filebuf();
// void is_open__C7filebuf();
// void __tf7filebuf();
// void stossc__9streambuf();
// void snextc__9streambuf();
// void sgetc__9streambuf();
// void sbumpc__9streambuf();
// void sputc__9streambufi();
// void sgetn__9streambufPcl();
// void padn__9streambufcl();
// void sputn__9streambufPCcl();
// void out_waiting__9streambuf();
// void in_avail__9streambuf();
// void allocbuf__9streambuf();
// void allocate__9streambuf();
// void linebuffered__9streambufi();
// void unbuffered__9streambufi();
// void linebuffered__9streambuf();
// void unbuffered__9streambuf();
// void pubseekpos__9streambufli();
// void pubseekoff__9streambuflQ23ios8seek_diri();
// void put_mode__9streambuf();
// void have_markers__9streambuf();
// void have_backup__9streambuf();
// void eNptr__9streambuf();
// void Nbase__9streambuf();
// void eBptr__9streambuf();
// void Bptr__9streambuf();
// void Bbase__9streambuf();
// void eGptr__9streambuf();
// void Gbase__9streambuf();
// void in_backup__9streambuf();
// void shortbuf__9streambuf();
// void setg__9streambufPcT1T1();
// void setp__9streambufPcT1();
// void pbump__9streambufi();
// void gbump__9streambufi();
// void xsetflags__9streambufii();
// void xsetflags__9streambufi();
// void xflags__9streambufi();
// void xflags__9streambuf();
// void xput_char__9streambufc();
// void blen__C9streambuf();
// void ebuf__C9streambuf();
// void base__C9streambuf();
// void eback__C9streambuf();
// void pbase__C9streambuf();
// void epptr__C9streambuf();
// void egptr__C9streambuf();
// void pptr__C9streambuf();
// void gptr__C9streambuf();
// void xchain__9streambuf();
// void _vtable__9streambuf();
// void __tf9streambuf();
// void saving__12streammarker();
// void set_offset__12streammarkeri();
// void __Q23ios4Init();
// void unset__3ios11state_value();
// void sync_with_stdio__3ios();
// void rdbuf__3iosP9streambuf();
// void rdbuf__C3ios();
// void exceptions__3iosi();
// void exceptions__C3ios();
// void __nt__C3ios();
// void __opPv__C3ios();
// void rdstate__C3ios();
// void bad__C3ios();
// void fail__C3ios();
// void eof__C3ios();
// void good__C3ios();
// void setstate__3iosi();
// void set__3iosi();
// void clear__3iosi();
// void _throw_failure__C3ios();
// void width__3iosi();
// void width__C3ios();
// void unsetf__3iosUl();
// void setf__3iosUlUl();
// void setf__3iosUl();
// void precision__3iosi();
// void precision__C3ios();
// void flags__3iosUl();
// void flags__C3ios();
// void fill__3ioss();
// void fill__C3ios();
// void tie__3iosP7ostream();
// void tie__C3ios();
// void __tf3ios();
// void __tf11_ios_fields();
// void __tf8_IO_FILE();

// rodata

// extern UNK_TYPE _vt$7filebuf;
// extern UNK_TYPE _vt$9streambuf;
// extern UNK_TYPE _vt$3ios;
// extern UNK_TYPE D_004ACE48;
// extern UNK_TYPE D_004ACE58;
// extern UNK_TYPE D_004ACE68;
// extern UNK_TYPE D_004ACE70;
// extern UNK_TYPE D_004ACE80;

// data

// extern UNK_TYPE io_defs__;
// extern UNK_TYPE D_004401E9;
// extern UNK_TYPE _GLOBAL_$F$_un_link__9streambuf;

#endif
