#ifndef ALLCHARACTER_HPP
#define ALLCHARACTER_HPP

// text

// void __6Wander();
// void _$_6Wander();
// void func_0025DF68();
// void Tick__6WanderR9Character();
// void Update__21AICharacterControllerf();
// void GetValue__C21AICharacterControlleri();
// void IsButtonDown__C21AICharacterControlleri();
// void __11NPCharacter();
// void _$_11NPCharacter();
// void OnUpdateRoot__11NPCharacterf();
// void OnPostSimUpdate__11NPCharacterf();
// void __9Character();
// void Init__9Character();
// void InitGroundPlane__9Character();
// void SetPuppet__9CharacterPQ26choreo6Puppet();
// void SetYAdjust__9Characterf();
// void ResetSpeed__9Character();
// void Kick__9Character();
// void Slam__9Character();
// void RelocateAndReset__9CharacterRCQ218RadicalMathLibrary6VectorfbT3();
// void AddToPhysics__9Character();
// void RemoveFromPhysics__9Character();
// void AddToPhysics__11NPCharacter();
// void RemoveFromPhysics__11NPCharacter();
// void _$_9Character();
// void UpdateParentTransform__9Characterf();
// void SetParentTransform__9CharacterRCQ218RadicalMathLibrary6Matrixf();
// void UpdateGroundPlane__9Characterf();
// void PreSimUpdate__9Characterf();
// void ResetCollisions__9Character();
// void UpdateController__9CharacterRQ218RadicalMathLibrary6Vectorf();
// void UpdateDesiredDirAndSpeed__9CharacterRCQ218RadicalMathLibrary6Vector();
// void UpdateRoot__9Characterf();
// void OnUpdateRoot__9Characterf();
// void UpdatePuppet__9Characterf();
// void TestInAnyonesFrustrum__9Character();
// void PostSimUpdate__9Characterf();
// void ResolveCollisions__9Character();
// void UpdateFootPlant__9Character();
// void OnPostSimUpdate__9Characterf();
// void UpdateShock__9Characterf();
// void AddToWorldScene__9Character();
// void RemoveFromWorldScene__9Character();
// void MoveInWorldScene__9Character();
// void UpdateSimState__9Characterf();
// void UpdateBBox__9CharacterRQ218RadicalMathLibrary5Box3D();
// void PreReactToCollision__9CharacterPQ23sim8SimStateRQ23sim9Collision();
// void PostReactToCollision__9CharacterRQ218RadicalMathLibrary6VectorRQ23sim9Collision();
// void SolveCollisionWithStatic__9CharacterRCQ218RadicalMathLibrary6VectorRQ218RadicalMathLibrary6Vector();
// void GetMaxSpeed__C9Character();
// void GetTerrainIntersect__C9CharacterRQ218RadicalMathLibrary6VectorT1();
// void GetTerrainType__C9CharacterR12eTerrainTypeRb();
// void SnapToGround__9Character();
// void UpdateGroundHeight__9Character();
// void pPosition__9Character();
// void rPosition__9Character();
// void GetPosition__9CharacterPQ218RadicalMathLibrary6Vector();
// void SetFadeAlpha__9Characteri();
// void CastsShadow__9Character();
// void DisplayShadow__9Character();
// void DisplaySimpleShadow__9Character();
// void CanPlayAnimation__C9CharacterRC5tName();
// void func_00264EF0();
// void CanStandOnCollisionNormal__C9CharacterRCQ218RadicalMathLibrary6Vector();
// void FindStandingVolume__9CharacterRCQ218RadicalMathLibrary6VectorPQ23sim15CollisionVolumeRQ218RadicalMathLibrary6VectorRf();
// void GetCollisionHeight__9CharacterRCQ218RadicalMathLibrary6VectorT1RQ218RadicalMathLibrary6VectorT3();
// void SetStandingJoint__9CharacterPCQ25poser5Joint();
// void SetGroundPoint__9CharacterRCQ218RadicalMathLibrary6Vector();
// void UpdateTransformToLoco__9Character();
// void AssignCollisionAreaIndex__9Character();
// void UpdateTransformToInCar__9Character();
// void SetInCar__9Characterb();
// void GetActionButtonHandler__C9Character();
// void AddActionButtonHandler__9CharacterPQ212ActionButton13ButtonHandler();
// void RemoveActionButtonHandler__9CharacterPQ212ActionButton13ButtonHandler();
// void TestPriority__9CharacterPQ212ActionButton13ButtonHandlerT1();
// void ClearAllActionButtonHandlers__9Character();
// void __Q29Character4Prop();
// void _$_Q29Character4Prop();
// void TouchProp__9CharacterP15InstDynaPhysDSG();
// void AttachProp__9CharacterP15InstDynaPhysDSG();
// void UpdatePhysicsObjects__9Characterfi();
// void SubmitStatics__9Character();
// void SubmitAnimCollisions__9Character();
// void SubmitDynamics__9Character();
// void PosInFrustrumOfPlayer__9CharacterRCQ218RadicalMathLibrary6Vectori();
// void TestInFrustrumOfPlayer__9Characteri();
// void SetShadowColour__9CharacterG10pddiColour();
// void GetShadowColour__9Character();
// void SetSwatch__9Characteri();
// void SetDrawable__9CharacterP19CharacterRenderable();
// void Shock__9Characterf();
// void DoKickwave__9Character();
// void OnTransitToAICtrl__9Character();
// void Display__9Character();
// void SetAmbient__9CharacterPCcf();
// void EnableAmbientDialogue__9Characterb();
// void ResetAmbientPosition__9Character();
// void UpdatePhysicsObjects__11NPCharacterfi();
// void AssignCollisionAreaIndex__11NPCharacter();
// void SubmitStatics__11NPCharacter();
// void SubmitDynamics__11NPCharacter();
// void OnTransitToAICtrl__11NPCharacter();
// void ApplyForce__11NPCharacterRCQ218RadicalMathLibrary6Vectorf();
// void ApplyKickForce__11NPCharacterRCQ218RadicalMathLibrary6Vectorf();
// void __19CharacterController();
// void _$_19CharacterController();
// void GetCharacter__C19CharacterController();
// void SetCharacter__19CharacterControllerP9Character();
// void __18PhysicalController();
// void _$_18PhysicalController();
// void SetCharacterMappable__18PhysicalControllerP17CharacterMappable();
// void GetDirection__18PhysicalControllerRQ218RadicalMathLibrary6Vector();
// void GetValue__C18PhysicalControlleri();
// void IsButtonDown__C18PhysicalControlleri();
// void TimeSinceChange__C18PhysicalControlleri();
// void GetCharacterMappable__C18PhysicalController();
// void __33CameraRelativeCharacterController();
// void Create__33CameraRelativeCharacterControllerP9CharacterP17CharacterMappable();
// void _$_33CameraRelativeCharacterController();
// void SetIntention__33CameraRelativeCharacterControllerQ219CharacterController10eIntention();
// void GetDirection__33CameraRelativeCharacterControllerRQ218RadicalMathLibrary6Vector();
// void SetCamera__33CameraRelativeCharacterControllerP7tCamera();
// void HandleEvent__33CameraRelativeCharacterControlleriPv();
// void __13NPCController();
// void _$_13NPCController();
// void SetCharacter__13NPCControllerP9Character();
// void AddNPCWaypoint__13NPCControllerRCQ218RadicalMathLibrary6Vector();
// void IncitePanic__13NPCController();
// void QuellPanic__13NPCController();
// void Update__13NPCControllerf();
// void GetFollowPathSpeedMps__C13NPCController();
// void FollowPath__13NPCControllerf();
// void TeleportToPath__13NPCController();
// void DetectAndDodge__13NPCControllerf();
// void TraversePath__13NPCControllerf();
// void OnReachedWaypoint__13NPCController();
// void Detect__13NPCControllerfRf();
// void PerformCringe__13NPCController();
// void PerformDodge__13NPCController();
// void GetDirection__13NPCControllerRQ218RadicalMathLibrary6Vector();
// void TransitToState__13NPCControllerQ213NPCController5State();
// void GetAllowedPathOffset__13NPCControllerRQ218RadicalMathLibrary6Vector();
// void OnOffPath__13NPCControllerGQ218RadicalMathLibrary6VectorT1();
// void StartTalking__13NPCController();
// void StopTalking__13NPCController();
// void SetTempWaypont__13NPCControllerRCQ218RadicalMathLibrary6Vector();
// void ClearTempWaypoint__13NPCController();
// void CreateInstance__16CharacterManager();
// void GetInstance__16CharacterManager();
// void DestroyInstance__16CharacterManager();
// void __16CharacterManager();
// void _$_16CharacterManager();
// void PreLoad__16CharacterManager();
// void Destroy__16CharacterManagerb();
// void RemoveCharacter__16CharacterManagerP9Character();
// void SetGarbage__16CharacterManagerP9Characterb();
// void GarbageCollectModel__16CharacterManagerUi();
// void GarbageCollectAnim__16CharacterManagerUi();
// void IsModelLoaded__16CharacterManagerPCc();
// void func_0026BC30();
// void LoadModel__16CharacterManagerPCcPQ214LoadingManager23ProcessRequestsCallbackPv();
// void LoadAnimation__16CharacterManagerPCc();
// void FindLoad__16CharacterManagerPQ216CharacterManager4LoadG13tUidUnaligned();
// void AllocLoad__16CharacterManagerPQ216CharacterManager4LoadG13tUidUnaligned();
// void GetState__16CharacterManagerPQ216CharacterManager4LoadG13tUidUnaligned();
// void FillLoadData__16CharacterManagerRQ216CharacterManager17CharacterLoadDataPCcT2();
// void AddCharacter__16CharacterManagerQ216CharacterManager13CharacterTypePCcN32();
// void AddCharacterDeferedLoad__16CharacterManagerQ216CharacterManager13CharacterTypePCcN32();
// void SwapData__16CharacterManagerP9CharacterPCcT2();
// void InternalSwapData__16CharacterManagerP9CharacterPCcT2();
// void SetupCharacter__16CharacterManagerRQ216CharacterManager17CharacterLoadDataP9Character();
// void GarbageCollect__16CharacterManagerb();
// void PreSimUpdate__16CharacterManagerf();
// void PostSimUpdate__16CharacterManagerf();
// void Update__16CharacterManagerf();
// void PreSubstepUpdate__16CharacterManagerf();
// void PostSubstepUpdate__16CharacterManagerf();
// void ClearTargetVehicle__16CharacterManagerP7Vehicle();
// void ResetBonusCharacters__16CharacterManager();
// void AddCharacter__16CharacterManagerP9CharacterQ216CharacterManager13CharacterType();
// void OnProcessRequestsComplete__16CharacterManagerPv();
// void GetCharacterByName__C16CharacterManagerPCc();
// void GetCharacterByName__C16CharacterManagerG13tUidUnaligned();
// void GetMissionCharacter__C16CharacterManagerPCc();
// void GetCharacter__C16CharacterManageri();
// void HandleEvent__16CharacterManager9EventEnumPv();
// void GetModelName__16CharacterManagerP9Character();
// void GetAnimName__16CharacterManagerP9Character();
// void SubmitStatics__16CharacterManager();
// void SubmitAnimCollisions__16CharacterManager();
// void SubmitDynamics__16CharacterManager();
// void SetCharacterPosition__16CharacterManageriPPc();
// void ResetCharacter__16CharacterManageriPPc();
// void SetInitialWalk__16CharacterManageriPPc();
// void func_0026FB70();
// void NextCheatModel__16CharacterManager();
// void GetNumTeleportDests__16CharacterManager();
// void GetTeleportDest__16CharacterManagerUi();
// void ClearTeleportDests__16CharacterManager();
// void AddTeleportDest__16CharacterManageriPPc();
// void DoTeleport__16CharacterManagerPv();
// void GetCharacterIndex__C16CharacterManagerPC9Character();
// void __17CharacterMappable();
// void _$_17CharacterMappable();
// void GetCharacterController__C17CharacterMappable();
// void SetCharacterController__17CharacterMappableP19CharacterController();
// void OnButton__17CharacterMappableiiPC6Button();
// void OnButtonUp__17CharacterMappableiiPC6Button();
// void OnButtonDown__17CharacterMappableiiPC6Button();
// void LoadControllerMappings__17CharacterMappableUi();
// void GetDirection__C17CharacterMappableRQ218RadicalMathLibrary6Vector();
// void __22BipedCharacterMappable();
// void _$_22BipedCharacterMappable();
// void OnButtonDown__22BipedCharacterMappableiiPC6Button();
// void GetDirection__C22BipedCharacterMappableRQ218RadicalMathLibrary6Vector();
// void __22InCarCharacterMappable();
// void _$_22InCarCharacterMappable();
// void OnButtonDown__22InCarCharacterMappableiiPC6Button();
// void GetDirection__C22InCarCharacterMappableRQ218RadicalMathLibrary6Vector();
// void __19CharacterRenderableP13tDrawablePoseN21();
// void _$_19CharacterRenderable();
// void Display__19CharacterRenderableGQ218RadicalMathLibrary6VectorP5tPose();
// void CastsShadow__19CharacterRenderable();
// void DisplayShadow__19CharacterRenderableP5tPosePC16BlobShadowParams();
// void GetDrawable__C19CharacterRenderable();
// void SetLOD__19CharacterRenderablei();
// void SetSwatch__19CharacterRenderablei();
// void SetSwatchTexture__19CharacterRenderableiP8tTexture();
// void SetShockEffect__19CharacterRenderableP9tDrawable();
// void SetSwatchShader__19CharacterRenderableP7tShader();
// void SetFadeAlpha__19CharacterRenderablei();
// void SetShadowColour__19CharacterRenderableG10pddiColour();
// void DisplayModel__19CharacterRenderableP5tPose();
// void DisplayShocked__19CharacterRenderableP5tPose();
// void __15CharacterTargetP9Character();
// void _$_15CharacterTarget();
// void GetPosition__15CharacterTargetPQ218RadicalMathLibrary6Vector();
// void GetHeading__15CharacterTargetPQ218RadicalMathLibrary6Vector();
// void GetVUP__15CharacterTargetPQ218RadicalMathLibrary6Vector();
// void GetVelocity__15CharacterTargetPQ218RadicalMathLibrary6Vector();
// void GetID__15CharacterTarget();
// void IsCar__C15CharacterTarget();
// void IsAirborn__15CharacterTarget();
// void IsUnstable__15CharacterTarget();
// void IsQuickTurn__15CharacterTarget();
// void GetFirstPersonPosition__15CharacterTargetPQ218RadicalMathLibrary6Vector();
// void GetName__15CharacterTarget();
// void IsInReverse__15CharacterTarget();
// void GetTerrainIntersect__C15CharacterTargetRQ218RadicalMathLibrary6VectorT1();
// void func_002723B0();
// void __12TeleportDest();
// void func_002723D8();
// void __tf19CharacterController();
// void __tf13NPCController();
// void __tf18PhysicalController();
// void __tf33CameraRelativeCharacterController();
// void _$_21AICharacterController();
// void __tf21AICharacterController();
// void func_002727B8();
// void __tf9Character();
// void __tf11NPCharacter();
// void __tf16CharacterManager();
// void __tf6Wander();
// void __tf17CharacterMappable();
// void __tf22BipedCharacterMappable();
// void __tf22InCarCharacterMappable();
// void __tf15CharacterTarget();
// void func_00272A90();
// void _$_21AmbientDialogueButton();
// void __tf21AmbientDialogueButton();
// void __tf22AmbientDialogueTrigger();
// void __tf45CameraRelativeCharacterControllerEventHandler();
// void func_00272BE8();
// void Update__19CharacterControllerf();
// void TimeSinceChange__C19CharacterControlleri();
// void SetIntention__19CharacterControllerQ219CharacterController10eIntention();
// void __Q213NPCController9DodgeInfo();
// void GetState__C13NPCController();
// void GetSpeedMps__C13NPCController();
// void SetSpeedMps__13NPCControllerf();
// void SetDirection__13NPCControllerRCQ218RadicalMathLibrary6Vector();
// void GetValue__C13NPCControlleri();
// void IsButtonDown__C13NPCControlleri();
// void SetIntention__18PhysicalControllerQ219CharacterController10eIntention();
// void func_00272CA8();
// void _$_15ISuperCamTarget();
// void func_00272CE0();
// void GetAIRef__9Character();
// void Update__9Characterf();
// void ApplyForce__9CharacterRCQ218RadicalMathLibrary6Vectorf();
// void GetInputScale__9Character();
// void func_00272D30();
// void GetAIRef__11NPCharacter();
// void SubmitAnimCollisions__11NPCharacter();
// void GetInputScale__11NPCharacter();
// void UpdateFootPlant__11NPCharacter();
// void func_00272D98();
// void _$_Q216CharacterManager17CharacterLoadData();
// void __Q216CharacterManager17CharacterLoadData();
// void func_00272E98();
// void __9Behaviour();
// void OnButtonPressed__21AmbientDialogueButtonP9CharacterP9Sequencer();
// void _$_22AmbientDialogueTrigger();
// void Trigger__22AmbientDialogueTriggerUib();
// void func_00273088();
// void _$_45CameraRelativeCharacterControllerEventHandler();
// void HandleEvent__45CameraRelativeCharacterControllerEventHandler9EventEnumPv();
// void __Q216radLoadInventoryt8SafeCast1Z13tDrawablePose();
// void func_00273118();
// void __Q216radLoadInventoryt8SafeCast1Z9tSkeleton();
// void __Q216radLoadInventoryt8SafeCast1ZQ26choreo4Bank();
// void func_00273198();
// void __tfQ216radLoadInventoryt8SafeCast1Z13tDrawablePose();
// void func_00273240();
// void __tfQ216radLoadInventoryt8SafeCast1Z9tSkeleton();
// void __tfQ216radLoadInventoryt8SafeCast1ZQ26choreo4Bank();
// void func_00273300();
// void safe_cast__Q216radLoadInventoryt8SafeCast1ZQ26choreo4BankP9IRefCount();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z9tSkeletonP9IRefCount();
// void func_002733A8();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z13tDrawablePoseP9IRefCount();
// void func_00273408();
// void _GLOBAL_$I$__6Wander();
// void _GLOBAL_$D$__6Wander();

// data

// extern UNK_TYPE D_00430428;
// extern UNK_TYPE D_0043042C;
// extern UNK_TYPE D_00430430;
// extern UNK_TYPE _9Character$msIntersectInfo;
// extern UNK_TYPE D_00430464;
// extern UNK_TYPE D_0043046D;
// extern UNK_TYPE D_0043046E;
// extern UNK_TYPE D_0043046F;
// extern UNK_TYPE D_00430470;
// extern UNK_TYPE D_00430474;
// extern UNK_TYPE D_00430480;
// extern UNK_TYPE D_00430484;
// extern UNK_TYPE _Q29Character4Prop$spSkeleton;
// extern UNK_TYPE _Q29Character4Prop$sSkelRefs;
// extern UNK_TYPE D_00430490;
// extern UNK_TYPE D_00430494;
// extern UNK_TYPE D_00430498;
// extern UNK_TYPE D_0043049C;
// extern UNK_TYPE D_004304A0;
// extern UNK_TYPE D_004304A4;
// extern UNK_TYPE D_004304A8;
// extern UNK_TYPE D_004304AC;
// extern UNK_TYPE D_004304B0;
// extern UNK_TYPE D_004304B4;
// extern UNK_TYPE _16CharacterManager$spCharacterManager;
// extern UNK_TYPE D_004304BC;
// extern UNK_TYPE _13CharacterTune$sGetInPosition;
// extern UNK_TYPE D_004304CC;
// extern UNK_TYPE g_Blinkers;
// extern UNK_TYPE _16CharacterManager$sInitialWalkLocator;
// extern UNK_TYPE _16CharacterManager$sCharacterToSpawn;
// extern UNK_TYPE _16CharacterManager$sSpawnedCharacter;
// extern UNK_TYPE D_00430B54;
// extern UNK_TYPE D_00430D18;
// extern UNK_TYPE D_004339D4;
// extern UNK_TYPE D_004339D8;
// extern UNK_TYPE D_004339DC;
// extern UNK_TYPE s_teleportDests;
// extern UNK_TYPE D_00435DE0;

// bss

// extern UNK_TYPE D_004B2838;
// extern UNK_TYPE D_004B2840;
// extern UNK_TYPE D_004B284C;
// extern UNK_TYPE D_004B285C;
// extern UNK_TYPE D_004B2860;
// extern UNK_TYPE D_004B28E8;
// extern UNK_TYPE D_004B28F0;
// extern UNK_TYPE D_004B28F8;
// extern UNK_TYPE D_004B2900;
// extern UNK_TYPE D_004B2908;
// extern UNK_TYPE D_004B2934;

// rodata

// extern UNK_TYPE D_00479550;
// extern UNK_TYPE D_00479568;
// extern UNK_TYPE D_00479570;
// extern UNK_TYPE D_00479580;
// extern UNK_TYPE D_00479588;
// extern UNK_TYPE D_00479590;
// extern UNK_TYPE D_004795A0;
// extern UNK_TYPE D_004795B0;
// extern UNK_TYPE D_004795C0;
// extern UNK_TYPE D_004796A8;
// extern UNK_TYPE D_004796B0;
// extern UNK_TYPE D_004796C0;
// extern UNK_TYPE jtbl_004796E0;
// extern UNK_TYPE D_00479700;
// extern UNK_TYPE D_00479710;
// extern UNK_TYPE jtbl_00479720;
// extern UNK_TYPE jtbl_00479750;
// extern UNK_TYPE D_00479770;
// extern UNK_TYPE D_00479788;
// extern UNK_TYPE D_004797A8;
// extern UNK_TYPE D_004797B8;
// extern UNK_TYPE D_004797E0;
// extern UNK_TYPE D_004797F0;
// extern UNK_TYPE D_00479818;
// extern UNK_TYPE D_00479828;
// extern UNK_TYPE D_00479850;
// extern UNK_TYPE D_00479858;
// extern UNK_TYPE D_00479870;
// extern UNK_TYPE D_00479888;
// extern UNK_TYPE D_00479890;
// extern UNK_TYPE D_00479898;
// extern UNK_TYPE D_004798B0;
// extern UNK_TYPE D_004798B8;
// extern UNK_TYPE D_004798D0;
// extern UNK_TYPE D_004798E8;
// extern UNK_TYPE D_004798F0;
// extern UNK_TYPE D_004798F8;
// extern UNK_TYPE D_00479900;
// extern UNK_TYPE D_00479970;
// extern UNK_TYPE D_00479978;
// extern UNK_TYPE D_00479980;
// extern UNK_TYPE D_00479988;
// extern UNK_TYPE D_00479990;
// extern UNK_TYPE D_00479998;
// extern UNK_TYPE D_004799A0;
// extern UNK_TYPE D_004799B8;
// extern UNK_TYPE D_004799C0;
// extern UNK_TYPE D_004799D0;
// extern UNK_TYPE D_004799E8;
// extern UNK_TYPE D_00479A00;
// extern UNK_TYPE D_00479A18;
// extern UNK_TYPE D_00479A30;
// extern UNK_TYPE D_00479A48;
// extern UNK_TYPE D_00479A58;
// extern UNK_TYPE D_00479A60;
// extern UNK_TYPE D_00479AB0;
// extern UNK_TYPE D_00479AC0;
// extern UNK_TYPE D_00479AD0;
// extern UNK_TYPE D_00479AD8;
// extern UNK_TYPE D_00479AE8;
// extern UNK_TYPE D_00479AF8;
// extern UNK_TYPE D_00479B08;
// extern UNK_TYPE D_00479B18;
// extern UNK_TYPE D_00479B20;
// extern UNK_TYPE D_00479B28;
// extern UNK_TYPE _vt$45CameraRelativeCharacterControllerEventHandler;
// extern UNK_TYPE _vt$22AmbientDialogueTrigger$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$22AmbientDialogueTrigger;
// extern UNK_TYPE _vt$21AmbientDialogueButton;
// extern UNK_TYPE _vt$15CharacterTarget$18IHudMapIconLocator;
// extern UNK_TYPE _vt$15CharacterTarget;
// extern UNK_TYPE _vt$22InCarCharacterMappable;
// extern UNK_TYPE _vt$22BipedCharacterMappable;
// extern UNK_TYPE _vt$17CharacterMappable;
// extern UNK_TYPE _vt$6Wander;
// extern UNK_TYPE _vt$16CharacterManager$Q214LoadingManager23ProcessRequestsCallback;
// extern UNK_TYPE _vt$16CharacterManager;
// extern UNK_TYPE _vt$11NPCharacter$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$11NPCharacter;
// extern UNK_TYPE _vt$9Character$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$9Character;
// extern UNK_TYPE _vt$15ISuperCamTarget;
// extern UNK_TYPE _vt$21AICharacterController;
// extern UNK_TYPE _vt$33CameraRelativeCharacterController;
// extern UNK_TYPE _vt$18PhysicalController;
// extern UNK_TYPE _vt$13NPCController;
// extern UNK_TYPE _vt$19CharacterController;
// extern UNK_TYPE D_0047A600;
// extern UNK_TYPE D_0047A618;
// extern UNK_TYPE D_0047A628;
// extern UNK_TYPE D_0047A640;
// extern UNK_TYPE D_0047A668;
// extern UNK_TYPE D_0047A698;
// extern UNK_TYPE D_0047A6A8;
// extern UNK_TYPE D_0047A6B0;
// extern UNK_TYPE D_0047A6C0;
// extern UNK_TYPE D_0047A6C8;
// extern UNK_TYPE D_0047A6E0;
// extern UNK_TYPE D_0047A6F0;
// extern UNK_TYPE D_0047A6F8;
// extern UNK_TYPE D_0047A710;
// extern UNK_TYPE D_0047A730;
// extern UNK_TYPE D_0047A750;
// extern UNK_TYPE D_0047A768;
// extern UNK_TYPE D_0047A790;
// extern UNK_TYPE D_0047A7A8;
// extern UNK_TYPE D_0047A7C8;
// extern UNK_TYPE D_0047A7D0;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1ZQ26choreo4Bank;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z9tSkeleton;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z13tDrawablePose;
// extern UNK_TYPE D_0047AAE0;
// extern UNK_TYPE D_0047AB70;
// extern UNK_TYPE D_0047ABA0;

#endif
