#ifndef ALLCAMERA_HPP
#define ALLCAMERA_HPP

// text

// void Abort__11AnimatedCam();
// void __11AnimatedCam();
// void _$_11AnimatedCam();
// void AllowSkipping__11AnimatedCamb();
// void CameraSwitchPending__11AnimatedCam();
// void CheckPendingCameraSwitch__11AnimatedCam();
// void ClearCamera__11AnimatedCam();
// void GetName__C11AnimatedCam();
// void GetType__11AnimatedCam();
// void LetterBoxStart__11AnimatedCam();
// void LetterBoxStop__11AnimatedCam();
// void LookupCamera__11AnimatedCam();
// void LookupMulticontroller__11AnimatedCam();
// void OnInit__11AnimatedCam();
// void OnShutdown__11AnimatedCam();
// void Reset__11AnimatedCam();
// void SetCamera__11AnimatedCamG5tName();
// void SetMulticontroller__11AnimatedCamG5tName();
// void SetMissionStartCamera__11AnimatedCamG5tName();
// void SetMissionStartMulticontroller__11AnimatedCamG5tName();
// void SetNextCameraType__11AnimatedCamQ28SuperCam4Type();
// void SetTarget__11AnimatedCamP15ISuperCamTarget();
// void Skip__11AnimatedCam();
// void TriggerMissionStartCamera__11AnimatedCam();
// void SetCameraSwitchPending__11AnimatedCamb();
// void SetCameraTransitionFlags__11AnimatedCami();
// void SupressNextLetterbox__11AnimatedCam();
// void Update__11AnimatedCamUi();
// void __9BumperCam();
// void _$_9BumperCam();
// void Update__9BumperCamUi();
// void UpdateForPhysics__9BumperCamUi();
// void LoadSettings__9BumperCamPUc();
// void SetCollisionOffset__9BumperCamPCQ218RadicalMathLibrary6VectorUiRCQ218RadicalMathLibrary6Vector();
// void OnRegisterDebugControls__9BumperCam();
// void OnUnregisterDebugControls__9BumperCam();
// void __8ChaseCam();
// void _$_8ChaseCam();
// void Update__8ChaseCamUi();
// void LoadSettings__8ChaseCamPUc();
// void OnRegisterDebugControls__8ChaseCam();
// void OnUnregisterDebugControls__8ChaseCam();
// void DoCameraCut__8ChaseCam();
// void __15ConversationCam();
// void _$_15ConversationCam();
// void Update__15ConversationCamUi();
// void LoadSettings__15ConversationCamPUc();
// void LockCharacterPositions__15ConversationCam();
// void SetTarget__15ConversationCamP15ISuperCamTarget();
// void AddTarget__15ConversationCamP15ISuperCamTarget();
// void GetNumTargets__C15ConversationCam();
// void OnRegisterDebugControls__15ConversationCam();
// void OnUnregisterDebugControls__15ConversationCam();
// void func_00133168();
// void func_001332A0();
// void func_00133318();
// void SetCameraByIndex__15ConversationCamUi();
// void SetCameraByName__15ConversationCamRC5tName();
// void SetCameraDistanceByName__15ConversationCamRC5tNamef();
// void SetCamBestSide__15ConversationCamRC5tName();
// void SetCameraDistanceByIndex__15ConversationCamUif();
// void SetCharacter__15ConversationCamiP9Character();
// void SetPcCameraByName__15ConversationCamRC5tName();
// void SetNpcCameraByName__15ConversationCamRC5tName();
// void SetNpcIsChild__15ConversationCamb();
// void SetPcIsChild__15ConversationCamb();
// void UsePcCam__15ConversationCam();
// void UseNpcCam__15ConversationCam();
// void OnInit__15ConversationCam();
// void OnShutdown__15ConversationCam();
// void __8DebugCam();
// void _$_8DebugCam();
// void Update__8DebugCamUi();
// void EnableShake__8DebugCam();
// void DisableShake__8DebugCam();
// void OnRegisterDebugControls__8DebugCam();
// void OnUnregisterDebugControls__8DebugCam();
// void func_00133C10();
// void __9FollowCamQ29FollowCam10FollowType();
// void _$_9FollowCam();
// void Update__9FollowCamUi();
// void UpdateForPhysics__9FollowCamUi();
// void LoadSettings__9FollowCamPUc();
// void CopyToData__9FollowCam();
// void SetTarget__9FollowCamP15ISuperCamTarget();
// void AddTarget__9FollowCamP15ISuperCamTarget();
// void EnableShake__9FollowCam();
// void DisableShake__9FollowCam();
// void ShouldReverse__C9FollowCam();
// void OnRegisterDebugControls__9FollowCam();
// void OnUnregisterDebugControls__9FollowCam();
// void DoCameraCut__9FollowCam();
// void InitUnstable__9FollowCam();
// void UpdateUnstable__9FollowCamUi();
// void InitQuickTurn__9FollowCam();
// void UpdateQuickTurn__9FollowCamUi();
// void GetTargetPosition__9FollowCamPQ218RadicalMathLibrary6Vectorb();
// void CalculateRod__9FollowCamPQ218RadicalMathLibrary6VectorUif();
// void CalculateTarget__9FollowCamPQ218RadicalMathLibrary6VectorUif();
// void GetDesiredRod__9FollowCamPQ218RadicalMathLibrary6Vector();
// void IsPushingStick__9FollowCam();
// void __7KullCam();
// void _$_7KullCam();
// void Update__7KullCamUi();
// void OnRegisterDebugControls__7KullCam();
// void OnUnregisterDebugControls__7KullCam();
// void __19RelativeAnimatedCam();
// void CheckPendingCameraSwitch__19RelativeAnimatedCam();
// void GetName__C19RelativeAnimatedCam();
// void GetType__19RelativeAnimatedCam();
// void LetterBoxStart__19RelativeAnimatedCam();
// void LetterBoxStop__19RelativeAnimatedCam();
// void SetCameraAnimationController__19RelativeAnimatedCamP26tCameraAnimationController();
// void SetOffsetMatrix__19RelativeAnimatedCamRCQ218RadicalMathLibrary6Matrix();
// void Update__19RelativeAnimatedCamUi();
// void __7RailCam();
// void _$_7RailCam();
// void OnInit__7RailCam();
// void OnShutdown__7RailCam();
// void Update__7RailCamUi();
// void InitController__7RailCam();
// void LoadSettings__7RailCamPUc();
// void OnRegisterDebugControls__7RailCam();
// void OnUnregisterDebugControls__7RailCam();
// void GetTargetSpeedModifier__7RailCam();
// void GetTargetPosition__7RailCamPQ218RadicalMathLibrary6Vectorb();
// void IntervalClamp__C7RailCamRf();
// void ProjectPointOnLine__C7RailCamRCQ218RadicalMathLibrary6VectorN21Rf();
// void IntersectLineCylinder__7RailCamiRCQ218RadicalMathLibrary6VectorfT2Rf();
// void FindCameraPosition_Distance__7RailCamRCQ218RadicalMathLibrary6Vectorf();
// void FindCameraPosition_Projection__7RailCamRCQ218RadicalMathLibrary6Vectorf();
// void FinalizeRailPosition__7RailCamQ27RailCam12SolutionType();
// void FindCameraLookAt__7RailCamRCQ218RadicalMathLibrary6VectorT1();
// void TestEval__7RailCamf();
// void DrawRail__7RailCamb();
// void DrawHull__7RailCamb();
// void DrawCylinder__7RailCamRCQ218RadicalMathLibrary6Vector();
// void __13SineCosShaker();
// void _$_13SineCosShaker();
// void SetCamera__13SineCosShakerP12tPointCamera();
// void ShakeCamera__13SineCosShakerPQ218RadicalMathLibrary6VectorT1Ui();
// void RegisterDebugInfo__13SineCosShaker();
// void UnregisterDebugInfo__13SineCosShaker();
// void SetShakeData__13SineCosShakerPC14ShakeEventData();
// void __8SuperCam();
// void _$_8SuperCam();
// void RegisterDebugControls__8SuperCam();
// void UnregisterDebugControls__8SuperCam();
// void GetPosition__C8SuperCamPQ218RadicalMathLibrary6Vector();
// void GetTarget__C8SuperCamPQ218RadicalMathLibrary6Vector();
// void GetHeading__C8SuperCamPQ218RadicalMathLibrary6Vector();
// void GetHeadingNormalized__8SuperCamPQ218RadicalMathLibrary6Vector();
// void GetCameraUp__C8SuperCamPQ218RadicalMathLibrary6Vector();
// void SetFOV__8SuperCamf();
// void GetFOV__C8SuperCam();
// void SetCameraValues__8SuperCamUiGQ218RadicalMathLibrary6VectorT2PCQ218RadicalMathLibrary6Vector();
// void OverrideFOV__8SuperCambff();
// void DisableOverride__8SuperCam();
// void SetFOVOverride__8SuperCamf();
// void SetCamera__8SuperCamP12tPointCamera();
// void ClampAngle__C8SuperCamPf();
// void AdjustAngles__C8SuperCamPfN21();
// void Shutdown__8SuperCam();
// void CorrectDist__8SuperCamRCQ218RadicalMathLibrary6VectorRQ218RadicalMathLibrary6Vector();
// void InitMyController__8SuperCami();
// void ShutDownMyController__8SuperCam();
// void GetCameraNonConst__8SuperCam();
// void SphericalMotion__C8SuperCamRCQ218RadicalMathLibrary6VectorRQ218RadicalMathLibrary6VectorT1T2f();
// void UpdateVUP__8SuperCamGQ218RadicalMathLibrary6VectorT1();
// void EaseMotion__8SuperCamfff();
// void DoCameraTransition__8SuperCambUi();
// void func_00139E38();
// void SetupShake__8SuperCam();
// void EndShake__8SuperCam();
// void SetupTransition__8SuperCamb();
// void EndTransition__8SuperCamb();
// void TransitionCamera__8SuperCamfPQ218RadicalMathLibrary6VectorT2PfUib();
// void TransitionFOV__8SuperCamfPfUi();
// void EaseIn__8SuperCamfPQ218RadicalMathLibrary6VectorT2Ui();
// void SetCameraShakerData__8SuperCamPC14ShakeEventData();
// void __15SuperCamCentral();
// void _$_15SuperCamCentral();
// void Init__15SuperCamCentralb();
// void IsInit__C15SuperCamCentral();
// void UpdateCameraCollisionSpherePosition__15SuperCamCentralRQ218RadicalMathLibrary6Vector();
// void UpdateCameraCollisionSphereRadius__15SuperCamCentralf();
// void Update__15SuperCamCentralUib();
// void PreCollisionPrep__15SuperCamCentral();
// void AddCameraCollisionOffset__15SuperCamCentralRQ218RadicalMathLibrary6Vector();
// void RegisterSuperCam__15SuperCamCentralP8SuperCam();
// void UnregisterSuperCam__15SuperCamCentralP8SuperCam();
// void UnregisterSuperCam__15SuperCamCentralUi();
// void GetActiveSuperCamIndex__C15SuperCamCentral();
// void GetSuperCam__C15SuperCamCentralQ28SuperCam4Type();
// void ToggleSuperCam__15SuperCamCentralbT1();
// void SelectSuperCam__15SuperCamCentralUiiUi();
// void SelectSuperCam__15SuperCamCentralQ28SuperCam4TypeiUi();
// void SelectSuperCam__15SuperCamCentralP8SuperCamiUi();
// void SetCamera__15SuperCamCentralP12tPointCamera();
// void SetTarget__15SuperCamCentralP15ISuperCamTarget();
// void AddTarget__15SuperCamCentralP15ISuperCamTarget();
// void SetActiveSuperCam__15SuperCamCentralUiiUi();
// void SubmitStatics__15SuperCamCentral();
// void UpdateForPhysics__15SuperCamCentralUi();
// void AllowCameraToggle__15SuperCamCentral();
// void AllowAutoCameraChange__15SuperCamCentral();
// void RegisterFOVLocator__15SuperCamCentralP10FOVLocator();
// void UnregisterFOVLocator__15SuperCamCentral();
// void NoTransition__15SuperCamCentral();
// void HandleEvent__15SuperCamCentral9EventEnumPv();
// void ToggleFirstPerson__15SuperCamCentrali();
// void IsCutCam__15SuperCamCentral();
// void LoadData__15SuperCamCentralPCUcUi();
// void SaveData__15SuperCamCentralPUcUi();
// void ResetData__15SuperCamCentral();
// void IsLegalType__15SuperCamCentralQ28SuperCam4Type();
// void GetNewFollowCamDataChunk__15SuperCamCentral();
// void func_0013CEA0();
// void FindFCD__15SuperCamCentralUi();
// void __18SuperCamController();
// void _$_18SuperCamController();
// void LoadControllerMappings__18SuperCamControllerUi();
// void OnButtonDown__18SuperCamControlleriiPC6Button();

class SuperCamManager {
public:
    static void CreateInstance();

private:
// void GetInstance__15SuperCamManager();
// void DestroyInstance__15SuperCamManager();
// void Init__15SuperCamManagerb();
// void GetSCC__15SuperCamManageri();
// void PreCollisionPrep__15SuperCamManager();
// void Update__15SuperCamManagerUib();
// void SubmitStatics__15SuperCamManager();
// void ToggleFirstPerson__15SuperCamManageri();
// void __15SuperCamManager();
// void _$_15SuperCamManager();
};

// void __10TrackerCam();
// void _$_10TrackerCam();
// void Update__10TrackerCamUi();
// void OnRegisterDebugControls__10TrackerCam();
// void OnUnregisterDebugControls__10TrackerCam();
// void __9WalkerCam();
// void _$_9WalkerCam();
// void Update__9WalkerCamUi();
// void UpdateForPhysics__9WalkerCamUi();
// void LoadSettings__9WalkerCamPUc();
// void SetTarget__9WalkerCamP15ISuperCamTarget();
// void AddTarget__9WalkerCamP15ISuperCamTarget();
// void OnDisplay__C9WalkerCam();
// void UpdatePositionNormal__9WalkerCamUif();
// void UpdatePositionInCollision__9WalkerCamUif();
// void UpdatePositionOneCollsion__9WalkerCamUifUi();
// void UpdatePositionMultipleCollision__9WalkerCamUif();
// void OnRegisterDebugControls__9WalkerCam();
// void OnUnregisterDebugControls__9WalkerCam();
// void IsPushingStick__9WalkerCam();
// void IsStickStill__9WalkerCam();
// void GetTargetPosition__C9WalkerCamPQ218RadicalMathLibrary6Vectorb();
// void IsTargetNearPed__9WalkerCamUi();
// void __12WrecklessCam();
// void _$_12WrecklessCam();
// void Update__12WrecklessCamUi();
// void SetTarget__12WrecklessCamP15ISuperCamTarget();
// void AddTarget__12WrecklessCamP15ISuperCamTarget();
// void OnInit__12WrecklessCam();
// void OnShutdown__12WrecklessCam();
// void OnRegisterDebugControls__12WrecklessCam();
// void OnUnregisterDebugControls__12WrecklessCam();
// void __22WrecklessEventListener();
// void _$_22WrecklessEventListener();
// void HandleEvent__22WrecklessEventListener9EventEnumPv();
// void __9StaticCam();
// void _$_9StaticCam();
// void Update__9StaticCamUi();
// void OnRegisterDebugControls__9StaticCam();
// void OnUnregisterDebugControls__9StaticCam();
// void GetTargetSpeedModifier__9StaticCam();
// void __10ReverseCam();
// void _$_10ReverseCam();
// void Update__10ReverseCamUi();
// void UpdateForPhysics__10ReverseCamUi();
// void EnableShake__10ReverseCam();
// void DisableShake__10ReverseCam();
// void OnRegisterDebugControls__10ReverseCam();
// void OnUnregisterDebugControls__10ReverseCam();
// void CanSwitch__10ReverseCam();
// void _$_15SurveillanceCam();
// void Update__15SurveillanceCamUi();
// void GetName__C15SurveillanceCam();
// void GetType__15SurveillanceCam();
// void SetTarget__15SurveillanceCamP15ISuperCamTarget();
// void OnRegisterDebugControls__15SurveillanceCam();
// void OnUnregisterDebugControls__15SurveillanceCam();
// void __14SuperSprintCam();
// void _$_14SuperSprintCam();
// void Update__14SuperSprintCamUi();
// void OnInit__14SuperSprintCam();
// void OnShutdown__14SuperSprintCam();
// void OnRegisterDebugControls__14SuperSprintCam();
// void OnUnregisterDebugControls__14SuperSprintCam();
// void find__H2ZP5tNameZ5tName_X01X01RCX11G26random_access_iterator_tag_X01();
// void func_00142E60();
// void func_00142E68();
// void func_001430D0();
// void __tf13ICameraShaker();
// void __tf13SineCosShaker();
// void __tf8SuperCam();
// void __tf11AnimatedCam();
// void __tf15SuperCamCentral();
// void __tf13BumperCamData();
// void __tf9BumperCam();
// void __tf15ISuperCamTarget();
// void __tf12ChaseCamData();
// void __tf8ChaseCam();
// void __tf19ConversationCamData();
// void __tf15ConversationCam();
// void __tf8DebugCam();
// void __tf13FollowCamData();
// void __tf9FollowCam();
// void __tf18SuperCamController();
// void __tf7KullCam();
// void _$_19RelativeAnimatedCam();
// void __tf19RelativeAnimatedCam();
// void __tf7RailCam();
// void __tf22WrecklessEventListener();
// void __tf12WrecklessCam();
// void __tf14TrackerCamData();
// void __tf10TrackerCam();
// void __tf13WalkerCamData();
// void __tf9WalkerCam();
// void __tf18WalkerCamDataChunk();
// void __tf9StaticCam();
// void __tf10ReverseCam();
// void __tf15SurveillanceCam();
// void __tf14SuperSprintCam();
// void func_00143AF8();
// void _$_13ICameraShaker();
// void Reset__13SineCosShaker();
// void SetSpeed__13SineCosShakerf();
// void SetTime__13SineCosShakerUi();
// void SetCameraRelative__13SineCosShakerb();
// void SetDirection__13SineCosShakerRCQ218RadicalMathLibrary6Vector();
// void SetLooping__13SineCosShakerb();
// void DoneShaking__13SineCosShaker();
// void GetName__13SineCosShaker();
// void UpdateForPhysics__8SuperCamUi();
// void LoadSettings__8SuperCamPUc();
// void SetTarget__8SuperCamP15ISuperCamTarget();
// void AddTarget__8SuperCamP15ISuperCamTarget();
// void GetNumTargets__C8SuperCam();
// void SetCollisionOffset__8SuperCamPCQ218RadicalMathLibrary6VectorUiRCQ218RadicalMathLibrary6Vector();
// void GetCollisionRadius__C8SuperCam();
// void GetIntersectionRadius__C8SuperCam();
// void OnInit__8SuperCam();
// void OnShutdown__8SuperCam();
// void GetTargetSpeedModifier__8SuperCam();
// void OnDisplay__C8SuperCam();
// void func_00143C20();
// void OnRegisterDebugControls__8SuperCam();
// void OnUnregisterDebugControls__8SuperCam();
// void func_00143C38();
// void CanSwitch__8SuperCam();
// void func_00143C50();
// void EnableShake__8SuperCam();
// void DisableShake__8SuperCam();
// void LookBack__8SuperCamb();
// void DoFirstTime__8SuperCam();
// void DoCameraCut__8SuperCam();
// void func_00143D10();
// void __15GameDataHandler();
// void func_00143D38();
// void _$_Q218radLoadHashedStore11RawIterator();
// void __Q216radLoadInventoryt8SafeCast1Z7tCamera();
// void __Q216radLoadInventoryt8SafeCast1Z16tMultiController();
// void _$_13BumperCamData();
// void GetCollisionRadius__C9BumperCam();
// void GetName__C9BumperCam();
// void GetType__9BumperCam();
// void SetTarget__9BumperCamP15ISuperCamTarget();
// void AddTarget__9BumperCamP15ISuperCamTarget();
// void GetNumTargets__C9BumperCam();
// void _$_12ChaseCamData();
// void GetName__C8ChaseCam();
// void GetType__8ChaseCam();
// void SetTarget__8ChaseCamP15ISuperCamTarget();
// void AddTarget__8ChaseCamP15ISuperCamTarget();
// void GetNumTargets__C8ChaseCam();
// void _$_19ConversationCamData();
// void GetName__C15ConversationCam();
// void GetType__15ConversationCam();
// void func_00143F08();
// void GetName__C8DebugCam();
// void GetType__8DebugCam();
// void _$_13FollowCamData();
// void GetCollisionRadius__C9FollowCam();
// void GetIntersectionRadius__C9FollowCam();
// void GetName__C9FollowCam();
// void GetNumTargets__C9FollowCam();
// void GetType__9FollowCam();
// void func_00143FA8();
// void SetCollisionOffset__9FollowCamPCQ218RadicalMathLibrary6VectorUiRCQ218RadicalMathLibrary6Vector();
// void OnInit__9FollowCam();
// void OnButton__18SuperCamControlleriiPC6Button();
// void OnButtonUp__18SuperCamControlleriiPC6Button();
// void GetName__C7KullCam();
// void GetType__7KullCam();
// void SetTarget__7KullCamP15ISuperCamTarget();
// void AddTarget__7KullCamP15ISuperCamTarget();
// void GetNumTargets__C7KullCam();
// void GetName__C7RailCam();
// void GetType__7RailCam();
// void SetTarget__7RailCamP15ISuperCamTarget();
// void AddTarget__7RailCamP15ISuperCamTarget();
// void GetNumTargets__C7RailCam();
// void func_00144088();
// void GetName__C12WrecklessCam();
// void GetType__12WrecklessCam();
// void GetNumTargets__C12WrecklessCam();
// void _$_14TrackerCamData();
// void GetName__C10TrackerCam();
// void GetType__10TrackerCam();
// void SetTarget__10TrackerCamP15ISuperCamTarget();
// void AddTarget__10TrackerCamP15ISuperCamTarget();
// void GetNumTargets__C10TrackerCam();
// void _$_13WalkerCamData();
// void GetCollisionRadius__C9WalkerCam();
// void GetIntersectionRadius__C9WalkerCam();
// void OnInit__9WalkerCam();
// void GetName__C9WalkerCam();
// void GetType__9WalkerCam();
// void GetNumTargets__C9WalkerCam();
// void SetCollisionOffset__9WalkerCamPCQ218RadicalMathLibrary6VectorUiRCQ218RadicalMathLibrary6Vector();
// void __Q216radLoadInventoryt8SafeCast1Z18WalkerCamDataChunk();
// void __10OldCamData();
// void func_00144230();
// void OnInit__9StaticCam();
// void GetName__C9StaticCam();
// void GetType__9StaticCam();
// void SetTarget__9StaticCamP15ISuperCamTarget();
// void AddTarget__9StaticCamP15ISuperCamTarget();
// void GetNumTargets__C9StaticCam();
// void LoadSettings__10ReverseCamPUc();
// void GetCollisionRadius__C10ReverseCam();
// void OnInit__10ReverseCam();
// void GetName__C10ReverseCam();
// void GetType__10ReverseCam();
// void SetTarget__10ReverseCamP15ISuperCamTarget();
// void AddTarget__10ReverseCamP15ISuperCamTarget();
// void GetNumTargets__C10ReverseCam();
// void SetCollisionOffset__10ReverseCamPCQ218RadicalMathLibrary6VectorUiRCQ218RadicalMathLibrary6Vector();
// void GetName__C14SuperSprintCam();
// void GetType__14SuperSprintCam();
// void __Q216radLoadInventoryt8SafeCast1Z13tVectorCamera();
// void func_00144370();
// void __tf15GameDataHandler();
// void __tf18FollowCamDataChunk();
// void __tfQ216radLoadInventoryt8SafeCast1Z7tCamera();
// void __tfQ216radLoadInventoryt8SafeCast1Z16tMultiController();
// void func_001444B8();
// void __tfQ216radLoadInventoryt8SafeCast1Z18WalkerCamDataChunk();
// void func_00144518();
// void __tfQ216radLoadInventoryt8SafeCast1Z13tVectorCamera();
// void func_00144578();
// void _$_18FollowCamDataChunk();
// void _$_Q2t9HashTable1Z9IRefCount11RawIterator();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z18WalkerCamDataChunkP9IRefCount();
// void func_00144648();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z13tVectorCameraP9IRefCount();
// void func_001446A0();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z16tMultiControllerP9IRefCount();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z7tCameraP9IRefCount();
// void func_00144748();
// void _GLOBAL_$I$Abort__11AnimatedCam();
// void _GLOBAL_$D$Abort__11AnimatedCam();

// rodata

// extern UNK_TYPE D_004560A8;
// extern UNK_TYPE D_004560E0;
// extern UNK_TYPE D_004560E8;
// extern UNK_TYPE D_004560F8;
// extern UNK_TYPE D_00456108;
// extern UNK_TYPE D_00456118;
// extern UNK_TYPE D_00456128;
// extern UNK_TYPE D_00456138;
// extern UNK_TYPE D_00456148;
// extern UNK_TYPE D_00456160;
// extern UNK_TYPE D_00456170;
// extern UNK_TYPE D_00456178;
// extern UNK_TYPE D_00456188;
// extern UNK_TYPE D_00456198;
// extern UNK_TYPE D_004561A8;
// extern UNK_TYPE D_004561C0;
// extern UNK_TYPE D_004561C8;
// extern UNK_TYPE D_004561D0;
// extern UNK_TYPE D_004561D8;
// extern UNK_TYPE D_004561E8;
// extern UNK_TYPE D_004561F8;
// extern UNK_TYPE D_00456208;
// extern UNK_TYPE D_00456220;
// extern UNK_TYPE D_00456230;
// extern UNK_TYPE D_00456248;
// extern UNK_TYPE _7RailCam$BehaviourNames;
// extern UNK_TYPE D_00456288;
// extern UNK_TYPE NUM_CAMERAS_FOR_DRIVING;
// extern UNK_TYPE NUM_CAMERAS_FOR_DRIVING_WITHOUT_CHEAT;
// extern UNK_TYPE NUM_CAMERAS_FOR_WALKING;
// extern UNK_TYPE NUM_CAMERAS_FOR_WALKING_WITHOUT_CHEAT;
// extern UNK_TYPE NUM_SUPERSPRINT_CAMS;
// extern UNK_TYPE D_004562B0;
// extern UNK_TYPE D_004562C8;
// extern UNK_TYPE D_004562E0;
// extern UNK_TYPE D_00456308;
// extern UNK_TYPE D_00456310;
// extern UNK_TYPE D_00456318;
// extern UNK_TYPE D_00456320;
// extern UNK_TYPE D_00456328;
// extern UNK_TYPE D_00456330;
// extern UNK_TYPE D_00456338;
// extern UNK_TYPE D_00456348;
// extern UNK_TYPE D_00456358;
// extern UNK_TYPE D_00456368;
// extern UNK_TYPE D_00456370;
// extern UNK_TYPE D_00456378;
// extern UNK_TYPE D_00456380;
// extern UNK_TYPE D_00456390;
// extern UNK_TYPE D_004563B0;
// extern UNK_TYPE D_004563C0;
// extern UNK_TYPE D_004563C8;
// extern UNK_TYPE D_004563D0;
// extern UNK_TYPE D_004563E0;
// extern UNK_TYPE D_004563F0;
// extern UNK_TYPE D_00456408;
// extern UNK_TYPE D_00456418;
// extern UNK_TYPE _vt$14SuperSprintCam;
// extern UNK_TYPE _vt$15SurveillanceCam;
// extern UNK_TYPE _vt$10ReverseCam;
// extern UNK_TYPE _vt$9StaticCam;
// extern UNK_TYPE _vt$9WalkerCam;
// extern UNK_TYPE _vt$13WalkerCamData;
// extern UNK_TYPE _vt$10TrackerCam;
// extern UNK_TYPE _vt$14TrackerCamData;
// extern UNK_TYPE _vt$12WrecklessCam;
// extern UNK_TYPE _vt$22WrecklessEventListener;
// extern UNK_TYPE _vt$7RailCam;
// extern UNK_TYPE _vt$19RelativeAnimatedCam;
// extern UNK_TYPE _vt$7KullCam;
// extern UNK_TYPE _vt$18SuperCamController;
// extern UNK_TYPE _vt$9FollowCam;
// extern UNK_TYPE _vt$13FollowCamData;
// extern UNK_TYPE _vt$8DebugCam;
// extern UNK_TYPE _vt$15ConversationCam;
// extern UNK_TYPE _vt$19ConversationCamData;
// extern UNK_TYPE _vt$8ChaseCam;
// extern UNK_TYPE _vt$12ChaseCamData;
// extern UNK_TYPE _vt$9BumperCam;
// extern UNK_TYPE _vt$13BumperCamData;
// extern UNK_TYPE _vt$15SuperCamCentral$15GameDataHandler;
// extern UNK_TYPE _vt$15SuperCamCentral;
// extern UNK_TYPE _vt$11AnimatedCam;
// extern UNK_TYPE _vt$8SuperCam;
// extern UNK_TYPE _vt$13SineCosShaker;
// extern UNK_TYPE _vt$13ICameraShaker;
// extern UNK_TYPE D_00457608;
// extern UNK_TYPE D_00457620;
// extern UNK_TYPE D_00457630;
// extern UNK_TYPE D_00457640;
// extern UNK_TYPE D_00457650;
// extern UNK_TYPE D_00457660;
// extern UNK_TYPE D_00457678;
// extern UNK_TYPE D_00457688;
// extern UNK_TYPE D_00457698;
// extern UNK_TYPE D_004576A8;
// extern UNK_TYPE D_004576C0;
// extern UNK_TYPE D_004576D0;
// extern UNK_TYPE D_004576E0;
// extern UNK_TYPE D_004576F8;
// extern UNK_TYPE D_00457710;
// extern UNK_TYPE D_00457720;
// extern UNK_TYPE D_00457730;
// extern UNK_TYPE D_00457740;
// extern UNK_TYPE D_00457758;
// extern UNK_TYPE D_00457768;
// extern UNK_TYPE D_00457780;
// extern UNK_TYPE D_00457790;
// extern UNK_TYPE D_004577B0;
// extern UNK_TYPE D_004577C0;
// extern UNK_TYPE D_004577D8;
// extern UNK_TYPE D_004577E8;
// extern UNK_TYPE D_004577F8;
// extern UNK_TYPE D_00457808;
// extern UNK_TYPE D_00457820;
// extern UNK_TYPE D_00457830;
// extern UNK_TYPE D_00457840;
// extern UNK_TYPE D_00457858;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z13tVectorCamera;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z18WalkerCamDataChunk;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z16tMultiController;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z7tCamera;
// extern UNK_TYPE _vt$18FollowCamDataChunk;
// extern UNK_TYPE _vt$15GameDataHandler;
// extern UNK_TYPE D_00457978;
// extern UNK_TYPE D_00457990;
// extern UNK_TYPE D_004579A8;
// extern UNK_TYPE D_004579D8;
// extern UNK_TYPE D_00457A40;
// extern UNK_TYPE D_00457AA8;

// data

// extern UNK_TYPE D_00424B60;
// extern UNK_TYPE D_00424B7C;
// extern UNK_TYPE D_00424B80;
// extern UNK_TYPE D_00424B84;
// extern UNK_TYPE D_00424B85;
// extern UNK_TYPE D_00424B88;
// extern UNK_TYPE D_00424B8C;
// extern UNK_TYPE D_00424B90;
// extern UNK_TYPE D_00424B91;
// extern UNK_TYPE D_00424B94;
// extern UNK_TYPE _15ConversationCam$sInstCount;
// extern UNK_TYPE D_00424BA0;
// extern UNK_TYPE D_00424BA4;
// extern UNK_TYPE D_00424BA8;
// extern UNK_TYPE D_00424BAC;
// extern UNK_TYPE D_00424BB0;
// extern UNK_TYPE D_00424BB4;
// extern UNK_TYPE D_00424BB8;
// extern UNK_TYPE D_00424BC8;
// extern UNK_TYPE D_00424BE8;
// extern UNK_TYPE D_00424C08;
// extern UNK_TYPE D_00424C28;
// extern UNK_TYPE D_00424C48;
// extern UNK_TYPE D_00424C50;
// extern UNK_TYPE D_00424C70;
// extern UNK_TYPE D_00424C90;
// extern UNK_TYPE D_00424C94;
// extern UNK_TYPE D_00424C98;
// extern UNK_TYPE _8SuperCam$s_secondaryControllerID;
// extern UNK_TYPE D_00424CA4;
// extern UNK_TYPE CAMERAS_FOR_DRIVING;
// extern UNK_TYPE D_00424CCC;
// extern UNK_TYPE CAMERAS_FOR_WALKING;
// extern UNK_TYPE D_00424CDC;
// extern UNK_TYPE SUPER_SPRINT_CAMERAS;
// extern UNK_TYPE _15SuperCamCentral$mTotalSuperCamCentrals;
// extern UNK_TYPE D_00424CF5;
// extern UNK_TYPE _15SuperCamCentral$CAMERA_INVENTORY_SECTION;
// extern UNK_TYPE D_00424CFC;
// extern UNK_TYPE _15SuperCamCentral$mFollowCamDataChunks;
// extern UNK_TYPE _15SuperCamCentral$mNumUsedFDC;
// extern UNK_TYPE _15SuperCamManager$mspInstance;
// extern UNK_TYPE _14SuperSprintCam$mSprintCamCount;
// extern UNK_TYPE D_0042692C;
// extern UNK_TYPE D_00426930;
// extern UNK_TYPE D_00426990;
// extern UNK_TYPE D_00426998;

// bss

// extern UNK_TYPE D_004B1598;
// extern UNK_TYPE D_004B15A8;
// extern UNK_TYPE D_004B15B0;
// extern UNK_TYPE D_004B15B8;
// extern UNK_TYPE D_004B15C0;
// extern UNK_TYPE D_004B15C8;
// extern UNK_TYPE D_004B15D0;
// extern UNK_TYPE D_004B15D8;
// extern UNK_TYPE D_004B15E0;
// extern UNK_TYPE D_004B15E8;
// extern UNK_TYPE D_004B15F8;
// extern UNK_TYPE D_004B1608;
// extern UNK_TYPE D_004B1668;
// extern UNK_TYPE D_004B16C8;
// extern UNK_TYPE D_004B16D0;
// extern UNK_TYPE D_004B16DC;
// extern UNK_TYPE D_004B16E0;
// extern UNK_TYPE D_004B16E1;

#endif
