#ifndef ALLCONDITIONS_H
#define ALLCONDITIONS_H

// text

// void __15DamageCondition();
// void _$_15DamageCondition();
// void OnInitialize__15DamageCondition();
// void OnFinalize__15DamageCondition();
// void HandleEvent__15DamageCondition9EventEnumPv();
// void IsClose__15DamageCondition();
// void __15FollowCondition();
// void _$_15FollowCondition();
// void Update__15FollowConditionUi();
// void IsChaseCondition__15FollowCondition();
// void IsClose__15FollowCondition();
// void OnInitialize__15FollowCondition();
// void OnFinalize__15FollowCondition();
// void CalculateDistanceToTarget__15FollowCondition();
// void __22LeaveInteriorCondition();
// void _$_22LeaveInteriorCondition();
// void HandleEvent__22LeaveInteriorCondition9EventEnumPv();
// void IsClose__22LeaveInteriorCondition();
// void OnInitialize__22LeaveInteriorCondition();
// void OnFinalize__22LeaveInteriorCondition();
// void __16MissionCondition();
// void _$_16MissionCondition();
// void Initialize__16MissionCondition();
// void Finalize__16MissionCondition();
// void HandleEvent__16MissionCondition9EventEnumPv();
// void IsChaseCondition__16MissionCondition();
// void IsClose__16MissionCondition();
// void __20OutOfBoundsCondition();
// void _$_20OutOfBoundsCondition();
// void OnInitialize__20OutOfBoundsCondition();
// void OnFinalize__20OutOfBoundsCondition();
// void HandleEvent__20OutOfBoundsCondition9EventEnumPv();
// void IsClose__20OutOfBoundsCondition();
// void __13RaceCondition();
// void _$_13RaceCondition();
// void OnInitialize__13RaceCondition();
// void OnFinalize__13RaceCondition();
// void HandleEvent__13RaceCondition9EventEnumPv();
// void IsChaseCondition__13RaceCondition();
// void IsClose__13RaceCondition();
// void __16TimeOutCondition();
// void _$_16TimeOutCondition();
// void Update__16TimeOutConditionUi();
// void IsClose__16TimeOutCondition();
// void SetViolated__16TimeOutConditionb();
// void __16VehicleCondition();
// void _$_16VehicleCondition();
// void __17PositionCondition();
// void _$_17PositionCondition();
// void HandleEvent__17PositionCondition9EventEnumPv();
// void OnInitialize__17PositionCondition();
// void OnFinalize__17PositionCondition();
// void __24VehicleCarryingStateProp();
// void _$_24VehicleCarryingStateProp();
// void Update__24VehicleCarryingStatePropUi();
// void HandleEvent__24VehicleCarryingStateProp9EventEnumPv();
// void OnInitialize__24VehicleCarryingStateProp();
// void OnFinalize__24VehicleCarryingStateProp();
// void __20GetOutOfCarCondition();
// void _$_20GetOutOfCarCondition();
// void Update__20GetOutOfCarConditionUi();
// void HandleEvent__20GetOutOfCarCondition9EventEnumPv();
// void GetTimeRemainingTilFailuremilliseconds__20GetOutOfCarCondition();
// void IsClose__20GetOutOfCarCondition();
// void OnInitialize__20GetOutOfCarCondition();
// void OnFinalize__20GetOutOfCarCondition();
// void __20NotAbductedCondition();
// void _$_20NotAbductedCondition();
// void HandleEvent__20NotAbductedCondition9EventEnumPv();
// void OnInitialize__20NotAbductedCondition();
// void OnFinalize__20NotAbductedCondition();
// void __19KeepBarrelCondition();
// void _$_19KeepBarrelCondition();
// void HandleEvent__19KeepBarrelCondition9EventEnumPv();
// void OnInitialize__19KeepBarrelCondition();
// void OnFinalize__19KeepBarrelCondition();
// void __tf16MissionCondition();
// void __tf16VehicleCondition();
// void __tf15DamageCondition();
// void __tf15FollowCondition();
// void __tf22LeaveInteriorCondition();
// void __tf20OutOfBoundsCondition();
// void __tf13RaceCondition();
// void __tf16TimeOutCondition();
// void __tf17PositionCondition();
// void __tf24VehicleCarryingStateProp();
// void __tf20GetOutOfCarCondition();
// void __tf20NotAbductedCondition();
// void __tf19KeepBarrelCondition();
// void Update__16MissionConditionUi();
// void OnInitialize__16MissionCondition();
// void OnFinalize__16MissionCondition();
// void OnInitialize__16VehicleCondition();
// void OnFinalize__16VehicleCondition();
// void func_0018CF88();

// rodata

// extern UNK_TYPE D_00461950;
// extern UNK_TYPE D_00461990;
// extern UNK_TYPE D_004619A0;
// extern UNK_TYPE D_004619B0;
// extern UNK_TYPE D_004619C0;
// extern UNK_TYPE D_004619D0;
// extern UNK_TYPE D_004619E0;
// extern UNK_TYPE D_004619F0;
// extern UNK_TYPE _vt$19KeepBarrelCondition;
// extern UNK_TYPE _vt$20NotAbductedCondition;
// extern UNK_TYPE _vt$20GetOutOfCarCondition;
// extern UNK_TYPE _vt$24VehicleCarryingStateProp;
// extern UNK_TYPE _vt$17PositionCondition;
// extern UNK_TYPE _vt$16TimeOutCondition;
// extern UNK_TYPE _vt$13RaceCondition;
// extern UNK_TYPE _vt$20OutOfBoundsCondition;
// extern UNK_TYPE _vt$22LeaveInteriorCondition;
// extern UNK_TYPE _vt$15FollowCondition;
// extern UNK_TYPE _vt$15DamageCondition;
// extern UNK_TYPE _vt$16VehicleCondition;
// extern UNK_TYPE _vt$16MissionCondition;
// extern UNK_TYPE D_00461DC8;
// extern UNK_TYPE D_00461DE0;
// extern UNK_TYPE D_00461DF8;
// extern UNK_TYPE D_00461E10;
// extern UNK_TYPE D_00461E28;
// extern UNK_TYPE D_00461E48;
// extern UNK_TYPE D_00461E60;
// extern UNK_TYPE D_00461E70;
// extern UNK_TYPE D_00461E88;
// extern UNK_TYPE D_00461EA0;
// extern UNK_TYPE D_00461EC0;
// extern UNK_TYPE D_00461ED8;
// extern UNK_TYPE D_00461EF0;

// data

// extern UNK_TYPE _16MissionCondition$mFailedHitNRun;
// extern UNK_TYPE D_0042C4F5;

#endif
