#ifndef ALLDSG_HPP
#define ALLDSG_HPP

// text

// void __22AnimCollisionEntityDSG();
// void _$_22AnimCollisionEntityDSG();
// void LoadSetUp__22AnimCollisionEntityDSGP18tCompositeDrawableP16tMultiControllerPQ23sim15CollisionObjectP12tEntityStore();
// void SetAction__22AnimCollisionEntityDSGPQ212ActionButton10AnimSwitch();
// void GetBoundingBox__22AnimCollisionEntityDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__22AnimCollisionEntityDSGPQ218RadicalMathLibrary6Sphere();
// void Display__22AnimCollisionEntityDSG();
// void pPosition__22AnimCollisionEntityDSG();
// void rPosition__22AnimCollisionEntityDSG();
// void GetPosition__22AnimCollisionEntityDSGPQ218RadicalMathLibrary6Vector();
// void AdvanceAnimation__22AnimCollisionEntityDSGf();
// void Update__22AnimCollisionEntityDSGf();
// void UpdatePose__22AnimCollisionEntityDSGf();
// void UpdateBBox__22AnimCollisionEntityDSGPQ23sim15CollisionVolume();
// void UpdateVisibility__22AnimCollisionEntityDSG();
// void PreReactToCollision__22AnimCollisionEntityDSGPQ23sim8SimStateRQ23sim9Collision();
// void PostReactToCollision__22AnimCollisionEntityDSGRQ218RadicalMathLibrary6VectorRQ23sim9Collision();
// void GetPoseJoint__22AnimCollisionEntityDSGib();
// void OnSetSimState__22AnimCollisionEntityDSGPQ23sim8SimState();
// void findSoundName__22AnimCollisionEntityDSG();
// void __13AnimEntityDSG();
// void _$_13AnimEntityDSG();
// void Display__13AnimEntityDSG();
// void Reset__13AnimEntityDSG();
// void pPosition__13AnimEntityDSG();
// void rPosition__13AnimEntityDSG();
// void GetPosition__13AnimEntityDSGPQ218RadicalMathLibrary6Vector();
// void SetAnimRootHeadingYUp__13AnimEntityDSGRQ218RadicalMathLibrary6Vector();
// void SetPosition__13AnimEntityDSGRQ218RadicalMathLibrary6Vector();
// void Update__13AnimEntityDSGf();
// void LoadSetUp__13AnimEntityDSGP18tCompositeDrawableP16tMultiControllerP12tEntityStoreRQ218RadicalMathLibrary6Vector();
// void GetBoundingBox__13AnimEntityDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__13AnimEntityDSGPQ218RadicalMathLibrary6Sphere();
// void PlaceOnGround__13AnimEntityDSGfb();
// void FindEffectElements__13AnimEntityDSGP18tCompositeDrawable();
// void GetParticleSystemBoundingBox__13AnimEntityDSGP18tCompositeDrawablePQ218RadicalMathLibrary5Box3D();
// void __18CollisionEntityDSG();
// void _$_18CollisionEntityDSG();
// void SetSimState__18CollisionEntityDSGPQ23sim8SimState();
// void SetCollisionAttributes__18CollisionEntityDSGP19CollisionAttributes();
// void SetRenderLayer__18CollisionEntityDSGQ211RenderEnums9LayerEnum();
// void PostReactToCollision__18CollisionEntityDSGRQ218RadicalMathLibrary6VectorRQ23sim9Collision();
// void GetCollisionAttributes__C18CollisionEntityDSG();
// void func_001F5E18();
// void __19CollisionAttributesPcN21fffUif();
// void _$_19CollisionAttributes();
// void GetBreakable__19CollisionAttributes();
// void GetParticle__19CollisionAttributes();
// void GetSound__19CollisionAttributes();
// void GetMass__19CollisionAttributes();
// void GetClasstypeid__19CollisionAttributes();
// void func_001F6298();
// void SetSound__19CollisionAttributesPc();
// void SetClasstypeid__19CollisionAttributesUi();
// void CreateInstance__10DSGFactory();
// void GetInstance__10DSGFactory();
// void DestroyInstance__10DSGFactory();
// void CreateIntersectDSG__10DSGFactoryP9tGeometry();
// void __10DSGFactory();
// void _$_10DSGFactory();
// void __11DynaPhysDSG();
// void _$_11DynaPhysDSG();
// void Update__11DynaPhysDSGf();
// void FetchGroundPlane__11DynaPhysDSG();
// void FreeGroundPlane__11DynaPhysDSG();
// void IsAtRest__11DynaPhysDSG();
// void RestTest__11DynaPhysDSG();
// void AddToSimulation__11DynaPhysDSG();
// void ApplyForce__11DynaPhysDSGRCQ218RadicalMathLibrary6Vectorf();
// void IsCollisionEnabled__C11DynaPhysDSG();
// void __14FenceEntityDSG();
// void _$_14FenceEntityDSG();
// void Display__14FenceEntityDSG();
// void GetBoundingBox__14FenceEntityDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__14FenceEntityDSGPQ218RadicalMathLibrary6Sphere();
// void pPosition__14FenceEntityDSG();
// void rPosition__14FenceEntityDSG();
// void GetPosition__14FenceEntityDSGPQ218RadicalMathLibrary6Vector();
// void PreReactToCollision__14FenceEntityDSGPQ23sim8SimStateRQ23sim9Collision();
// void PostReactToCollision__14FenceEntityDSGRQ218RadicalMathLibrary6VectorRQ23sim9Collision();
// void __10IEntityDSG();
// void Process__10IEntityDSGP7tShader();
// void _$_10IEntityDSG();
// void RenderUpdate__10IEntityDSG();
// void SetRank__10IEntityDSGRQ218RadicalMathLibrary6VectorT1();
// void __15InstDynaPhysDSG();
// void _$_15InstDynaPhysDSG();
// void Display__15InstDynaPhysDSG();
// void GetBoundingBox__15InstDynaPhysDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__15InstDynaPhysDSGPQ218RadicalMathLibrary6Sphere();
// void Update__15InstDynaPhysDSGf();
// void PreReactToCollision__15InstDynaPhysDSGPQ23sim8SimStateRQ23sim9Collision();
// void AddToSimulation__15InstDynaPhysDSG();
// void PostReactToCollision__15InstDynaPhysDSGRQ218RadicalMathLibrary6VectorRQ23sim9Collision();
// void Break__15InstDynaPhysDSG();
// void OnSetSimState__15InstDynaPhysDSGPQ23sim8SimState();
// void LoadSetUp__15InstDynaPhysDSGPQ23sim8SimStateP19CollisionAttributesRCQ218RadicalMathLibrary6MatrixP9tDrawableT4();
// void Clone__15InstDynaPhysDSGPCcRCQ218RadicalMathLibrary6Matrix();
// void SetRank__15InstDynaPhysDSGRQ218RadicalMathLibrary6VectorT1();
// void __17InstStatEntityDSG();
// void _$_17InstStatEntityDSG();
// void Display__17InstStatEntityDSG();
// void DisplaySimpleShadow__17InstStatEntityDSG();
// void RecomputeShadowPosition__17InstStatEntityDSG();
// void GetBoundingBox__17InstStatEntityDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__17InstStatEntityDSGPQ218RadicalMathLibrary6Sphere();
// void pMatrix__17InstStatEntityDSG();
// void LoadSetUp__17InstStatEntityDSGPQ218RadicalMathLibrary6MatrixP9tGeometryP9tDrawable();
// void LoadSetUp__17InstStatEntityDSGPQ218RadicalMathLibrary6MatrixP9tDrawableT2();
// void pPosition__17InstStatEntityDSG();
// void rPosition__17InstStatEntityDSG();
// void GetPosition__17InstStatEntityDSGPQ218RadicalMathLibrary6Vector();
// void CreateShadowMatrix__17InstStatEntityDSGRCQ218RadicalMathLibrary6Vector();
// void ComputeShadowMatrix__17InstStatEntityDSGRCQ218RadicalMathLibrary6VectorPQ218RadicalMathLibrary6Matrix();
// void __15InstStatPhysDSG();
// void _$_15InstStatPhysDSG();
// void Display__15InstStatPhysDSG();
// void GetBoundingBox__15InstStatPhysDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__15InstStatPhysDSGPQ218RadicalMathLibrary6Sphere();
// void OnSetSimState__15InstStatPhysDSGPQ23sim8SimState();
// void SetInternalState__15InstStatPhysDSG();
// void LoadSetUp__15InstStatPhysDSGPQ23sim8SimStateP19CollisionAttributesRCQ218RadicalMathLibrary6MatrixP9tGeometry();
// void Clone__C15InstStatPhysDSGPCcRCQ218RadicalMathLibrary6Matrix();
// void __12IntersectDSGP9tGeometry();
// void __12IntersectDSG();
// void _$_12IntersectDSG();
// void Display__12IntersectDSG();
// void rPosition__12IntersectDSG();
// void pPosition__12IntersectDSG();
// void GetPosition__12IntersectDSGPQ218RadicalMathLibrary6Vector();
// void IntoTheVoid_WithGoFastaStripes__12IntersectDSG();
// void OutOfTheVoid_WithGoFastaStripes__12IntersectDSG();
// void mTri__12IntersectDSGiPQ218RadicalMathLibrary6VectorRQ218RadicalMathLibrary6Vector();
// void nTris__12IntersectDSG();
// void GetBoundingBox__12IntersectDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__12IntersectDSGPQ218RadicalMathLibrary6Sphere();
// void SetBoundingBox__12IntersectDSGffffff();
// void SetBoundingSphere__12IntersectDSGffff();
// void GetNumPrimGroup__12IntersectDSG();
// void GenIDSG__12IntersectDSGP9tGeometry();
// void PreParseTris__12IntersectDSGP18tPrimGroupStreamed();
// void PreParseTriStrips__12IntersectDSGP18tPrimGroupStreamed();
// void DoAllAllocs__12IntersectDSG();
// void ParseTris__12IntersectDSGP18tPrimGroupStreamed();
// void ParseTriStrips__12IntersectDSGP18tPrimGroupStreamed();
// void CalcAllFields__12IntersectDSG();
// void __15StaticEntityDSG();
// void _$_15StaticEntityDSG();
// void SetRank__15StaticEntityDSGRQ218RadicalMathLibrary6VectorT1();
// void SetGeometry__15StaticEntityDSGP9tGeometry();
// void SetDrawable__15StaticEntityDSGP9tDrawable();
// void Display__15StaticEntityDSG();
// void GetBoundingBox__15StaticEntityDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__15StaticEntityDSGPQ218RadicalMathLibrary6Sphere();
// void pPosition__15StaticEntityDSG();
// void rPosition__15StaticEntityDSG();
// void GetPosition__15StaticEntityDSGPQ218RadicalMathLibrary6Vector();
// void RenderUpdate__15StaticEntityDSG();
// void SetInternalState__15StaticEntityDSG();
// void __13StaticPhysDSG();
// void _$_13StaticPhysDSG();
// void OnSetSimState__13StaticPhysDSGPQ23sim8SimState();
// void GetSimState__C13StaticPhysDSG();
// void Display__13StaticPhysDSG();
// void GetBoundingBox__13StaticPhysDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__13StaticPhysDSGPQ218RadicalMathLibrary6Sphere();
// void pPosition__13StaticPhysDSG();
// void rPosition__13StaticPhysDSG();
// void GetPosition__13StaticPhysDSGPQ218RadicalMathLibrary6Vector();
// void RenderUpdate__13StaticPhysDSG();
// void SetInternalState__13StaticPhysDSG();
// void PreReactToCollision__13StaticPhysDSGPQ23sim8SimStateRQ23sim9Collision();
// void PostReactToCollision__13StaticPhysDSGRQ218RadicalMathLibrary6VectorRQ23sim9Collision();
// void SetShadow__13StaticPhysDSGP9tDrawable();
// void CreateShadowMatrix__13StaticPhysDSGRCQ218RadicalMathLibrary6Vector();
// void RecomputeShadowPosition__13StaticPhysDSGf();
// void RecomputeShadowPositionNoIntersect__13StaticPhysDSGfRCQ218RadicalMathLibrary6Vectorff();
// void DisplaySimpleShadow__13StaticPhysDSG();
// void ComputeShadowMatrix__13StaticPhysDSGRCQ218RadicalMathLibrary6VectorPQ218RadicalMathLibrary6Matrix();
// void __14WorldSphereDSG();
// void _$_14WorldSphereDSG();
// void Activate__14WorldSphereDSG();
// void Deactivate__14WorldSphereDSG();
// void SetNumMeshes__14WorldSphereDSGi();
// void SetNumBillBoardQuadGroups__14WorldSphereDSGi();
// void SetFlare__14WorldSphereDSGP12LensFlareDSG();
// void AddMesh__14WorldSphereDSGP9tGeometry();
// void AddBillBoardQuadGroup__14WorldSphereDSGP19tBillboardQuadGroup();
// void SetCompositeDrawable__14WorldSphereDSGP18tCompositeDrawable();
// void SetMultiController__14WorldSphereDSGP16tMultiController();
// void Display__14WorldSphereDSG();
// void GetBoundingBox__14WorldSphereDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__14WorldSphereDSGPQ218RadicalMathLibrary6Sphere();
// void pPosition__14WorldSphereDSG();
// void rPosition__14WorldSphereDSG();
// void GetPosition__14WorldSphereDSGPQ218RadicalMathLibrary6Vector();
// void RenderUpdate__14WorldSphereDSG();
// void SetInternalState__14WorldSphereDSG();
// void __18BreakableObjectDSG();
// void _$_18BreakableObjectDSG();
// void Init__18BreakableObjectDSGP22tAnimatedObjectFactoryP30tAnimatedObjectFrameController();
// void Display__18BreakableObjectDSG();
// void GetBoundingBox__18BreakableObjectDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__18BreakableObjectDSGPQ218RadicalMathLibrary6Sphere();
// void Update__18BreakableObjectDSGf();
// void pPosition__18BreakableObjectDSG();
// void rPosition__18BreakableObjectDSG();
// void GetPosition__18BreakableObjectDSGPQ218RadicalMathLibrary6Vector();
// void SetTransform__18BreakableObjectDSGRCQ218RadicalMathLibrary6Matrix();
// void Reset__18BreakableObjectDSG();
// void LastFrameReached__18BreakableObjectDSG();
// void ClearAllFlares__12LensFlareDSG();
// void DisplayAllFlares__12LensFlareDSG();
// void PostDisplayFlare__12LensFlareDSGP12LensFlareDSG();
// void ReadFrameBufferIntensities__12LensFlareDSG();
// void __12LensFlareDSG();
// void _$_12LensFlareDSG();
// void func_001FBAD0();
// void SetNumBillBoardQuadGroups__12LensFlareDSGi();
// void AddBillBoardQuadGroup__12LensFlareDSGP19tBillboardQuadGroup();
// void SetCompositeDrawable__12LensFlareDSGP18tCompositeDrawable();
// void Display__12LensFlareDSG();
// void DisplayImmediate__12LensFlareDSG();
// void GetBoundingBox__12LensFlareDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__12LensFlareDSGPQ218RadicalMathLibrary6Sphere();
// void pPosition__12LensFlareDSG();
// void rPosition__12LensFlareDSG();
// void GetPosition__12LensFlareDSGPQ218RadicalMathLibrary6Vector();
// void RenderUpdate__12LensFlareDSG();
// void DrawVisibilityChecker__12LensFlareDSG();
// void SetBillBoardIntensity__12LensFlareDSGf();
// void __19InstAnimDynaPhysDSG();
// void _$_19InstAnimDynaPhysDSG();
// void Display__19InstAnimDynaPhysDSG();
// void DisplayBoundingBox__19InstAnimDynaPhysDSGG10pddiColour();
// void LoadSetUp__19InstAnimDynaPhysDSGP19CollisionAttributesRCQ218RadicalMathLibrary6MatrixP18tCompositeDrawableP16tMultiControllerP12tEntityStore();
// void Break__19InstAnimDynaPhysDSG();
// void Update__19InstAnimDynaPhysDSGf();
// void SetTransform__19InstAnimDynaPhysDSGRCQ218RadicalMathLibrary6Matrix();
// void __19AnimDynaPhysWrapper();
// void _$_19AnimDynaPhysWrapper();
// void GetVolume__C19AnimDynaPhysWrapper();
// void GetDrawable__C19AnimDynaPhysWrapper();
// void GetController__C19AnimDynaPhysWrapper();
// void GetStatePropData__C19AnimDynaPhysWrapper();
// void HasAlpha__C19AnimDynaPhysWrapper();
// void func_001FCAE0();
// void __12StatePropDSG();
// void _$_12StatePropDSG();
// void LoadSetup__12StatePropDSGP14CStatePropDataiRCQ218RadicalMathLibrary6MatrixP19CollisionAttributesbP12tEntityStoreT5PQ23sim15CollisionObjectPQ23sim13PhysicsObject();
// void Clone__C12StatePropDSGPCcRCQ218RadicalMathLibrary6Matrix();
// void OnSetSimState__12StatePropDSGPQ23sim8SimState();
// void Display__12StatePropDSG();
// void AdvanceAnimation__12StatePropDSGf();
// void Update__12StatePropDSGf();
// void GetBoundingBox__12StatePropDSGPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__12StatePropDSGPQ218RadicalMathLibrary6Sphere();
// void pPosition__12StatePropDSG();
// void rPosition__12StatePropDSG();
// void GetPosition__12StatePropDSGPQ218RadicalMathLibrary6Vector();
// void SetPosition__12StatePropDSGRCQ218RadicalMathLibrary6Vector();
// void GetTransform__12StatePropDSGPQ218RadicalMathLibrary6Matrix();
// void SetTransform__12StatePropDSGRCQ218RadicalMathLibrary6Matrix();
// void PreReactToCollision__12StatePropDSGPQ23sim8SimStateRQ23sim9Collision();
// void PostReactToCollision__12StatePropDSGRQ218RadicalMathLibrary6VectorRQ23sim9Collision();
// void GenerateCoins__12StatePropDSGi();
// void RecieveEvent__12StatePropDSGiP10CStateProp();
// void AddToSimulation__12StatePropDSG();
// void ApplyForce__12StatePropDSGRCQ218RadicalMathLibrary6Vectorf();
// void CastsShadow__12StatePropDSG();
// void DisplaySimpleShadow__12StatePropDSG();
// void SetRank__12StatePropDSGRQ218RadicalMathLibrary6VectorT1();
// void SetShadowElement__12StatePropDSGG13tUidUnaligned();
// void EnableCollisionVolume__12StatePropDSGb();
// void RemoveSubCollisionVolume__12StatePropDSGi();
// void GetAIRef__12StatePropDSG();
// void SetState__12StatePropDSGi();
// void HandleEvent__12StatePropDSGQ212StatePropDSG5Event();
// void GetState__C12StatePropDSG();
// void AddStatePropListener__12StatePropDSGP18CStatePropListener();
// void RemoveStatePropListener__12StatePropDSGP18CStatePropListener();
// void SetSimJoint__12StatePropDSGi();
// void GetType__C12StatePropDSG();
// void RemoveAllSharedtPoses__12StatePropDSG();
// void AnimateCollisionVolume__12StatePropDSG();
// void GetSharedtPose__12StatePropDSGG13tUidUnaligned();
// void AddNewSharedtPose__12StatePropDSGG13tUidUnalignedP5tPose();
// void func_001FF198();
// void __t3Map2Z13tUidUnalignedZP5tPose();
// void __t10MapElement2Z13tUidUnalignedZP5tPoseRCt10MapElement2Z13tUidUnalignedZP5tPose();
// void __uninitialized_copy_aux__H2ZPt10MapElement2Z13tUidUnalignedZP5tPoseZPt10MapElement2Z13tUidUnalignedZP5tPose_X01X01X11G12__false_type_X11();
// void reserve__t3Map2Z13tUidUnalignedZP5tPoseUi();
// void begin__t3Map2Z13tUidUnalignedZP5tPose();
// void end__t3Map2Z13tUidUnalignedZP5tPose();
// void __as__t10MapElement2Z13tUidUnalignedZP5tPoseRCt10MapElement2Z13tUidUnalignedZP5tPose();
// void __push_heap__H3ZPt10MapElement2Z13tUidUnalignedZP5tPoseZiZt10MapElement2Z13tUidUnalignedZP5tPose_X01X11X11X21_v();
// void __adjust_heap__H3ZPt10MapElement2Z13tUidUnalignedZP5tPoseZiZt10MapElement2Z13tUidUnalignedZP5tPose_X01X11X11X21_v();
// void __make_heap__H3ZPt10MapElement2Z13tUidUnalignedZP5tPoseZt10MapElement2Z13tUidUnalignedZP5tPoseZi_X01X01PX11PX21_v();
// void sort_heap__H1ZPt10MapElement2Z13tUidUnalignedZP5tPose_X01X01_v();
// void __partial_sort__H2ZPt10MapElement2Z13tUidUnalignedZP5tPoseZt10MapElement2Z13tUidUnalignedZP5tPose_X01X01X01PX11_v();
// void __unguarded_partition__H2ZPt10MapElement2Z13tUidUnalignedZP5tPoseZt10MapElement2Z13tUidUnalignedZP5tPose_X01X01X11_X01();
// void __introsort_loop__H3ZPt10MapElement2Z13tUidUnalignedZP5tPoseZt10MapElement2Z13tUidUnalignedZP5tPoseZi_X01X01PX11X21_v();
// void __unguarded_linear_insert__H2ZPt10MapElement2Z13tUidUnalignedZP5tPoseZt10MapElement2Z13tUidUnalignedZP5tPose_X01X11_v();
// void __insertion_sort__H1ZPt10MapElement2Z13tUidUnalignedZP5tPose_X01X01_v();
// void __unguarded_insertion_sort_aux__H2ZPt10MapElement2Z13tUidUnalignedZP5tPoseZt10MapElement2Z13tUidUnalignedZP5tPose_X01X01PX11_v();
// void __final_insertion_sort__H1ZPt10MapElement2Z13tUidUnalignedZP5tPose_X01X01_v();
// void RefreshIfDirty__Ct3Map2Z13tUidUnalignedZP5tPose();
// void __t10MapElement2Z13tUidUnalignedZP5tPose();
// void __lower_bound__H3ZPt10MapElement2Z13tUidUnalignedZP5tPoseZt10MapElement2Z13tUidUnalignedZP5tPoseZi_X01X01RCX11PX21_X01();
// void find__t3Map2Z13tUidUnalignedZP5tPoseRC13tUidUnaligned();
// void _M_insert_aux__t6vector2Zt10MapElement2Z13tUidUnalignedZP5tPoseZt7s2alloc1Zt10MapElement2Z13tUidUnalignedZP5tPosePt10MapElement2Z13tUidUnalignedZP5tPoseRCt10MapElement2Z13tUidUnalignedZP5tPose();
// void insert__t3Map2Z13tUidUnalignedZP5tPoseRC13tUidUnalignedRCP5tPose();
// void func_00200138();
// void __tf10IEntityDSG();
// void __tf19CollisionAttributes();
// void __tf18CollisionEntityDSG();
// void __tf22AnimCollisionEntityDSG();
// void func_00200648();
// void __tf13StaticPhysDSG();
// void __tf11DynaPhysDSG();
// void __tf15InstDynaPhysDSG();
// void __tf15StaticEntityDSG();
// void __tf17InstStatEntityDSG();
// void __tf13AnimEntityDSG();
// void __tf12IntersectDSG();
// void __tf14FenceEntityDSG();
// void __tf18BreakableObjectDSG();
// void __tf15InstStatPhysDSG();
// void __tf12LensFlareDSG();
// void __tf14WorldSphereDSG();
// void __tf19InstAnimDynaPhysDSG();
// void __tf19AnimDynaPhysWrapper();
// void __tf12StatePropDSG();
// void func_00200B80();
// void __Q29tDrawable14ShaderCallback();
// void func_00200BA0();
// void SetShadow__10IEntityDSGP11tShadowSkin();
// void SetShadow__10IEntityDSGP11tShadowMesh();
// void CastsShadow__10IEntityDSG();
// void DisplayShadow__10IEntityDSG();
// void DisplaySimpleShadow__10IEntityDSG();
// void SetShader__10IEntityDSGP7tShaderi();
// void func_00200BD8();
// void GetPosition__10IEntityDSGPQ218RadicalMathLibrary6Vector();
// void OnSetSimState__18CollisionEntityDSGPQ23sim8SimState();
// void GetAIRef__22AnimCollisionEntityDSG();
// void mpSimState__C13StaticPhysDSG();
// void CastsShadow__13StaticPhysDSG();
// void GetAIRef__13StaticPhysDSG();
// void OnTransitToAICtrl__11DynaPhysDSG();
// void GetGroundPlaneIndex__11DynaPhysDSG();
// void GetAIRef__15InstDynaPhysDSG();
// void SetShader__15StaticEntityDSGP7tShaderi();
// void SetShader__17InstStatEntityDSGP7tShaderi();
// void CastsShadow__17InstStatEntityDSG();
// void func_00200CA8();
// void SetVisibility__13AnimEntityDSGb();
// void GetVisibility__C13AnimEntityDSG();
// void PlayAnimation__13AnimEntityDSGb();
// void RenderUpdate__13AnimEntityDSG();
// void GetAIRef__14FenceEntityDSG();
// void SetShader__12LensFlareDSGP7tShaderi();
// void _$_t3Map2Z13tUidUnalignedZP5tPose();
// void HasAlpha__C12StatePropDSG();
// void __Q216radLoadInventoryt8SafeCast1ZQ23sim13PhysicsObject();
// void func_00200DE8();
// void __tfQ29tDrawable14ShaderCallback();
// void func_00200E48();
// void __tfQ216radLoadInventoryt8SafeCast1ZQ23sim13PhysicsObject();
// void func_00200EA8();
// void _$_t18_Vector_alloc_base3Zt10MapElement2Z13tUidUnalignedZP5tPoseZt7s2alloc1Zt10MapElement2Z13tUidUnalignedZP5tPoseb0();
// void func_00200EE0();
// void safe_cast__Q216radLoadInventoryt8SafeCast1ZQ23sim13PhysicsObjectP9IRefCount();
// void func_00200F38();
// void _GLOBAL_$I$__22AnimCollisionEntityDSG();
// void _GLOBAL_$D$__22AnimCollisionEntityDSG();

// bss

// extern UNK_TYPE D_004B1E28;
// extern UNK_TYPE D_004B1E30;
// extern UNK_TYPE D_004B1EC0;
// extern UNK_TYPE D_004B1ED0;
// extern UNK_TYPE D_004B1ED8;
// extern UNK_TYPE D_004B1EE8;
// extern UNK_TYPE D_004B1EF8;

// data

// extern UNK_TYPE D_0042E118;
// extern UNK_TYPE D_0042E134;
// extern UNK_TYPE D_0042E138;
// extern UNK_TYPE _10DSGFactory$mspInstance;
// extern UNK_TYPE _10IEntityDSG$msDeletionsSafe;
// extern UNK_TYPE D_0042E141;
// extern UNK_TYPE _12IntersectDSG$mspIndexData;
// extern UNK_TYPE _12IntersectDSG$mspTerrainData;
// extern UNK_TYPE _12IntersectDSG$mspVertexData;
// extern UNK_TYPE _12IntersectDSG$mspNormalData;
// extern UNK_TYPE D_0042E154;
// extern UNK_TYPE _12LensFlareDSG$spDrawQueue;
// extern UNK_TYPE _12LensFlareDSG$spVisTestQueue;
// extern UNK_TYPE _12LensFlareDSG$sP3DVisibilityCounter;
// extern UNK_TYPE D_0042E17C;

// rodata

// extern UNK_TYPE D_0046D400;
// extern UNK_TYPE D_0046D418;
// extern UNK_TYPE D_0046D428;
// extern UNK_TYPE D_0046D430;
// extern UNK_TYPE D_0046D438;
// extern UNK_TYPE D_0046D448;
// extern UNK_TYPE D_0046D458;
// extern UNK_TYPE D_0046D468;
// extern UNK_TYPE D_0046D478;
// extern UNK_TYPE D_0046D4A8;
// extern UNK_TYPE D_0046D4C8;
// extern UNK_TYPE D_0046D4F0;
// extern UNK_TYPE D_0046D500;
// extern UNK_TYPE D_0046D508;
// extern UNK_TYPE D_0046D518;
// extern UNK_TYPE D_0046D520;
// extern UNK_TYPE D_0046D538;
// extern UNK_TYPE D_0046D540;
// extern UNK_TYPE D_0046D550;
// extern UNK_TYPE D_0046D560;
// extern UNK_TYPE D_0046D570;
// extern UNK_TYPE jtbl_0046D590;
// extern UNK_TYPE jtbl_0046D5C0;
// extern UNK_TYPE D_0046D5F0;
// extern UNK_TYPE D_0046D5F8;
// extern UNK_TYPE D_0046D604;
// extern UNK_TYPE D_0046D608;
// extern UNK_TYPE D_0046D610;
// extern UNK_TYPE D_0046D618;
// extern UNK_TYPE jtbl_0046D630;
// extern UNK_TYPE D_0046D67C;
// extern UNK_TYPE _vt$12StatePropDSG$18CStatePropListener;
// extern UNK_TYPE _vt$12StatePropDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$12StatePropDSG;
// extern UNK_TYPE _vt$19AnimDynaPhysWrapper;
// extern UNK_TYPE _vt$19InstAnimDynaPhysDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$19InstAnimDynaPhysDSG;
// extern UNK_TYPE _vt$14WorldSphereDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$14WorldSphereDSG;
// extern UNK_TYPE _vt$12LensFlareDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$12LensFlareDSG;
// extern UNK_TYPE _vt$15InstStatPhysDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$15InstStatPhysDSG;
// extern UNK_TYPE _vt$18BreakableObjectDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$18BreakableObjectDSG;
// extern UNK_TYPE _vt$14FenceEntityDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$14FenceEntityDSG;
// extern UNK_TYPE _vt$12IntersectDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$12IntersectDSG;
// extern UNK_TYPE _vt$13AnimEntityDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$13AnimEntityDSG;
// extern UNK_TYPE _vt$17InstStatEntityDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$17InstStatEntityDSG;
// extern UNK_TYPE _vt$15StaticEntityDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$15StaticEntityDSG;
// extern UNK_TYPE _vt$15InstDynaPhysDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$15InstDynaPhysDSG;
// extern UNK_TYPE _vt$11DynaPhysDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$11DynaPhysDSG;
// extern UNK_TYPE _vt$13StaticPhysDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$13StaticPhysDSG;
// extern UNK_TYPE _vt$22AnimCollisionEntityDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$22AnimCollisionEntityDSG;
// extern UNK_TYPE _vt$18CollisionEntityDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$18CollisionEntityDSG;
// extern UNK_TYPE _vt$19CollisionAttributes;
// extern UNK_TYPE _vt$10IEntityDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$10IEntityDSG;
// extern UNK_TYPE D_0046E7A0;
// extern UNK_TYPE D_0046E7B0;
// extern UNK_TYPE D_0046E7C0;
// extern UNK_TYPE D_0046E7D8;
// extern UNK_TYPE D_0046E7E8;
// extern UNK_TYPE D_0046E7F8;
// extern UNK_TYPE D_0046E808;
// extern UNK_TYPE D_0046E818;
// extern UNK_TYPE D_0046E820;
// extern UNK_TYPE D_0046E830;
// extern UNK_TYPE D_0046E838;
// extern UNK_TYPE D_0046E848;
// extern UNK_TYPE D_0046E858;
// extern UNK_TYPE D_0046E868;
// extern UNK_TYPE D_0046E880;
// extern UNK_TYPE D_0046E898;
// extern UNK_TYPE D_0046E8A0;
// extern UNK_TYPE D_0046E8C0;
// extern UNK_TYPE D_0046E8E0;
// extern UNK_TYPE D_0046E8F0;
// extern UNK_TYPE D_0046E900;
// extern UNK_TYPE D_0046E908;
// extern UNK_TYPE D_0046E920;
// extern UNK_TYPE D_0046E928;
// extern UNK_TYPE D_0046E940;
// extern UNK_TYPE D_0046E958;
// extern UNK_TYPE D_0046E960;
// extern UNK_TYPE D_0046E970;
// extern UNK_TYPE D_0046E980;
// extern UNK_TYPE D_0046E998;
// extern UNK_TYPE D_0046E9B0;
// extern UNK_TYPE D_0046E9B8;
// extern UNK_TYPE D_0046E9D0;
// extern UNK_TYPE D_0046E9E0;
// extern UNK_TYPE D_0046E9F8;
// extern UNK_TYPE D_0046EA10;
// extern UNK_TYPE D_0046EA18;
// extern UNK_TYPE D_0046EA30;
// extern UNK_TYPE D_0046EA40;
// extern UNK_TYPE D_0046EBF0;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1ZQ23sim13PhysicsObject;
// extern UNK_TYPE _vt$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE D_0046ED48;
// extern UNK_TYPE D_0046ED80;

#endif
