#ifndef ALLLOADERS_HPP
#define ALLLOADERS_HPP

#include "types.h"

#include "AllWrappers_mpLoader_ret.hpp"

// text

class AllWrappers {
    // void CreateInstance__11AllWrappers();
public:
    static AllWrappers *GetInstance(void);
private:
    // void DestroyInstance__11AllWrappers();
    // void mLoader__11AllWrappersi();
public:
    AllWrappers_mpLoader_ret *mpLoader(int);
private:
    // void CoupleAllLoaders__11AllWrappers();
    // void AddGlobalEntity__11AllWrappersP9tDrawable();
    // void GetGlobalEntity__C11AllWrappersG13tUidUnaligned();
    // void ClearGlobalEntities__11AllWrappers();
    // void __11AllWrappers();
    // void _$_11AllWrappers();
};

// void __14AnimCollLoader();
// void _$_14AnimCollLoader();
// void LoadObject__14AnimCollLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__14AnimCollLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__14AnimCollLoaderP21ChunkListenerCallbacki();
// void __13AnimDSGLoader();
// void _$_13AnimDSGLoader();
// void LoadObject__13AnimDSGLoaderP10tChunkFileP12tEntityStore();
// void LoadAnimAtIntersections__13AnimDSGLoaderP18tCompositeDrawableP16tMultiControllerP12tEntityStorebPci();
// void SetRegdListener__13AnimDSGLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__13AnimDSGLoaderP21ChunkListenerCallbacki();
// void __22BillboardWrappedLoader();
// void SetRegdListener__22BillboardWrappedLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__22BillboardWrappedLoaderP21ChunkListenerCallbacki();
// void LoadObject__22BillboardWrappedLoaderP10tChunkFileP12tEntityStore();
// void __21BreakableObjectLoader();
// void _$_21BreakableObjectLoader();
// void SetRegdListener__21BreakableObjectLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__21BreakableObjectLoaderP21ChunkListenerCallbacki();
// void LoadObject__21BreakableObjectLoaderP10tChunkFileP12tEntityStore();
// void __14DynaPhysLoader();
// void _$_14DynaPhysLoader();
// void LoadObject__14DynaPhysLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__14DynaPhysLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__14DynaPhysLoaderP21ChunkListenerCallbacki();
// void __11FenceLoader();
// void LoadObject__11FenceLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__11FenceLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__11FenceLoaderP21ChunkListenerCallbacki();
// void __21GeometryWrappedLoader();
// void SetRegdListener__21GeometryWrappedLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__21GeometryWrappedLoaderP21ChunkListenerCallbacki();
// void LoadObject__21GeometryWrappedLoaderP10tChunkFileP12tEntityStore();
// void __24InstParticleSystemLoader();
// void _$_24InstParticleSystemLoader();
// void SetRegdListener__24InstParticleSystemLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__24InstParticleSystemLoaderP21ChunkListenerCallbacki();
// void LoadObject__24InstParticleSystemLoaderP10tChunkFileP12tEntityStore();
// void __20InstStatEntityLoader();
// void LoadObject__20InstStatEntityLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__20InstStatEntityLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__20InstStatEntityLoaderP21ChunkListenerCallbacki();
// void __18InstStatPhysLoader();
// void _$_18InstStatPhysLoader();
// void LoadObject__18InstStatPhysLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__18InstStatPhysLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__18InstStatPhysLoaderP21ChunkListenerCallbacki();
// void __15IntersectLoader();
// void LoadObject__15IntersectLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__15IntersectLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__15IntersectLoaderP21ChunkListenerCallbacki();
// void __18StaticEntityLoader();
// void LoadObject__18StaticEntityLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__18StaticEntityLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__18StaticEntityLoaderP21ChunkListenerCallbacki();
// void __16StaticPhysLoader();
// void _$_16StaticPhysLoader();
// void LoadObject__16StaticPhysLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__16StaticPhysLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__16StaticPhysLoaderP21ChunkListenerCallbacki();
// void __13TreeDSGLoader();
// void LoadObject__13TreeDSGLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__13TreeDSGLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__13TreeDSGLoaderP21ChunkListenerCallbacki();
// void __17WorldSphereLoader();
// void _$_17WorldSphereLoader();
// void LoadObject__17WorldSphereLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__17WorldSphereLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__17WorldSphereLoaderP21ChunkListenerCallbacki();
// void __15LensFlareLoader();
// void _$_15LensFlareLoader();
// void LoadObject__15LensFlareLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__15LensFlareLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__15LensFlareLoaderP21ChunkListenerCallbacki();
// void SetOcclusionFlags__15LensFlareLoaderP18tCompositeDrawable();
// void __18AnimDynaPhysLoader();
// void _$_18AnimDynaPhysLoader();
// void func_0020D4E8();
// void LoadObject__18AnimDynaPhysLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__18AnimDynaPhysLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__18AnimDynaPhysLoaderP21ChunkListenerCallbacki();
// void SetShadowElement__18AnimDynaPhysLoaderPCcT1();
// void ClearShadowList__18AnimDynaPhysLoader();
// void GetShadowElement__18AnimDynaPhysLoaderG13tUidUnaligned();
// void __25AnimDynaPhysWrapperLoader();
// void _$_25AnimDynaPhysWrapperLoader();
// void LoadObject__25AnimDynaPhysWrapperLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__25AnimDynaPhysWrapperLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__25AnimDynaPhysWrapperLoaderP21ChunkListenerCallbacki();
// void __23AnimObjDSGWrapperLoader();
// void _$_23AnimObjDSGWrapperLoader();
// void LoadObject__23AnimObjDSGWrapperLoaderP10tChunkFileP12tEntityStore();
// void SetRegdListener__23AnimObjDSGWrapperLoaderP21ChunkListenerCallbacki();
// void ModRegdListener__23AnimObjDSGWrapperLoaderP21ChunkListenerCallbacki();
// void IsMissionProp__C18AnimDynaPhysLoaderPCc();
// void func_0020F048();
// void IsRoot__t17ContiguousBinNode1Z11SpatialNode();
// void capacity__Ct3Map2Z13tUidUnalignedZ13tUidUnaligned();
// void __t10MapElement2Z13tUidUnalignedZ13tUidUnalignedRCt10MapElement2Z13tUidUnalignedZ13tUidUnaligned();
// void __uninitialized_copy_aux__H2ZPt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZPt10MapElement2Z13tUidUnalignedZ13tUidUnaligned_X01X01X11G12__false_type_X11();
// void reserve__t3Map2Z13tUidUnalignedZ13tUidUnalignedUi();
// void __as__t10MapElement2Z13tUidUnalignedZ13tUidUnalignedRCt10MapElement2Z13tUidUnalignedZ13tUidUnaligned();
// void __push_heap__H3ZPt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZiZt10MapElement2Z13tUidUnalignedZ13tUidUnaligned_X01X11X11X21_v();
// void __adjust_heap__H3ZPt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZiZt10MapElement2Z13tUidUnalignedZ13tUidUnaligned_X01X11X11X21_v();
// void __make_heap__H3ZPt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZi_X01X01PX11PX21_v();
// void sort_heap__H1ZPt10MapElement2Z13tUidUnalignedZ13tUidUnaligned_X01X01_v();
// void __partial_sort__H2ZPt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZt10MapElement2Z13tUidUnalignedZ13tUidUnaligned_X01X01X01PX11_v();
// void __unguarded_partition__H2ZPt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZt10MapElement2Z13tUidUnalignedZ13tUidUnaligned_X01X01X11_X01();
// void __introsort_loop__H3ZPt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZi_X01X01PX11X21_v();
// void __unguarded_linear_insert__H2ZPt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZt10MapElement2Z13tUidUnalignedZ13tUidUnaligned_X01X11_v();
// void __insertion_sort__H1ZPt10MapElement2Z13tUidUnalignedZ13tUidUnaligned_X01X01_v();
// void __unguarded_insertion_sort_aux__H2ZPt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZt10MapElement2Z13tUidUnalignedZ13tUidUnaligned_X01X01PX11_v();
// void __final_insertion_sort__H1ZPt10MapElement2Z13tUidUnalignedZ13tUidUnaligned_X01X01_v();
// void RefreshIfDirty__Ct3Map2Z13tUidUnalignedZ13tUidUnaligned();
// void __t10MapElement2Z13tUidUnalignedZ13tUidUnaligned();
// void __lower_bound__H3ZPt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZi_X01X01RCX11PX21_X01();
// void find__t3Map2Z13tUidUnalignedZ13tUidUnalignedRC13tUidUnaligned();
// void end__t3Map2Z13tUidUnalignedZ13tUidUnaligned();
// void _M_insert_aux__t6vector2Zt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZt7s2alloc1Zt10MapElement2Z13tUidUnalignedZ13tUidUnalignedPt10MapElement2Z13tUidUnalignedZ13tUidUnalignedRCt10MapElement2Z13tUidUnalignedZ13tUidUnaligned();
// void insert__t3Map2Z13tUidUnalignedZ13tUidUnalignedRC13tUidUnalignedT1();
// void clear__t3Map2Z13tUidUnalignedZ13tUidUnaligned();
// void _$_t18_Vector_alloc_base3Zt10MapElement2Z13tUidUnalignedZ13tUidUnalignedZt7s2alloc1Zt10MapElement2Z13tUidUnalignedZ13tUidUnalignedb0();
// void __t3Map2Z13tUidUnalignedZ13tUidUnaligned();
// void _$_t3Map2Z13tUidUnalignedZ13tUidUnaligned();
// void func_00210038();
// void func_002100C0();
// void _$_21GeometryWrappedLoader();
// void __tf21GeometryWrappedLoader();
// void _$_18StaticEntityLoader();
// void __tf18StaticEntityLoader();
// void __tf16StaticPhysLoader();
// void _$_13TreeDSGLoader();
// void __tf13TreeDSGLoader();
// void _$_11FenceLoader();
// void __tf11FenceLoader();
// void _$_15IntersectLoader();
// void __tf15IntersectLoader();
// void __tf14AnimCollLoader();
// void __tf13AnimDSGLoader();
// void __tf14DynaPhysLoader();
// void __tf18InstStatPhysLoader();
// void _$_20InstStatEntityLoader();
// void __tf20InstStatEntityLoader();
// void __tf17WorldSphereLoader();
// void __tf18AnimDynaPhysLoader();
// void __tf25AnimDynaPhysWrapperLoader();
// void __tf23AnimObjDSGWrapperLoader();
// void _$_22BillboardWrappedLoader();
// void __tf22BillboardWrappedLoader();
// void __tf24InstParticleSystemLoader();
// void __tf21BreakableObjectLoader();
// void __tf15LensFlareLoader();
// void func_00210A90();
// void _GLOBAL_$I$_11AllWrappers$mspInstance();
// void _GLOBAL_$D$_11AllWrappers$mspInstance();

// bss

// extern UNK_TYPE D_004B1F20;
// extern UNK_TYPE D_004B1F28;
// extern UNK_TYPE D_004B1F38;
// extern UNK_TYPE D_004B1F40;

// rodata

// extern UNK_TYPE D_0046F260;
// extern UNK_TYPE jtbl_0046F270;
// extern UNK_TYPE D_0046F2D0;
// extern UNK_TYPE D_0046F2D8;
// extern UNK_TYPE D_0046F2E0;
// extern UNK_TYPE D_0046F2F8;
// extern UNK_TYPE D_0046F300;
// extern UNK_TYPE D_0046F310;
// extern UNK_TYPE D_0046F320;
// extern UNK_TYPE D_0046F330;
// extern UNK_TYPE D_0046F338;
// extern UNK_TYPE D_0046F340;
// extern UNK_TYPE D_0046F348;
// extern UNK_TYPE D_0046F358;
// extern UNK_TYPE D_0046F368;
// extern UNK_TYPE D_0046F378;
// extern UNK_TYPE D_0046F3B0;
// extern UNK_TYPE _vt$15LensFlareLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$15LensFlareLoader;
// extern UNK_TYPE _vt$21BreakableObjectLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$21BreakableObjectLoader;
// extern UNK_TYPE _vt$24InstParticleSystemLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$24InstParticleSystemLoader;
// extern UNK_TYPE _vt$22BillboardWrappedLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$22BillboardWrappedLoader;
// extern UNK_TYPE _vt$23AnimObjDSGWrapperLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$23AnimObjDSGWrapperLoader;
// extern UNK_TYPE _vt$25AnimDynaPhysWrapperLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$25AnimDynaPhysWrapperLoader;
// extern UNK_TYPE _vt$18AnimDynaPhysLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$18AnimDynaPhysLoader;
// extern UNK_TYPE _vt$17WorldSphereLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$17WorldSphereLoader;
// extern UNK_TYPE _vt$20InstStatEntityLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$20InstStatEntityLoader;
// extern UNK_TYPE _vt$18InstStatPhysLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$18InstStatPhysLoader;
// extern UNK_TYPE _vt$14DynaPhysLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$14DynaPhysLoader;
// extern UNK_TYPE _vt$13AnimDSGLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$13AnimDSGLoader;
// extern UNK_TYPE _vt$14AnimCollLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$14AnimCollLoader;
// extern UNK_TYPE _vt$15IntersectLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$15IntersectLoader;
// extern UNK_TYPE _vt$11FenceLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$11FenceLoader;
// extern UNK_TYPE _vt$13TreeDSGLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$13TreeDSGLoader;
// extern UNK_TYPE _vt$16StaticPhysLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$16StaticPhysLoader;
// extern UNK_TYPE _vt$18StaticEntityLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$18StaticEntityLoader;
// extern UNK_TYPE _vt$21GeometryWrappedLoader$14IWrappedLoader;
// extern UNK_TYPE _vt$21GeometryWrappedLoader;
// extern UNK_TYPE D_0046FEB0;
// extern UNK_TYPE D_0046FEC8;
// extern UNK_TYPE D_0046FED8;
// extern UNK_TYPE D_0046FEF0;
// extern UNK_TYPE D_0046FF00;
// extern UNK_TYPE D_0046FF18;
// extern UNK_TYPE D_0046FF28;
// extern UNK_TYPE D_0046FF38;
// extern UNK_TYPE D_0046FF50;
// extern UNK_TYPE D_0046FF68;
// extern UNK_TYPE D_0046FF78;
// extern UNK_TYPE D_0046FF90;
// extern UNK_TYPE D_0046FFA8;
// extern UNK_TYPE D_0046FFC0;
// extern UNK_TYPE D_0046FFD8;
// extern UNK_TYPE D_0046FFF0;
// extern UNK_TYPE D_00470010;
// extern UNK_TYPE D_00470030;
// extern UNK_TYPE D_00470050;
// extern UNK_TYPE D_00470060;
// extern UNK_TYPE D_00470080;
// extern UNK_TYPE D_00470098;
// extern UNK_TYPE D_004701D0;

// data

// extern UNK_TYPE _11AllWrappers$mspInstance;
// extern UNK_TYPE _22BillboardWrappedLoader$mOverrideWrapper;
// extern UNK_TYPE D_0042E1AD;
// extern UNK_TYPE _11FenceLoader$mFenceCount;
// extern UNK_TYPE VIS_TEST_NAME;
// extern UNK_TYPE _18AnimDynaPhysLoader$s_ShadowList;
// extern UNK_TYPE D_0042E1CC;

#endif
