#ifndef ALLMISSION_HPP
#define ALLMISSION_HPP

// text

// void GetInstance__15GameplayManager();
// void SetInstance__15GameplayManagerP15GameplayManager();
// void __15GameplayManager();
// void _$_15GameplayManager();
// void LevelLoaded__15GameplayManager();
// void SetLevelIndex__15GameplayManagerQ211RenderEnums9LevelEnum();
// void SetMissionIndex__15GameplayManagerQ211RenderEnums11MissionEnum();
// void TestPosInFrustrumOfPlayer__15GameplayManagerRCQ218RadicalMathLibrary6Vectorif();
// void ContinueGameplay__15GameplayManager();
// void Update__15GameplayManageri();
// void PlaceCharacterAtLocator__15GameplayManagerP9CharacterP7Locator();
// void PlaceVehicleAtLocator__15GameplayManagerP7VehicleP15CarStartLocator();
// void TestProximityToUsersCarAndNudgeUpIfNecessaryDamnUglyHack__15GameplayManagerRQ218RadicalMathLibrary6VectorP7Vehicle();
// void PlaceVehicleAtLocation__15GameplayManagerP7VehicleGQ218RadicalMathLibrary6Vectorf();
// void PlaceVehicleAtLocatorName__15GameplayManagerP7VehiclePCc();
// void AddLevelVehicle__15GameplayManagerPcQ215GameplayManager9eCarSlotsT1();
// void RemoveLevelVehicleController__15GameplayManager();
// void PauseForIrisClose__15GameplayManagerf();
// void PauseForIrisOpen__15GameplayManagerf();
// void PauseForFadeToBlack__15GameplayManagerf();
// void PauseForFadeFromBlack__15GameplayManagerf();
// void AddMissionVehicle__15GameplayManagerPcN21();
// void EmptyMissionVehicleSlots__15GameplayManager();
// void GetMissionVehicleByName__15GameplayManagerPCc();
// void GetUserVehicleByName__15GameplayManagerPCc();
// void GetMissionVehicleIndex__15GameplayManagerP7Vehicle();
// void RepairVehicle__15GameplayManagerPQ215GameplayManager13CarDataStruct();
// void HandleEvent__15GameplayManager9EventEnumPv();
// void GetCurrentVehicle__15GameplayManager();
// void UnregisterVehicleHUDIcon__15GameplayManager();
// void SetCurrentVehicle__15GameplayManagerP7Vehicle();
// void DumpCurrentCar__15GameplayManager();
// void ClearVehicleSlotIfInSphere__15GameplayManagerQ215GameplayManager9eCarSlotsRCQ218RadicalMathLibrary6Sphere();
// void DumpCurrentCarIfInSphere__15GameplayManagerRCQ218RadicalMathLibrary6Sphere();
// void MakeSureHusksAreReverted__15GameplayManagerP7Vehicle();
// void ClearVehicleSlot__15GameplayManagerQ215GameplayManager9eCarSlots();
// void CopyVehicleSlot__15GameplayManagerQ215GameplayManager9eCarSlotsT1();
// void GetVehicleSlotFilename__15GameplayManagerQ215GameplayManager9eCarSlots();
// void GetVehicleSlotVehicleName__15GameplayManagerQ215GameplayManager9eCarSlots();
// void GetVehicleInSlot__15GameplayManagerQ215GameplayManager9eCarSlots();
// void SetBonusMissionInfo__15GameplayManagerPCcN31bT1T5();
// void GetOverrideCharacterName__15GameplayManagerPc();
// void Initialize__15GameplayManager();
// void Finalize__15GameplayManager();
// void SetCurrentMission__15GameplayManageri();
// void NextMission__15GameplayManager();
// void PrevMission__15GameplayManager();
// void DoNextMission__15GameplayManager();
// void DoPrevMission__15GameplayManager();
// void GetCurrentMission__15GameplayManager();
// void GetCurrentBonusMissionInfo__C15GameplayManager();
// void GetBonusMissionInfo__15GameplayManageri();
// void GetMissionHeap__15GameplayManageri();
// void GetCurrentMissionNum__C15GameplayManager();
// void RestartCurrentMission__15GameplayManager();
// void RestartToMission__15GameplayManagerQ211RenderEnums11MissionEnum();
// void AbortCurrentMission__15GameplayManager();
// void IsBonusMissionDesired__C15GameplayManager();
// void CancelBonusMission__15GameplayManager();
// void EnablePhoneBooths__15GameplayManager();
// void DisablePhoneBooths__15GameplayManager();
// void QueryPhoneBoothsEnabled__15GameplayManager();
// void CreateChaseManager__15GameplayManagerPcT1i();
// void GetChaseManager__15GameplayManagerPc();
// void GetChaseManager__15GameplayManageri();
// void GetMissionNumByName__15GameplayManagerPCc();
// void KillAllChaseManagers__15GameplayManager();
// void EnableBonusMissions__15GameplayManager();
// void DisableBonusMissions__15GameplayManager();
// void func_00171880();
// void DisableAllChaseAI__15GameplayManager();
// void EnableAllChaseAI__15GameplayManager();
// void GetGameType__15GameplayManager();
// void GetControllerColour__15GameplayManageri();
// void GetRespawnManager__15GameplayManager();
// void SetPostLevelFMV__15GameplayManagerPCc();
// void AddToVDU__15GameplayManagerP7Vehicle();
// void UpdateVDU__15GameplayManager();
// void MDKVDU__15GameplayManager();
// void ReleaseFromVDU__15GameplayManagerPcPP7Vehicle();
// void TestForContinuityErrorWithCar__15GameplayManagerP7Vehicleb();
// void RemoveVehicleFromMissionVehicleSlots__15GameplayManagerP7Vehicle();
// void AbortFade__15GameplayManager();
// void __19HasPresentationInfo();
// void _$_19HasPresentationInfo();
// void AddAmbientCharacterAnimation__19HasPresentationInfoUiRC5tName();
// void AmbientCharacterAnimationSetRandom__19HasPresentationInfoUib();
// void ClearAmbientAnimations__19HasPresentationInfo();
// void GoToPattyAndSelmaScreenWhenDone__19HasPresentationInfo();
// void OnStageCompleteSuccessful__C19HasPresentationInfo();
// void Reset__19HasPresentationInfo();
// void SetCameraForDialogLine__19HasPresentationInfoUiRC5tName();
// void SetConversationCamName__19HasPresentationInfoRC5tName();
// void SetConversationCamPcName__19HasPresentationInfoRC5tName();
// void SetConversationCamNpcName__19HasPresentationInfoRC5tName();
// void SetBestSideLocator__19HasPresentationInfoRC5tName();
// void __7Mission();
// void _$_7Mission();
// void Initialize__7Mission19GameMemoryAllocator();
// void Finalize__7Mission();
// void SetToStage__7Missionib();
// void NextStage__7Mission();
// void PrevStage__7Mission();
// void ResetStage__7Mission();
// void HandleEvent__7Mission9EventEnumPv();
// void Update__7MissionUi();
// void IsComplete__7Mission();
// void SetRestartDynaload__7MissionPCcT1();
// void AddBonusObjective__7MissionP14BonusObjective();
// void StartBonusObjectives__7Mission();
// void SetForcedCar__7Missionb();
// void SetMissionTime__7Missioni();
// void CreateStatePropCollectible__7MissionPCcT1i();
// void AttachStatePropCollectible__7MissionPCcT1i();
// void Reset__7Missionb();
// void ResetPlayer__7Mission();
// void InitDynaLoad__7Mission();
// void SetInitPedGroup__7Missioni();
// void DialogueCharactersTeleported__7Mission();
// void GetCurrentStage__7Mission();
// void GetMissionTimeLeftInSeconds__7Mission();
// void GetMissionTimeLeftInMilliSeconds__7Mission();
// void DoUpdate__7Missioni();
// void SetBonusMission__7Mission();
// void IsBonusMission__7Mission();
// void IsRaceMission__7Mission();
// void IsWagerMission__7Mission();
// void UnlockStage__7MissionP12MissionStage();
// void LoadStreetRaceProps__7MissionPCc();
// void UnloadStreetRaceProps__7MissionPCc();
// void SetupStageChange__7Mission();
// void DoStageChange__7Mission();
// void SetSwappedCarsFlag__7Missionb();
// void GetSwappedCarsFlag__7Mission();
// void InitStreetRacePropLoad__7Mission();
// void InitStreetRacePropUnload__7Mission();
// void ShowHUD__7Missionb();
// void CanMDKCar__7MissionP7VehicleP12MissionStage();
// void GetInstance__14MissionManager();
// void CreateInstance__14MissionManager();
// void DestroyInstance__14MissionManager();
// void __14MissionManager();
// void _$_14MissionManager();
// void Initialize__14MissionManager();
// void Finalize__14MissionManager();
// void Update__14MissionManageri();
// void Reset__14MissionManager();
// void HandleEvent__14MissionManager9EventEnumPv();
// void PerformLoading__14MissionManager();
// void RestartCurrentMission__14MissionManager();
// void RestartToMission__14MissionManagerQ211RenderEnums11MissionEnum();
// void AbortCurrentMission__14MissionManager();
// void LoadLevelData__14MissionManager();
// void InitLevelData__14MissionManager();
// void OnProcessRequestsComplete__14MissionManagerPv();
// void LoadMission__14MissionManager();
// void CleanMissionData__14MissionManager();
// void PutEffectHere__14MissionManagerRCQ218RadicalMathLibrary6Vector();
// void CreateInstance__19MissionScriptLoader();
// void GetInstance__19MissionScriptLoader();
// void DestroyInstance__19MissionScriptLoader();
// void __19MissionScriptLoader();
// void _$_19MissionScriptLoader();
// void Register__19MissionScriptLoader();
// void func_00178850();
// void LoadScriptAsync__19MissionScriptLoaderPcPQ214LoadingManager23ProcessRequestsCallback();
// void OnExecuteScriptComplete__19MissionScriptLoaderPv();
// void InitLevelPlayerVehicle__19MissionScriptLoaderiPPc();
// void PlacePlayerCar__19MissionScriptLoaderiPPc();
// void AddPurchaseCarReward__19MissionScriptLoaderiPPc();
// void SetPostLevelFMV__19MissionScriptLoaderiPPc();
// void CreateChaseManager__19MissionScriptLoaderiPPc();
// void SetChaseSpawnRate__19MissionScriptLoaderiPPc();
// void KillAllChaseAI__19MissionScriptLoaderiPPc();
// void AddMission__19MissionScriptLoaderiPPc();
// void AddBonusMission__19MissionScriptLoaderiPPc();
// void CloseMission__19MissionScriptLoaderiPPc();
// void SetForcedCar__19MissionScriptLoaderiPPc();
// void SetDemoLoopTime__19MissionScriptLoaderiPPc();
// void SelectMission__19MissionScriptLoaderiPPc();
// void SetMissionNameIndex__19MissionScriptLoaderiPPc();
// void SetMissionResetPlayerInCar__19MissionScriptLoaderiPPc();
// void SetMissionResetPlayerOutCar__19MissionScriptLoaderiPPc();
// void SetDynaLoadData__19MissionScriptLoaderiPPc();
// void AddBonusObjective__19MissionScriptLoaderiPPc();
// void AddObjective__19MissionScriptLoaderiPPc();
// void AddNPC__19MissionScriptLoaderiPPc();
// void AddDriver__19MissionScriptLoaderiPPc();
// void RemoveNPC__19MissionScriptLoaderiPPc();
// void RemoveDriver__19MissionScriptLoaderiPPc();
// void SetTalkToTarget__19MissionScriptLoaderiPPc();
// void SetDialogueInfo__19MissionScriptLoaderiPPc();
// void SetDialoguePositions__19MissionScriptLoaderiPPc();
// void SetRaceLaps__19MissionScriptLoaderiPPc();
// void BindCollectibleToWaypoint__19MissionScriptLoaderiPPc();
// void AllowUserDump__19MissionScriptLoaderiPPc();
// void SetVehicleToLoad__19MissionScriptLoaderiPPc();
// void CloseObjective__19MissionScriptLoaderiPPc();
// void AddCollectible__19MissionScriptLoaderiPPc();
// void AddCollectibleStateProp__19MissionScriptLoaderiPPc();
// void SetCollectibleEffect__19MissionScriptLoaderiPPc();
// void SetDestination__19MissionScriptLoaderiPPc();
// void TurnGotoDialogOff__19MissionScriptLoaderiPPc();
// void MustActionTrigger__19MissionScriptLoaderiPPc();
// void AddStageVehicle__19MissionScriptLoaderiPPc();
// void MoveStageVehicle__19MissionScriptLoaderiPPc();
// void ActivateVehicle__19MissionScriptLoaderiPPc();
// void AddStageWaypoint__19MissionScriptLoaderiPPc();
// void AddStageCharacter__19MissionScriptLoaderiPPc();
// void AddStageMusicChange__19MissionScriptLoaderiPPc();
// void SetStageMusicAlwaysOn__19MissionScriptLoaderiPPc();
// void SetCompletionDialog__19MissionScriptLoaderiPPc();
// void SetStageStartMusicEvent__19MissionScriptLoaderiPPc();
// void SetMusicState__19MissionScriptLoaderiPPc();
// void SetStageCamera__19MissionScriptLoaderiPPc();
// void ResetToThisStage__19MissionScriptLoaderiPPc();
// void SetTrafficDensity__19MissionScriptLoaderiPPc();
// void AddCondition__19MissionScriptLoaderiPPc();
// void CloseCondition__19MissionScriptLoaderiPPc();
// void AmbientAnimationRandomize__19MissionScriptLoaderiPPc();
// void ClearAmbientAnimations__19MissionScriptLoaderiPPc();
// void AddAmbientNpcAnimation__19MissionScriptLoaderiPPc();
// void AddAmbientPcAnimation__19MissionScriptLoaderiPPc();
// void SetCamBestSide__19MissionScriptLoaderiPPc();
// void SetConversationCamName__19MissionScriptLoaderiPPc();
// void SetConversationCamPcName__19MissionScriptLoaderiPPc();
// void SetConversationCamNpcName__19MissionScriptLoaderiPPc();
// void SetConversationCam__19MissionScriptLoaderiPPc();
// void func_0017C150();
// void SetConversationCamDistance__19MissionScriptLoaderiPPc();
// void SetPresentationBitmap__19MissionScriptLoaderiPPc();
// void SetAnimatedCameraMulticontrollerName__19MissionScriptLoaderiPPc();
// void SetAnimatedCameraName__19MissionScriptLoaderiPPc();
// void SetMissionStartMulticontrollerName__19MissionScriptLoaderiPPc();
// void SetMissionStartCameraName__19MissionScriptLoaderiPPc();
// void SetPlayerCarName__19MissionScriptLoaderiPPc();
// void SetFMVInfo__19MissionScriptLoaderiPPc();
// void CharacterIsChild__19MissionScriptLoaderiPPc();
// void SetFollowDistances__19MissionScriptLoaderiPPc();
// void SetCondMinHealth__19MissionScriptLoaderiPPc();
// void SetConditionPosition__19MissionScriptLoaderiPPc();
// void SetCondTime__19MissionScriptLoaderiPPc();
// void SetHitNRun__19MissionScriptLoaderiPPc();
// void SetObjTargetVehicle__19MissionScriptLoaderiPPc();
// void SetObjTargetBoss__19MissionScriptLoaderiPPc();
// void SetPickupTarget__19MissionScriptLoaderiPPc();
// void AllowRockOut__19MissionScriptLoaderiPPc();
// void SetObjDistance__19MissionScriptLoaderiPPc();
// void SetCondTargetVehicle__19MissionScriptLoaderiPPc();
// void AddStage__19MissionScriptLoaderiPPc();
// void SetStageMessageIndex__19MissionScriptLoaderiPPc();
// void SetStageTime__19MissionScriptLoaderiPPc();
// void AddStageTime__19MissionScriptLoaderiPPc();
// void ShowStageComplete__19MissionScriptLoaderiPPc();
// void SetHUDIcon__19MissionScriptLoaderiPPc();
// void SetIrisWipe__19MissionScriptLoaderiPPc();
// void SetFadeOut__19MissionScriptLoaderiPPc();
// void CloseStage__19MissionScriptLoaderiPPc();
// void SetVehicleAIParams__19MissionScriptLoaderiPPc();
// void SetBonusMissionStart__19MissionScriptLoaderiPPc();
// void func_0017CB78();
// void GetVehicleByName__19MissionScriptLoaderPCc();
// void GetDirectionalArrowType__19MissionScriptLoaderPCcPQ220DirectionalArrowEnum4TYPE();
// void LoadP3DFile__19MissionScriptLoaderiPPc();
// void LoadDisposableCar__19MissionScriptLoaderiPPc();
// void AddCharacter__19MissionScriptLoaderiPPc();
// void AddNPCCharacterBonusMission__19MissionScriptLoaderiPPc();
// void SetBonusMissionDialoguePositions__19MissionScriptLoaderiPPc();
// void AddAmbientCharacter__19MissionScriptLoaderiPPc();
// void AddBonusMissionNPCWaypoint__19MissionScriptLoaderiPPc();
// void AddObjectiveNPCWaypoint__19MissionScriptLoaderiPPc();
// void AddNPCWaypoint__19MissionScriptLoaderPCcT1();
// void AddPurchaseCarNPCWaypoint__19MissionScriptLoaderiPPc();
// void AddAmbientNPCWaypoint__19MissionScriptLoaderiPPc();
// void ActivateTrigger__19MissionScriptLoaderiPPc();
// void DeactivateTrigger__19MissionScriptLoaderiPPc();
// void CreateAnimPhysObject__19MissionScriptLoaderiPPc();
// void CreateActionEventTrigger__19MissionScriptLoaderiPPc();
// void LinkActionToObjectJoint__19MissionScriptLoaderiPPc();
// void LinkActionToObject__19MissionScriptLoaderiPPc();
// void SetCoinDrawable__19MissionScriptLoaderiPPc();
// void SetParticleTexture__19MissionScriptLoaderiPPc();
// void AddSafeZone__19MissionScriptLoaderiPPc();
// void CreatePedGroup__19MissionScriptLoaderiPPc();
// void AddPed__19MissionScriptLoaderiPPc();
// void ClosePedGroup__19MissionScriptLoaderiPPc();
// void UsePedGroup__19MissionScriptLoaderiPPc();
// void BindReward__19MissionScriptLoaderiPPc();
// void SetCarAttributes__19MissionScriptLoaderiPPc();
// void SetTotalGags__19MissionScriptLoaderiPPc();
// void SetTotalWasps__19MissionScriptLoaderiPPc();
// void CreateTrafficGroup__19MissionScriptLoaderiPPc();
// void AddTrafficModel__19MissionScriptLoaderiPPc();
// void CloseTrafficGroup__19MissionScriptLoaderiPPc();
// void SetRespawnRate__19MissionScriptLoaderiPPc();
// void EnableTutorialMode__19MissionScriptLoaderiPPc();
// void StartCountdown__19MissionScriptLoaderiPPc();
// void AddToCountdownSequence__19MissionScriptLoaderiPPc();
// void SetCarStartCamera__19MissionScriptLoaderiPPc();
// void GoToPattyAndSelmaScreenWhenDone__19MissionScriptLoaderiPPc();
// void StreetRacePropsLoad__19MissionScriptLoaderiPPc();
// void StreetRacePropsUnload__19MissionScriptLoaderiPPc();
// void UseElapsedTime__19MissionScriptLoaderiPPc();
// void AttachStatePropCollectible__19MissionScriptLoaderiPPc();
// void ShowHUD__19MissionScriptLoaderiPPc();
// void SetNumValidFailureHints__19MissionScriptLoaderiPPc();
// void SetParTime__19MissionScriptLoaderiPPc();
// void SetRaceEnteryFee__19MissionScriptLoaderiPPc();
// void SetCoinFee__19MissionScriptLoaderiPPc();
// void PutMFPlayerInCar__19MissionScriptLoaderiPPc();
// void SetStatepropShadow__19MissionScriptLoaderiPPc();
// void TreeOfWoeErrorMsg__19MissionScriptLoaderPCc();
// void DisableHitAndRun__19MissionScriptLoaderiPPc();
// void EnableHitAndRun__19MissionScriptLoaderiPPc();
// void ResetHitAndRun__19MissionScriptLoaderiPPc();
// void SetNumChaseCars__19MissionScriptLoaderiPPc();
// void SetHitAndRunDecay__19MissionScriptLoaderiPPc();
// void SetHitAndRunMeter__19MissionScriptLoaderiPPc();
// void SwapInDefaultCar__19MissionScriptLoaderiPPc();
// void SetSwapDefaultCarRespawnLocatorName__19MissionScriptLoaderiPPc();
// void SetSwapForcedCarRespawnLocatorName__19MissionScriptLoaderiPPc();
// void SetSwapPlayerRespawnLocatorName__19MissionScriptLoaderiPPc();
// void NoTrafficForStage__19MissionScriptLoaderiPPc();
// void ClearTrafficForStage__19MissionScriptLoaderiPPc();
// void AddGlobalProp__19MissionScriptLoaderiPPc();
// void PlacePlayerAtLocatorName__19MissionScriptLoaderiPPc();
// void msPlacePlayerCarAtLocatorName__19MissionScriptLoaderiPPc();
// void SetStageAIRaceCatchupParams__19MissionScriptLoaderiPPc();
// void SetStageAIEvadeCatchupParams__19MissionScriptLoaderiPPc();
// void SetStageAITargetCatchupParams__19MissionScriptLoaderiPPc();
// void SetPauseDuration__19MissionScriptLoaderiPPc();
// void SetCharacterToHide__19MissionScriptLoaderiPPc();
// void SetLevelOver__19MissionScriptLoaderiPPc();
// void SetGameOver__19MissionScriptLoaderiPPc();
// void StayInBlack__19MissionScriptLoaderiPPc();
// void AllowMissionAbort__19MissionScriptLoaderiPPc();
// void __12MissionStage();
// void _$_12MissionStage();
// void DestroyStageVehicleAI__12MissionStage();
// void AddVehicle__12MissionStageP7VehicleiP15CarStartLocatorPc();
// void SetAIParams__12MissionStageP7VehicleRCQ212MissionStage8AIParams();
// void SetAIRaceCatchupParams__12MissionStageP7VehicleRCQ29VehicleAI17RaceCatchupParams();
// void SetAIEvadeCatchupParams__12MissionStageP7VehicleRCQ29VehicleAI18EvadeCatchupParams();
// void SetAITargetCatchupParams__12MissionStageP7VehicleRCQ29VehicleAI19TargetCatchupParams();
// void AddWaypoint__12MissionStageP7Locator();
// void AddCharacter__12MissionStagePcP15CarStartLocatorT2PCcP7Vehicle();
// void AddCharacter__12MissionStagePcP15CarStartLocatorT2PCcT1();
// void GetFailureCondition__C12MissionStage();
// void Initialize__12MissionStage();
// void Finalize__12MissionStage();
// void VehicleFinalize__12MissionStage();
// void Reset__12MissionStage();
// void VehicleInfoInitialize__12MissionStage();
// void Start__12MissionStage();
// void Update__12MissionStageUi();
// void HandleEvent__12MissionStage9EventEnumPv();
// void SetStageTime__12MissionStageQ212MissionStage13StageTimeTypeUi();
// void GetStageTime__12MissionStageRQ212MissionStage13StageTimeTypeRUi();
// void func_001828C8();
// void SetCameraInfo__12MissionStageQ28SuperCam4TypebT2();
// void GetVehicle__12MissionStagei();
// void SetChaseSpawnRate__12MissionStagePcUi();
// void AddSafeZone__12MissionStageP15CarStartLocatorUi();
// void DestroyAllSafeZones__12MissionStage();
// void triggerStageDialog__12MissionStage();
// void SetLockRequirement__12MissionStageUiQ312MissionStage15LockRequirement4TypePCc();
// void GetLockRequirement__12MissionStageUi();
// void DisplayMissionStageIndexMessage__12MissionStage();
// void SetCountdownEnabled__12MissionStageUiG13tUidUnaligned();
// void AddCountdownSequenceUnit__12MissionStagePCci();
// void GetCountdownSequenceUnit__C12MissionStagei();
// void PutAllAisInLimbo__12MissionStageb();
// void DoTransition__12MissionStage();
// void UseElapsedTime__12MissionStage();
// void QueryUseElapsedTime__12MissionStage();
// void SetRaceEnteryFee__12MissionStagei();
// void PutMFPlayerInCar__12MissionStage();
// void DisableHitAndRun__12MissionStage();
// void SwapInDefaultCar__12MissionStage();
// void SwapInDefaultCarStart__12MissionStage();
// void OnProcessRequestsComplete__12MissionStagePv();
// void SetSwapDefaultCarRespawnLocatorName__12MissionStagePc();
// void SetSwapPlayerRespawnLocatorName__12MissionStagePc();
// void SetSwapForcedCarRespawnLocatorName__12MissionStagePc();
// void DisableTraffic__12MissionStage();
// void ClearTrafficForStage__12MissionStage();
// void SetPlayerRespawnLocatorName__12MissionStagePc();
// void SetmsPlayerCarRespawnLocatorName__12MissionStagePc();
// void OnStageCompleteSuccessful__12MissionStage();
// void SetCharacterToHide__12MissionStagePc();
// void SetLevelOver__12MissionStage();
// void SetStageMusicState__12MissionStageUiUi();
// void GetStageMusicState__12MissionStageRUiT1();
// void GetMainAIVehicleForThisStage__12MissionStage();
// void __12AnimatedIcon();
// void _$_12AnimatedIcon();
// void Init__12AnimatedIconPCcRCQ218RadicalMathLibrary6MatrixbT3();
// void Init__12AnimatedIconPCcRCQ218RadicalMathLibrary6VectorbT3();
// void ScaleByCameraDistance__12AnimatedIconffff();
// void Move__12AnimatedIconRCQ218RadicalMathLibrary6Vector();
// void Update__12AnimatedIconUi();
// void Reset__12AnimatedIcon();
// void ShouldRender__12AnimatedIconb();
// void __nw__12AnimatedIconUi();
// void __nw__12AnimatedIconUi19GameMemoryAllocator();
// void __dl__12AnimatedIconPv();
// void func_00183EA0();
// void InitAnimatedIcons__12AnimatedIcon19GameMemoryAllocator();
// void ShutdownAnimatedIcons__12AnimatedIcon();
// void SetFlag__12AnimatedIconQ212AnimatedIcon4Flagb();
// void GetFlag__C12AnimatedIconQ212AnimatedIcon4Flag();
// void Deallocate__12AnimatedIcon();
// void SetUpContents__12AnimatedIconPCc();
// void SetUpEffects__12AnimatedIcon();
// void __Q212AnimatedIcon11AnimIconDSG();
// void _$_Q212AnimatedIcon11AnimIconDSG();
// void CalcScale__Q212AnimatedIcon11AnimIconDSG();
// void SetScaleParameters__Q212AnimatedIcon11AnimIconDSGffff();
// void Display__Q212AnimatedIcon11AnimIconDSG();
// void __16BonusMissionInfo();
// void _$_16BonusMissionInfo();
// void HandleEvent__16BonusMissionInfo9EventEnumPv();
// void SetUpIcon__16BonusMissionInfoPCcGQ218RadicalMathLibrary6Vector();
// void SetUpAlternateIcon__16BonusMissionInfoPCcGQ218RadicalMathLibrary6Vector();
// void SetEventLocator__16BonusMissionInfoP12EventLocator();
// void SetPositions__16BonusMissionInfoP15CarStartLocatorN21();
// void CleanUp__16BonusMissionInfo();
// void Update__16BonusMissionInfoUi();
// void Enable__16BonusMissionInfo();
// void Disable__16BonusMissionInfo();
// void SetCompleted__16BonusMissionInfob();
// void TriggerDialogue__16BonusMissionInfo();
// void SetNPC__16BonusMissionInfoP9Character();
// void ResetCharacterPositions__16BonusMissionInfo();
// void ResetMissionBitmap__16BonusMissionInfo();
// void __19NoCopBonusObjective();
// void _$_19NoCopBonusObjective();
// void Initialize__19NoCopBonusObjective();
// void Finalize__19NoCopBonusObjective();
// void HandleEvent__19NoCopBonusObjective9EventEnumPv();
// void OnReset__19NoCopBonusObjective();
// void OnStart__19NoCopBonusObjective();
// void OnUpdate__19NoCopBonusObjectiveUi();
// void __22NoDamageBonusObjective();
// void _$_22NoDamageBonusObjective();
// void Initialize__22NoDamageBonusObjective();
// void Finalize__22NoDamageBonusObjective();
// void HandleEvent__22NoDamageBonusObjective9EventEnumPv();
// void OnReset__22NoDamageBonusObjective();
// void OnStart__22NoDamageBonusObjective();
// void OnUpdate__22NoDamageBonusObjectiveUi();
// void __24TimeRemainBonusObjective();
// void _$_24TimeRemainBonusObjective();
// void Initialize__24TimeRemainBonusObjective();
// void Finalize__24TimeRemainBonusObjective();
// void GetNumericData__24TimeRemainBonusObjective();
// void OnReset__24TimeRemainBonusObjective();
// void OnStart__24TimeRemainBonusObjective();
// void OnUpdate__24TimeRemainBonusObjectiveUi();
// void __26RacePositionBonusObjective();
// void _$_26RacePositionBonusObjective();
// void Initialize__26RacePositionBonusObjective();
// void Finalize__26RacePositionBonusObjective();
// void HandleEvent__26RacePositionBonusObjective9EventEnumPv();
// void OnReset__26RacePositionBonusObjective();
// void OnStart__26RacePositionBonusObjective();
// void OnUpdate__26RacePositionBonusObjectiveUi();
// void __20StatePropCollectible();
// void _$_20StatePropCollectible();
// void PreReactToCollision__20StatePropCollectiblePQ23sim8SimStateRQ23sim9Collision();
// void AdvanceAnimation__20StatePropCollectiblef();
// void SetTransform__20StatePropCollectibleRCQ218RadicalMathLibrary6Matrix();
// void SetPosition__20StatePropCollectibleRCQ218RadicalMathLibrary6Vector();
// void LoadSetup__20StatePropCollectibleP14CStatePropDataiRCQ218RadicalMathLibrary6MatrixP19CollisionAttributesbP12tEntityStoreT5PQ23sim15CollisionObjectPQ23sim13PhysicsObject();
// void AddToDSG__20StatePropCollectible();
// void RemoveFromDSG__20StatePropCollectible();
// void Update__20StatePropCollectiblef();
// void RecieveEvent__20StatePropCollectibleiP10CStateProp();
// void Explode__20StatePropCollectible();
// void GetPosition__20StatePropCollectiblePQ218RadicalMathLibrary6Vector();
// void GetHeading__20StatePropCollectiblePQ218RadicalMathLibrary6Vector();
// void EnableHudIcon__20StatePropCollectibleb();
// void DoCollisionTesting__20StatePropCollectible();
// void CameraShake__20StatePropCollectible();
// void func_00187020();
// void __uninitialized_copy_aux__H2ZP5tNameZP5tName_X01X01X11G12__false_type_X11();
// void _M_insert_aux__t6vector2Z5tNameZt7s2alloc1Z5tNameP5tNameRC5tName();
// void fill__H2ZP5tNameZ5tName_X01X01RCX11_v();
// void __uninitialized_fill_n_aux__H3ZP5tNameZUiZ5tName_X01X11RCX21G12__false_type_X01();
// void insert__t6vector2Z5tNameZt7s2alloc1Z5tNameP5tNameUiRC5tName();
// void func_00187548();
// void func_00187618();
// void __tf12MissionStage();
// void __tf7Mission();
// void __tf16BonusMissionInfo();
// void __tf15GameplayManager();
// void __tf14MissionManager();
// void __tf19MissionScriptLoader();
// void __tfQ212AnimatedIcon11AnimIconDSG();
// void __tf12AnimatedIcon();
// void func_001878F8();
// void __tfQ218tCompositeDrawable15DrawableElement();
// void __tf14BonusObjective();
// void __tf20StatePropCollectible();
// void __tf22NoDamageBonusObjective();
// void __tf19NoCopBonusObjective();
// void __tf24TimeRemainBonusObjective();
// void __tf26RacePositionBonusObjective();
// void __tf19HasPresentationInfo();
// void func_00187BB0();
// void _$_t18_Vector_alloc_base3Z5tNameZt7s2alloc1Z5tNameb0();
// void func_00187BF0();
// void __Q215GameplayManager16PlayerAndCarInfo();
// void __Q215GameplayManager13CarDataStruct();
// void func_00187C80();
// void OnPresentationEventBegin__15GameplayManagerP17PresentationEvent();
// void OnPresentationEventLoadComplete__15GameplayManagerP17PresentationEvent();
// void OnPresentationEventEnd__15GameplayManagerP17PresentationEvent();
// void func_00187CB0();
// void IsSundayDrive__15GameplayManager();
// void IsSuperSprint__15GameplayManager();
// void IsSundayDrive__14MissionManager();
// void __Q27Console21ExecuteScriptCallback();
// void func_00187D48();
// void _$_14BonusObjective();
// void OnReset__14BonusObjective();
// void OnStart__14BonusObjective();
// void OnUpdate__14BonusObjectiveUi();
// void func_00187DA0();
// void GetNumericData__22NoDamageBonusObjective();
// void GetNumericData__19NoCopBonusObjective();
// void GetNumericData__26RacePositionBonusObjective();
// void __Q216radLoadInventoryt8SafeCast1Z8tTexture();
// void func_00187E08();
// void __tfQ27Console21ExecuteScriptCallback();
// void func_00187E70();
// void __tfQ216radLoadInventoryt8SafeCast1Z8tTexture();
// void func_00187EE8();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z8tTextureP9IRefCount();
// void func_00187F60();
// void _GLOBAL_$I$_15GameplayManager$spInstance();

// data

// extern UNK_TYPE D_0042C494;
// extern UNK_TYPE _15GameplayManager$spInstance;
// extern UNK_TYPE NUM_CONTINUITY_ERRORS;
// extern UNK_TYPE _14MissionManager$spInstance;
// extern UNK_TYPE _19MissionScriptLoader$spInstance;
// extern UNK_TYPE _12AnimatedIcon$sAnimatedIconPool;
// extern UNK_TYPE _12AnimatedIcon$sNumAllocated;
// extern UNK_TYPE STATEPROP_SHAKE_FORCE;

// bss

// extern UNK_TYPE D_004B1AE0;
// extern UNK_TYPE D_004B1AE8;
// extern UNK_TYPE D_004B1AF0;
// extern UNK_TYPE D_004B1AF8;
// extern UNK_TYPE D_004B1B00;
// extern UNK_TYPE D_004B1B18;
// extern UNK_TYPE D_004B1B28;
// extern UNK_TYPE D_004B1B30;

// rodata

// extern UNK_TYPE D_0045ED90;
// extern UNK_TYPE D_0045EDA0;
// extern UNK_TYPE D_0045EDB8;
// extern UNK_TYPE D_0045EDC0;
// extern UNK_TYPE D_0045EDD0;
// extern UNK_TYPE D_0045EDD8;
// extern UNK_TYPE D_0045EDE0;
// extern UNK_TYPE D_0045EDF0;
// extern UNK_TYPE D_0045EE00;
// extern UNK_TYPE D_0045EE10;
// extern UNK_TYPE D_0045EE20;
// extern UNK_TYPE D_0045EE30;
// extern UNK_TYPE D_0045EE40;
// extern UNK_TYPE D_0045EE50;
// extern UNK_TYPE D_0045EE60;
// extern UNK_TYPE D_0045EE70;
// extern UNK_TYPE D_0045EE80;
// extern UNK_TYPE D_0045EEB0;
// extern UNK_TYPE D_0045EEF0;
// extern UNK_TYPE D_0045EF20;
// extern UNK_TYPE D_0045EF60;
// extern UNK_TYPE D_0045EF68;
// extern UNK_TYPE D_0045EF70;
// extern UNK_TYPE D_0045EF80;
// extern UNK_TYPE D_0045EF88;
// extern UNK_TYPE D_0045EF90;
// extern UNK_TYPE D_0045EF98;
// extern UNK_TYPE D_0045EFA8;
// extern UNK_TYPE D_0045EFB0;
// extern UNK_TYPE D_0045EFB8;
// extern UNK_TYPE D_0045EFC0;
// extern UNK_TYPE D_0045EFC8;
// extern UNK_TYPE jtbl_0045EFD0;
// extern UNK_TYPE D_0045EFE8;
// extern UNK_TYPE D_0045EFF0;
// extern UNK_TYPE D_0045EFF8;
// extern UNK_TYPE jtbl_0045F010;
// extern UNK_TYPE D_0045F028;
// extern UNK_TYPE D_0045F040;
// extern UNK_TYPE D_0045F048;
// extern UNK_TYPE D_0045F058;
// extern UNK_TYPE D_0045F060;
// extern UNK_TYPE D_0045F068;
// extern UNK_TYPE D_0045F078;
// extern UNK_TYPE D_0045F080;
// extern UNK_TYPE D_0045F088;
// extern UNK_TYPE D_0045F0A8;
// extern UNK_TYPE D_0045F0C8;
// extern UNK_TYPE D_0045F0E0;
// extern UNK_TYPE D_0045F108;
// extern UNK_TYPE D_0045F120;
// extern UNK_TYPE D_0045F130;
// extern UNK_TYPE jtbl_0045F160;
// extern UNK_TYPE D_0045F188;
// extern UNK_TYPE D_0045F1B0;
// extern UNK_TYPE D_0045F1D8;
// extern UNK_TYPE D_0045F200;
// extern UNK_TYPE D_0045F240;
// extern UNK_TYPE D_0045F300;
// extern UNK_TYPE D_0045F318;
// extern UNK_TYPE D_0045F328;
// extern UNK_TYPE D_0045F340;
// extern UNK_TYPE D_0045F350;
// extern UNK_TYPE D_0045F360;
// extern UNK_TYPE D_0045F368;
// extern UNK_TYPE D_0045F378;
// extern UNK_TYPE D_0045F388;
// extern UNK_TYPE D_0045F398;
// extern UNK_TYPE D_0045F3B0;
// extern UNK_TYPE D_0045F3C0;
// extern UNK_TYPE D_0045F3D8;
// extern UNK_TYPE D_0045F3F0;
// extern UNK_TYPE D_0045F400;
// extern UNK_TYPE D_0045F410;
// extern UNK_TYPE D_0045F420;
// extern UNK_TYPE D_0045F438;
// extern UNK_TYPE D_0045F450;
// extern UNK_TYPE D_0045F460;
// extern UNK_TYPE D_0045F478;
// extern UNK_TYPE D_0045F488;
// extern UNK_TYPE D_0045F4A0;
// extern UNK_TYPE D_0045F4B0;
// extern UNK_TYPE D_0045F4C0;
// extern UNK_TYPE D_0045F4D8;
// extern UNK_TYPE D_0045F4F8;
// extern UNK_TYPE D_0045F508;
// extern UNK_TYPE D_0045F518;
// extern UNK_TYPE D_0045F530;
// extern UNK_TYPE D_0045F540;
// extern UNK_TYPE D_0045F560;
// extern UNK_TYPE D_0045F580;
// extern UNK_TYPE D_0045F590;
// extern UNK_TYPE D_0045F5A8;
// extern UNK_TYPE D_0045F5B8;
// extern UNK_TYPE D_0045F5C8;
// extern UNK_TYPE D_0045F5D8;
// extern UNK_TYPE D_0045F5F0;
// extern UNK_TYPE D_0045F608;
// extern UNK_TYPE D_0045F618;
// extern UNK_TYPE D_0045F638;
// extern UNK_TYPE D_0045F640;
// extern UNK_TYPE D_0045F658;
// extern UNK_TYPE D_0045F668;
// extern UNK_TYPE D_0045F680;
// extern UNK_TYPE D_0045F690;
// extern UNK_TYPE D_0045F6A0;
// extern UNK_TYPE D_0045F6B0;
// extern UNK_TYPE D_0045F6C8;
// extern UNK_TYPE D_0045F6D8;
// extern UNK_TYPE D_0045F6F0;
// extern UNK_TYPE D_0045F708;
// extern UNK_TYPE D_0045F720;
// extern UNK_TYPE D_0045F738;
// extern UNK_TYPE D_0045F750;
// extern UNK_TYPE D_0045F768;
// extern UNK_TYPE D_0045F778;
// extern UNK_TYPE D_0045F788;
// extern UNK_TYPE D_0045F798;
// extern UNK_TYPE D_0045F7A8;
// extern UNK_TYPE D_0045F7B8;
// extern UNK_TYPE D_0045F7D0;
// extern UNK_TYPE D_0045F7E8;
// extern UNK_TYPE D_0045F7F8;
// extern UNK_TYPE D_0045F808;
// extern UNK_TYPE D_0045F818;
// extern UNK_TYPE D_0045F828;
// extern UNK_TYPE D_0045F840;
// extern UNK_TYPE D_0045F860;
// extern UNK_TYPE D_0045F880;
// extern UNK_TYPE D_0045F898;
// extern UNK_TYPE D_0045F8B0;
// extern UNK_TYPE D_0045F8D0;
// extern UNK_TYPE D_0045F8E8;
// extern UNK_TYPE D_0045F900;
// extern UNK_TYPE D_0045F918;
// extern UNK_TYPE D_0045F938;
// extern UNK_TYPE D_0045F958;
// extern UNK_TYPE D_0045F978;
// extern UNK_TYPE D_0045F990;
// extern UNK_TYPE D_0045F9A0;
// extern UNK_TYPE D_0045F9B0;
// extern UNK_TYPE D_0045F9C0;
// extern UNK_TYPE D_0045F9D8;
// extern UNK_TYPE D_0045F9E8;
// extern UNK_TYPE D_0045FA00;
// extern UNK_TYPE D_0045FA18;
// extern UNK_TYPE D_0045FA30;
// extern UNK_TYPE D_0045FA40;
// extern UNK_TYPE D_0045FA50;
// extern UNK_TYPE D_0045FA60;
// extern UNK_TYPE D_0045FA68;
// extern UNK_TYPE D_0045FA78;
// extern UNK_TYPE D_0045FA88;
// extern UNK_TYPE D_0045FA98;
// extern UNK_TYPE D_0045FAA8;
// extern UNK_TYPE D_0045FAB8;
// extern UNK_TYPE D_0045FAD0;
// extern UNK_TYPE D_0045FAE0;
// extern UNK_TYPE D_0045FAF8;
// extern UNK_TYPE D_0045FB10;
// extern UNK_TYPE D_0045FB20;
// extern UNK_TYPE D_0045FB30;
// extern UNK_TYPE D_0045FB40;
// extern UNK_TYPE D_0045FB58;
// extern UNK_TYPE D_0045FB70;
// extern UNK_TYPE D_0045FB80;
// extern UNK_TYPE D_0045FB98;
// extern UNK_TYPE D_0045FBB0;
// extern UNK_TYPE D_0045FBC0;
// extern UNK_TYPE D_0045FBD8;
// extern UNK_TYPE D_0045FBF0;
// extern UNK_TYPE D_0045FC00;
// extern UNK_TYPE D_0045FC10;
// extern UNK_TYPE D_0045FC20;
// extern UNK_TYPE D_0045FC30;
// extern UNK_TYPE D_0045FC48;
// extern UNK_TYPE D_0045FC60;
// extern UNK_TYPE D_0045FC78;
// extern UNK_TYPE D_0045FC88;
// extern UNK_TYPE D_0045FC98;
// extern UNK_TYPE D_0045FCB0;
// extern UNK_TYPE D_0045FCC8;
// extern UNK_TYPE D_0045FCD0;
// extern UNK_TYPE D_0045FCF0;
// extern UNK_TYPE D_0045FD10;
// extern UNK_TYPE D_0045FD28;
// extern UNK_TYPE D_0045FD48;
// extern UNK_TYPE D_0045FD68;
// extern UNK_TYPE D_0045FD80;
// extern UNK_TYPE D_0045FD98;
// extern UNK_TYPE D_0045FDB0;
// extern UNK_TYPE D_0045FDC8;
// extern UNK_TYPE D_0045FDE0;
// extern UNK_TYPE D_0045FDF8;
// extern UNK_TYPE D_0045FE10;
// extern UNK_TYPE D_0045FE30;
// extern UNK_TYPE D_0045FE50;
// extern UNK_TYPE D_0045FE60;
// extern UNK_TYPE D_0045FE70;
// extern UNK_TYPE D_0045FE80;
// extern UNK_TYPE D_0045FE98;
// extern UNK_TYPE D_0045FEB0;
// extern UNK_TYPE D_0045FEC8;
// extern UNK_TYPE D_0045FEE0;
// extern UNK_TYPE D_0045FEF8;
// extern UNK_TYPE D_0045FF08;
// extern UNK_TYPE D_0045FF20;
// extern UNK_TYPE D_0045FF30;
// extern UNK_TYPE D_0045FF40;
// extern UNK_TYPE D_0045FF60;
// extern UNK_TYPE D_0045FF80;
// extern UNK_TYPE D_0045FF98;
// extern UNK_TYPE D_0045FFB8;
// extern UNK_TYPE D_0045FFD0;
// extern UNK_TYPE D_0045FFE8;
// extern UNK_TYPE D_00460008;
// extern UNK_TYPE D_00460018;
// extern UNK_TYPE D_00460030;
// extern UNK_TYPE D_00460048;
// extern UNK_TYPE D_00460068;
// extern UNK_TYPE D_00460080;
// extern UNK_TYPE D_00460098;
// extern UNK_TYPE D_004600A8;
// extern UNK_TYPE D_004600C0;
// extern UNK_TYPE D_004600C8;
// extern UNK_TYPE D_004600D0;
// extern UNK_TYPE D_00460100;
// extern UNK_TYPE D_00460110;
// extern UNK_TYPE D_00460120;
// extern UNK_TYPE D_00460128;
// extern UNK_TYPE D_00460130;
// extern UNK_TYPE D_00460138;
// extern UNK_TYPE D_004601B0;
// extern UNK_TYPE D_004601C0;
// extern UNK_TYPE D_004601D0;
// extern UNK_TYPE D_004601D8;
// extern UNK_TYPE D_004601E8;
// extern UNK_TYPE jtbl_004601F0;
// extern UNK_TYPE D_00460240;
// extern UNK_TYPE D_00460248;
// extern UNK_TYPE D_00460250;
// extern UNK_TYPE jtbl_00460260;
// extern UNK_TYPE jtbl_004602A0;
// extern UNK_TYPE D_004602C0;
// extern UNK_TYPE D_004602C8;
// extern UNK_TYPE D_004602D0;
// extern UNK_TYPE D_004602D8;
// extern UNK_TYPE D_004602E0;
// extern UNK_TYPE D_004602E8;
// extern UNK_TYPE D_004602F0;
// extern UNK_TYPE D_004602F8;
// extern UNK_TYPE D_00460300;
// extern UNK_TYPE D_00460308;
// extern UNK_TYPE D_00460310;
// extern UNK_TYPE D_00460320;
// extern UNK_TYPE D_00460330;
// extern UNK_TYPE D_00460338;
// extern UNK_TYPE D_00460348;
// extern UNK_TYPE D_00460358;
// extern UNK_TYPE D_00460370;
// extern UNK_TYPE D_00460380;
// extern UNK_TYPE D_00460390;
// extern UNK_TYPE D_004603B8;
// extern UNK_TYPE D_004603D0;
// extern UNK_TYPE D_004603E8;
// extern UNK_TYPE D_004603F8;
// extern UNK_TYPE D_00460408;
// extern UNK_TYPE D_00460418;
// extern UNK_TYPE D_00460428;
// extern UNK_TYPE D_00460438;
// extern UNK_TYPE D_00460448;
// extern UNK_TYPE D_00460458;
// extern UNK_TYPE D_00460468;
// extern UNK_TYPE D_00460478;
// extern UNK_TYPE D_00460490;
// extern UNK_TYPE D_004604A0;
// extern UNK_TYPE D_004604B0;
// extern UNK_TYPE D_004604C0;
// extern UNK_TYPE D_004604C8;
// extern UNK_TYPE D_004604D8;
// extern UNK_TYPE D_004604E0;
// extern UNK_TYPE D_00460510;
// extern UNK_TYPE D_00460518;
// extern UNK_TYPE D_00460528;
// extern UNK_TYPE D_00460538;
// extern UNK_TYPE D_00460540;
// extern UNK_TYPE D_00460550;
// extern UNK_TYPE D_00460558;
// extern UNK_TYPE D_00460568;
// extern UNK_TYPE D_00460578;
// extern UNK_TYPE D_00460598;
// extern UNK_TYPE D_004605A8;
// extern UNK_TYPE D_004605B0;
// extern UNK_TYPE D_004605B8;
// extern UNK_TYPE D_004605C0;
// extern UNK_TYPE D_004605C8;
// extern UNK_TYPE D_004605D0;
// extern UNK_TYPE D_004605E8;
// extern UNK_TYPE D_004605F0;
// extern UNK_TYPE D_004605F8;
// extern UNK_TYPE D_00460600;
// extern UNK_TYPE D_00460608;
// extern UNK_TYPE D_00460610;
// extern UNK_TYPE D_00460630;
// extern UNK_TYPE D_00460690;
// extern UNK_TYPE D_00460698;
// extern UNK_TYPE D_004606A8;
// extern UNK_TYPE D_004606F0;
// extern UNK_TYPE D_00460700;
// extern UNK_TYPE _vt$26RacePositionBonusObjective$13EventListener;
// extern UNK_TYPE _vt$26RacePositionBonusObjective;
// extern UNK_TYPE _vt$24TimeRemainBonusObjective;
// extern UNK_TYPE _vt$19NoCopBonusObjective$13EventListener;
// extern UNK_TYPE _vt$19NoCopBonusObjective;
// extern UNK_TYPE _vt$22NoDamageBonusObjective$13EventListener;
// extern UNK_TYPE _vt$22NoDamageBonusObjective;
// extern UNK_TYPE _vt$20StatePropCollectible$18IHudMapIconLocator;
// extern UNK_TYPE _vt$20StatePropCollectible$18CStatePropListener;
// extern UNK_TYPE _vt$20StatePropCollectible$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$20StatePropCollectible;
// extern UNK_TYPE _vt$14BonusObjective;
// extern UNK_TYPE _vt$12AnimatedIcon;
// extern UNK_TYPE _vt$Q212AnimatedIcon11AnimIconDSG$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$Q212AnimatedIcon11AnimIconDSG;
// extern UNK_TYPE _vt$19MissionScriptLoader;
// extern UNK_TYPE _vt$14MissionManager$Q214LoadingManager23ProcessRequestsCallback;
// extern UNK_TYPE _vt$14MissionManager$Q217PresentationEvent25PresentationEventCallBack;
// extern UNK_TYPE _vt$14MissionManager;
// extern UNK_TYPE _vt$15GameplayManager$Q217PresentationEvent25PresentationEventCallBack;
// extern UNK_TYPE _vt$15GameplayManager;
// extern UNK_TYPE _vt$16BonusMissionInfo;
// extern UNK_TYPE _vt$7Mission;
// extern UNK_TYPE _vt$12MissionStage$Q214LoadingManager23ProcessRequestsCallback;
// extern UNK_TYPE _vt$12MissionStage;
// extern UNK_TYPE D_00460E80;
// extern UNK_TYPE D_00460E90;
// extern UNK_TYPE D_00460EA8;
// extern UNK_TYPE D_00460EB8;
// extern UNK_TYPE D_00460ED0;
// extern UNK_TYPE D_00460EE0;
// extern UNK_TYPE D_00460EF8;
// extern UNK_TYPE D_00460F08;
// extern UNK_TYPE D_00460F20;
// extern UNK_TYPE D_00460F30;
// extern UNK_TYPE D_00460F48;
// extern UNK_TYPE D_00460F68;
// extern UNK_TYPE D_00460F70;
// extern UNK_TYPE D_00460F98;
// extern UNK_TYPE D_00460FC0;
// extern UNK_TYPE D_00460FD8;
// extern UNK_TYPE D_00460FF0;
// extern UNK_TYPE D_00461000;
// extern UNK_TYPE D_00461020;
// extern UNK_TYPE D_00461024;
// extern UNK_TYPE D_00461030;
// extern UNK_TYPE D_00461048;
// extern UNK_TYPE D_00461068;
// extern UNK_TYPE D_00461088;
// extern UNK_TYPE D_004610D0;
// extern UNK_TYPE D_004611F0;
// extern UNK_TYPE D_004612F8;
// extern UNK_TYPE _t13_Alloc_traits2Z9UFOWeaponZt7s2alloc1Z9UFOWeapon$_S_instanceless;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z8tTexture;
// extern UNK_TYPE _vt$Q27Console21ExecuteScriptCallback;
// extern UNK_TYPE D_004614E8;
// extern UNK_TYPE D_004615E0;

#endif
