#ifndef ALLMOVINGPOSN_H
#define ALLMOVINGPOSN_H

// text

// void __18MovingSoundManager();
// void _$_18MovingSoundManager();
// void HandleEvent__18MovingSoundManager9EventEnumPv();
// void ServiceOncePerFrame__18MovingSoundManager();
// void addTrafficSound__18MovingSoundManagerPCcP7Vehicleb();
// void stopTrafficSound__18MovingSoundManagerP7Vehicle();
// void addAISound__18MovingSoundManagerPCcP7Vehicleb();
// void stopAISound__18MovingSoundManagerP7Vehicle();
// void handleTrafficHornEvent__18MovingSoundManagerP7Vehicle();
// void makeCarGoBoom__18MovingSoundManagerP7Vehicle();
// void startPlatformSound__18MovingSoundManagerP13AnimSoundData();
// void stopPlatformSound__18MovingSoundManagerPQ212ActionButton10AnimSwitch();
// void func_00249F28();
// void startAnimObjSound__18MovingSoundManagerP16AnimSoundDSGData();
// void stopAnimObjSound__18MovingSoundManagerP22AnimCollisionEntityDSG();
// void hasOverlayClip__18MovingSoundManagerP7VehiclePP18carSoundParameters();
// void toggleOverlayClip__18MovingSoundManagerP7Vehicle();
// void getPositionalSettingName__18MovingSoundManagerP7Vehicleb();
// void startWaspSound__18MovingSoundManagerP5Actor();
// void __28VehiclePositionalSoundPlayer();
// void _$_28VehiclePositionalSoundPlayer();
// void ActivateByName__28VehiclePositionalSoundPlayerPCcP7Vehicle();
// void Activate__28VehiclePositionalSoundPlayerP23positionalSoundSettingsPCcP7Vehicle();
// void Deactivate__28VehiclePositionalSoundPlayer();
// void GetPosition__28VehiclePositionalSoundPlayerR14radSoundVector();
// void GetVelocity__28VehiclePositionalSoundPlayerR14radSoundVector();
// void ServiceOncePerFrame__28VehiclePositionalSoundPlayer();
// void UsesVehicle__28VehiclePositionalSoundPlayerP7Vehicle();
// void BlowUp__28VehiclePositionalSoundPlayer();
// void __20AIVehicleSoundPlayer();
// void _$_20AIVehicleSoundPlayer();
// void ServiceOncePerFrame__20AIVehicleSoundPlayer();
// void __18TrafficSoundPlayer();
// void _$_18TrafficSoundPlayer();
// void InitializeClass__18TrafficSoundPlayerUi();
// void Activate__18TrafficSoundPlayerP23positionalSoundSettingsPCcP7Vehicle();
// void Deactivate__18TrafficSoundPlayer();
// void ServiceOncePerFrame__18TrafficSoundPlayer();
// void ServiceTimerList__18TrafficSoundPlayer();
// void OnTimerDone__18TrafficSoundPlayerUiPv();
// void HonkHorn__18TrafficSoundPlayer();
// void AddOverlayClip__18TrafficSoundPlayerP18carSoundParametersPCc();
// void ToggleOverlayClip__18TrafficSoundPlayerP18carSoundParametersPCc();
// void __23AvatarVehiclePosnPlayer();
// void _$_23AvatarVehiclePosnPlayer();
// void HandleEvent__23AvatarVehiclePosnPlayer9EventEnumPv();
// void StartPositionalIdle__23AvatarVehiclePosnPlayerP7Vehicle();
// void __11ActorPlayer();
// void _$_11ActorPlayer();
// void GetPosition__11ActorPlayerR14radSoundVector();
// void GetVelocity__11ActorPlayerR14radSoundVector();
// void ServiceOncePerFrame__11ActorPlayer();
// void OnPlaybackComplete__11ActorPlayer();
// void OnSoundReady__11ActorPlayer();
// void playSound__11ActorPlayerP23positionalSoundSettingsPCcP5Actor();
// void deactivate__11ActorPlayer();
// void __15WaspSoundPlayer();
// void _$_15WaspSoundPlayer();
// void Activate__15WaspSoundPlayerP5Actor();
// void HandleEvent__15WaspSoundPlayer9EventEnumPv();
// void OnPlaybackComplete__15WaspSoundPlayer();
// void deactivate__15WaspSoundPlayer();
// void safeStop__15WaspSoundPlayer();
// void playWaspSound__15WaspSoundPlayerPCcP5Actor();
// void __19PlatformSoundPlayer();
// void _$_19PlatformSoundPlayer();
// void Activate__19PlatformSoundPlayerP13AnimSoundData();
// void Deactivate__19PlatformSoundPlayer();
// void ServiceOncePerFrame__19PlatformSoundPlayer();
// void GetPosition__19PlatformSoundPlayerR14radSoundVector();
// void GetVelocity__19PlatformSoundPlayerR14radSoundVector();
// void __18AnimObjSoundPlayer();
// void _$_18AnimObjSoundPlayer();
// void Activate__18AnimObjSoundPlayerP16AnimSoundDSGData();
// void Deactivate__18AnimObjSoundPlayer();
// void ServiceOncePerFrame__18AnimObjSoundPlayer();
// void GetPosition__18AnimObjSoundPlayerR14radSoundVector();
// void GetVelocity__18AnimObjSoundPlayerR14radSoundVector();
// void func_0024BF20();
// void __tf28VehiclePositionalSoundPlayer();
// void __tf18TrafficSoundPlayer();
// void __tf20AIVehicleSoundPlayer();
// void __tf23AvatarVehiclePosnPlayer();
// void __tf11ActorPlayer();
// void __tf15WaspSoundPlayer();
// void __tf19PlatformSoundPlayer();
// void __tf18AnimObjSoundPlayer();
// void __tf18MovingSoundManager();
// void func_0024C290();
// void _GLOBAL_$I$_18MovingSoundManager$s_waspUID();

// data

// extern UNK_TYPE _18MovingSoundManager$s_waspUID;
// extern UNK_TYPE _18TrafficSoundPlayer$s_timerList;
// extern UNK_TYPE D_0043037C;

// rodata

// extern UNK_TYPE D_00478320;
// extern UNK_TYPE D_004783E0;
// extern UNK_TYPE D_004783F0;
// extern UNK_TYPE D_004783F8;
// extern UNK_TYPE D_00478408;
// extern UNK_TYPE D_00478418;
// extern UNK_TYPE D_00478430;
// extern UNK_TYPE D_00478440;
// extern UNK_TYPE D_00478450;
// extern UNK_TYPE D_00478468;
// extern UNK_TYPE D_00478480;
// extern UNK_TYPE D_00478490;
// extern UNK_TYPE jtbl_004784B0;
// extern UNK_TYPE D_004784E0;
// extern UNK_TYPE D_004784F0;
// extern UNK_TYPE D_00478500;
// extern UNK_TYPE D_00478510;
// extern UNK_TYPE D_00478528;
// extern UNK_TYPE D_00478538;
// extern UNK_TYPE D_00478548;
// extern UNK_TYPE D_00478558;
// extern UNK_TYPE D_00478568;
// extern UNK_TYPE D_00478578;
// extern UNK_TYPE D_00478580;
// extern UNK_TYPE D_00478588;
// extern UNK_TYPE D_00478598;
// extern UNK_TYPE D_004785A8;
// extern UNK_TYPE D_004785B8;
// extern UNK_TYPE _vt$18MovingSoundManager;
// extern UNK_TYPE _vt$18AnimObjSoundPlayer;
// extern UNK_TYPE _vt$19PlatformSoundPlayer;
// extern UNK_TYPE _vt$15WaspSoundPlayer$13EventListener;
// extern UNK_TYPE _vt$15WaspSoundPlayer$27SimpsonsSoundPlayerCallback;
// extern UNK_TYPE _vt$15WaspSoundPlayer;
// extern UNK_TYPE _vt$11ActorPlayer$27SimpsonsSoundPlayerCallback;
// extern UNK_TYPE _vt$11ActorPlayer;
// extern UNK_TYPE _vt$23AvatarVehiclePosnPlayer$13EventListener;
// extern UNK_TYPE _vt$23AvatarVehiclePosnPlayer;
// extern UNK_TYPE _vt$20AIVehicleSoundPlayer;
// extern UNK_TYPE _vt$18TrafficSoundPlayer$17IRadTimerCallback;
// extern UNK_TYPE _vt$18TrafficSoundPlayer;
// extern UNK_TYPE _vt$28VehiclePositionalSoundPlayer;
// extern UNK_TYPE D_00478850;
// extern UNK_TYPE D_00478870;
// extern UNK_TYPE D_00478888;
// extern UNK_TYPE D_00478898;
// extern UNK_TYPE D_004788B0;
// extern UNK_TYPE D_004788D0;
// extern UNK_TYPE D_004788E0;
// extern UNK_TYPE D_004788F0;
// extern UNK_TYPE D_00478900;
// extern UNK_TYPE D_00478918;
// extern UNK_TYPE D_00478928;
// extern UNK_TYPE D_00478940;
// extern UNK_TYPE D_00478958;

#endif
