#ifndef ALLMETA_H
#define ALLMETA_H

// text

// void PrepareString__FPPcPUcUi();
// void SetString__FPPcUiPCc();
// void __18ActionEventLocator();
// void _$_18ActionEventLocator();
// void SetObjNameSize__18ActionEventLocatorUc();
// void SetObjName__18ActionEventLocatorPCc();
// void SetJointNameSize__18ActionEventLocatorUc();
// void SetJointName__18ActionEventLocatorPCc();
// void SetActionNameSize__18ActionEventLocatorUc();
// void SetActionName__18ActionEventLocatorPCc();
// void AddToGame__18ActionEventLocatorP12tEntityStore();
// void Reset__18ActionEventLocator();
// void OnTrigger__18ActionEventLocatorUi();
// void __15CarStartLocator();
// void _$_15CarStartLocator();
// void __18DirectionalLocator();
// void _$_18DirectionalLocator();
// void __12EventLocator();
// void _$_12EventLocator();
// void OnTrigger__12EventLocatorUi();
// void __10FOVLocator();
// void _$_10FOVLocator();
// void RegisterDebugData__10FOVLocator();
// void UnRegisterDebugData__10FOVLocator();
// void OnTrigger__10FOVLocatorUi();
// void __23InteriorEntranceLocator();
// void _$_23InteriorEntranceLocator();
// void SetInteriorFileName__23InteriorEntranceLocatorPCc();
// void SetInteriorFileNameSize__23InteriorEntranceLocatorUi();
// void OnTrigger__23InteriorEntranceLocatorUi();
// void __7Locator();
// void _$_7Locator();
// void GetPosition__7LocatorPQ218RadicalMathLibrary6Vector();
// void GetHeading__7LocatorPQ218RadicalMathLibrary6Vector();
// void __16OcclusionLocator();
// void _$_16OcclusionLocator();
// void OnTrigger__16OcclusionLocatorUi();
// void __17RectTriggerVolumeRCQ218RadicalMathLibrary6VectorN31fff();
// void _$_17RectTriggerVolume();
// void Contains__C17RectTriggerVolumeRCQ218RadicalMathLibrary6Vectorf();
// void IntersectsBox__C17RectTriggerVolumeRCQ218RadicalMathLibrary6VectorN31();
// void IntersectsBox__17RectTriggerVolumeRCQ218RadicalMathLibrary5Box3D();
// void IntersectsSphere__C17RectTriggerVolumeRCQ218RadicalMathLibrary6Vectorf();
// void IntersectLine__C17RectTriggerVolumeRCQ218RadicalMathLibrary6VectorT1();
// void GetBoundingBox__C17RectTriggerVolumeRQ218RadicalMathLibrary6VectorT1();
// void GetType__C17RectTriggerVolume();
// void GetBoundingBox__17RectTriggerVolumePQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__17RectTriggerVolumePQ218RadicalMathLibrary6Sphere();
// void SetTransform__17RectTriggerVolumeRQ218RadicalMathLibrary6Matrix();
// void UpdateW2T__17RectTriggerVolume();
// void InitPoints__17RectTriggerVolume();
// void CalcPoints__17RectTriggerVolume();
// void func_0016A178();
// void __13ScriptLocator();
// void _$_13ScriptLocator();
// void OnTrigger__13ScriptLocatorUi();
// void __19SphereTriggerVolume();
// void __19SphereTriggerVolumeRCQ218RadicalMathLibrary6Vectorf();
// void _$_19SphereTriggerVolume();
// void Contains__C19SphereTriggerVolumeRCQ218RadicalMathLibrary6Vectorf();
// void IntersectsBox__C19SphereTriggerVolumeRCQ218RadicalMathLibrary6VectorN31();
// void IntersectsBox__19SphereTriggerVolumeRCQ218RadicalMathLibrary5Box3D();
// void IntersectLine__C19SphereTriggerVolumeRCQ218RadicalMathLibrary6VectorT1();
// void IntersectsSphere__C19SphereTriggerVolumeRCQ218RadicalMathLibrary6Vectorf();
// void GetBoundingBox__C19SphereTriggerVolumeRQ218RadicalMathLibrary6VectorT1();
// void GetType__C19SphereTriggerVolume();
// void GetBoundingBox__19SphereTriggerVolumePQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__19SphereTriggerVolumePQ218RadicalMathLibrary6Sphere();
// void IntersectLineSphere__C19SphereTriggerVolumeRCQ218RadicalMathLibrary6VectorT1();
// void InitPoints__19SphereTriggerVolume();
// void CalcPoints__19SphereTriggerVolume();
// void __13SplineLocator();
// void _$_13SplineLocator();
// void SetRailCam__13SplineLocatorP7RailCam();
// void TriggerAllowed__13SplineLocatori();
// void OnTrigger__13SplineLocatorUi();
// void __14TriggerLocator();
// void _$_14TriggerLocator();
// void SetNumTriggers__14TriggerLocatorUii();
// void AddTriggerVolume__14TriggerLocatorP13TriggerVolume();
// void GetTriggerVolume__14TriggerLocatorUi();
// void IsPlayerTracked__C14TriggerLocatori();
// void __13TriggerVolume();
// void _$_13TriggerVolume();
// void Trigger__13TriggerVolumeUib();
// void SetLocator__13TriggerVolumeP14TriggerLocator();
// void Render__13TriggerVolume();
// void GetBoundingBox__13TriggerVolumePQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__13TriggerVolumePQ218RadicalMathLibrary6Sphere();
// void Display__13TriggerVolume();
// void TriggerAllowed__13TriggerVolumei();
// void ClearPoints__13TriggerVolume();
// void CreateInstance__20TriggerVolumeTracker();
// void GetInstance__20TriggerVolumeTracker();
// void DestroyInstance__20TriggerVolumeTracker();
// void __20TriggerVolumeTracker();
// void _$_20TriggerVolumeTracker();
// void Cleanup__20TriggerVolumeTracker();
// void Update__20TriggerVolumeTrackeri();
// void AddTrigger__20TriggerVolumeTrackerP13TriggerVolume();
// void RemoveTrigger__20TriggerVolumeTrackerP13TriggerVolume();
// void func_0016BA30();
// void HandleEvent__20TriggerVolumeTracker9EventEnumPv();
// void Render__20TriggerVolumeTracker();
// void RegisterAI__20TriggerVolumeTrackerP7Vehiclei();
// void UnregisterAI__20TriggerVolumeTrackerP7Vehicle();
// void GetAI__20TriggerVolumeTrackeri();
// void AddActive__20TriggerVolumeTrackeriP13TriggerVolume();
// void CheckForActiveVolumes__20TriggerVolumeTrackeriRQ218RadicalMathLibrary6Vectorf();
// void RemoveActive__20TriggerVolumeTrackerii();
// void AddAIActive__20TriggerVolumeTrackeriP13TriggerVolume();
// void RemoveAIActive__20TriggerVolumeTrackerii();
// void TestVolume__20TriggerVolumeTrackerP13TriggerVolumeRQ218RadicalMathLibrary6VectorfiUi();
// void __16ZoneEventLocator();
// void _$_16ZoneEventLocator();
// void GetNumLoadZones__16ZoneEventLocator();
// void GetNumDumpZones__16ZoneEventLocator();
// void GetNumLWSActivates__16ZoneEventLocator();
// void GetNumLWSDeactivates__16ZoneEventLocator();
// void GetLoadZone__16ZoneEventLocatori();
// void GetDumpZone__16ZoneEventLocatori();
// void GetLWSActivates__16ZoneEventLocatori();
// void GetLWSDeactivates__16ZoneEventLocatori();
// void GetInteriorSection__16ZoneEventLocator();
// void SetZone__16ZoneEventLocatorPCc();
// void SetZoneSize__16ZoneEventLocatorUc();
// void __16StaticCamLocator();
// void _$_16StaticCamLocator();
// void SetStaticCam__16StaticCamLocatorP9StaticCam();
// void TriggerAllowed__16StaticCamLocatori();
// void OnTrigger__16StaticCamLocatorUi();
// void func_0016D378();
// void func_0016D380();
// void func_0016D3B8();
// void __tf7Locator();
// void __tf14TriggerLocator();
// void __tf18ActionEventLocator();
// void __tf15CarStartLocator();
// void __tf18DirectionalLocator();
// void __tf12EventLocator();
// void __tf10FOVLocator();
// void __tf23InteriorEntranceLocator();
// void __tf16OcclusionLocator();
// void __tf13TriggerVolume();
// void __tf17RectTriggerVolume();
// void __tf13ScriptLocator();
// void __tf19SphereTriggerVolume();
// void __tf13SplineLocator();
// void __tf20TriggerVolumeTracker();
// void __tf16ZoneEventLocator();
// void __tf16StaticCamLocator();
// void func_0016D9A0();
// void SetNumTriggers__7LocatorUii();
// void GetNumTriggers__7Locator();
// void SetMatrix__7LocatorRCQ218RadicalMathLibrary6Matrix();
// void TriggerAllowed__7Locatori();
// void func_0016D9D0();
// void GetDataType__C7Locator();
// void OnTrigger__14TriggerLocatorUi();
// void GetNumTriggers__14TriggerLocator();
// void func_0016D9F0();
// void GetDataType__C18ActionEventLocator();
// void SetMatrix__18ActionEventLocatorRCQ218RadicalMathLibrary6Matrix();
// void GetDataType__C15CarStartLocator();
// void GetDataType__C18DirectionalLocator();
// void GetDataType__C12EventLocator();
// void SetMatrix__12EventLocatorRCQ218RadicalMathLibrary6Matrix();
// void GetDataType__C10FOVLocator();
// void GetDataType__C23InteriorEntranceLocator();
// void GetDataType__C16OcclusionLocator();
// void func_0016DB40();
// void pPosition__13TriggerVolume();
// void rPosition__13TriggerVolume();
// void GetPosition__13TriggerVolumePQ218RadicalMathLibrary6Vector();
// void func_0016DB78();
// void GetDataType__C13ScriptLocator();
// void GetDataType__C13SplineLocator();
// void func_0016DB90();
// void GetDataType__C16ZoneEventLocator();
// void GetDataType__C16StaticCamLocator();
// void func_0016DBA8();
// void __tfQ216radLoadInventoryt8SafeCast1Z13TriggerVolume();
// void func_0016DC08();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z13TriggerVolumeP9IRefCount();
// void func_0016DC68();
// void _GLOBAL_$I$PrepareString__FPPcPUcUi();

// data

// extern UNK_TYPE D_0042C420;
// extern UNK_TYPE D_0042C43C;
// extern UNK_TYPE ALLOWED_AI_EVENTS;
// extern UNK_TYPE NUM_ALLOWED_AI_EVENTS;
// extern UNK_TYPE _20TriggerVolumeTracker$spInstance;
// extern UNK_TYPE _20TriggerVolumeTracker$sP1;
// extern UNK_TYPE D_0042C464;
// extern UNK_TYPE _20TriggerVolumeTracker$sP2;
// extern UNK_TYPE D_0042C474;
// extern UNK_TYPE _20TriggerVolumeTracker$sP3;
// extern UNK_TYPE D_0042C484;
// extern UNK_TYPE _20TriggerVolumeTracker$sP4;

// bss

// extern UNK_TYPE D_004B1AD8;

// rodata

// extern UNK_TYPE D_0045E000;
// extern UNK_TYPE D_0045E018;
// extern UNK_TYPE D_0045E028;
// extern UNK_TYPE D_0045E030;
// extern UNK_TYPE D_0045E038;
// extern UNK_TYPE D_0045E048;
// extern UNK_TYPE D_0045E058;
// extern UNK_TYPE D_0045E068;
// extern UNK_TYPE jtbl_0045E0B0;
// extern UNK_TYPE D_0045E1B8;
// extern UNK_TYPE MIN_SPEED_FOR_CAM_TRIGGER;
// extern UNK_TYPE _vt$16StaticCamLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$16StaticCamLocator;
// extern UNK_TYPE _vt$16ZoneEventLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$16ZoneEventLocator;
// extern UNK_TYPE _vt$20TriggerVolumeTracker;
// extern UNK_TYPE _vt$13SplineLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$13SplineLocator;
// extern UNK_TYPE _vt$19SphereTriggerVolume$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$19SphereTriggerVolume;
// extern UNK_TYPE _vt$13ScriptLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$13ScriptLocator;
// extern UNK_TYPE _vt$17RectTriggerVolume$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$17RectTriggerVolume;
// extern UNK_TYPE _vt$13TriggerVolume$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$13TriggerVolume;
// extern UNK_TYPE _vt$16OcclusionLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$16OcclusionLocator;
// extern UNK_TYPE _vt$23InteriorEntranceLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$23InteriorEntranceLocator;
// extern UNK_TYPE _vt$10FOVLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$10FOVLocator;
// extern UNK_TYPE _vt$12EventLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$12EventLocator;
// extern UNK_TYPE _vt$18DirectionalLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$18DirectionalLocator;
// extern UNK_TYPE _vt$15CarStartLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$15CarStartLocator;
// extern UNK_TYPE _vt$18ActionEventLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$18ActionEventLocator;
// extern UNK_TYPE _vt$14TriggerLocator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$14TriggerLocator;
// extern UNK_TYPE _vt$7Locator$18IHudMapIconLocator;
// extern UNK_TYPE _vt$7Locator;
// extern UNK_TYPE D_0045EB00;
// extern UNK_TYPE D_0045EB18;
// extern UNK_TYPE D_0045EB28;
// extern UNK_TYPE D_0045EB38;
// extern UNK_TYPE D_0045EB50;
// extern UNK_TYPE D_0045EB58;
// extern UNK_TYPE D_0045EB70;
// extern UNK_TYPE D_0045EB78;
// extern UNK_TYPE D_0045EB90;
// extern UNK_TYPE D_0045EBA8;
// extern UNK_TYPE D_0045EBB8;
// extern UNK_TYPE D_0045EBC8;
// extern UNK_TYPE D_0045EBE8;
// extern UNK_TYPE D_0045EBF0;
// extern UNK_TYPE D_0045EC08;
// extern UNK_TYPE D_0045EC18;
// extern UNK_TYPE D_0045EC20;
// extern UNK_TYPE D_0045EC38;
// extern UNK_TYPE D_0045EC40;
// extern UNK_TYPE D_0045EC50;
// extern UNK_TYPE D_0045EC68;
// extern UNK_TYPE D_0045EC78;
// extern UNK_TYPE D_0045EC90;
// extern UNK_TYPE D_0045ECA8;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z13TriggerVolume;
// extern UNK_TYPE D_0045ED18;

#endif
