#ifndef ALLOBJECTIVES_HPP
#define ALLOBJECTIVES_HPP

// text

// void __17DeliveryObjective();
// void _$_17DeliveryObjective();
// void HandleEvent__17DeliveryObjective9EventEnumPv();
// void OnInitCollectibles__17DeliveryObjective();
// void OnInitCollectibleObjective__17DeliveryObjective();
// void OnFinalizeCollectibleObjective__17DeliveryObjective();
// void OnCollection__17DeliveryObjectiveUiRb();
// void OnUpdateCollectibleObjective__17DeliveryObjectiveUi();
// void FindStateProps__17DeliveryObjective();
// void ReleaseAllStateProps__17DeliveryObjective();
// void SetButtonHandlersEnabled__17DeliveryObjectiveb();
// void SetStatePropState__17DeliveryObjectivei();
// void SetStatePropHUDIconEnable__17DeliveryObjectiveb();
// void __16DestroyObjective();
// void _$_16DestroyObjective();
// void OnInitialize__16DestroyObjective();
// void OnFinalize__16DestroyObjective();
// void OnUpdate__16DestroyObjectiveUi();
// void HandleEvent__16DestroyObjective9EventEnumPv();
// void SetTargetVehicle__16DestroyObjectiveP7Vehicle();
// void __20DestroyBossObjective();
// void _$_20DestroyBossObjective();
// void SetTarget__20DestroyBossObjectiveP5Actor();
// void OnInitialize__20DestroyBossObjective();
// void OnFinalize__20DestroyBossObjective();
// void OnUpdate__20DestroyBossObjectiveUi();
// void HandleEvent__20DestroyBossObjective9EventEnumPv();
// void __17DialogueObjective();
// void _$_17DialogueObjective();
// void HandleEvent__17DialogueObjective9EventEnumPv();
// void SetPositions__17DialogueObjectiveP15CarStartLocatorN21b();
// void CharactersReset__17DialogueObjective();
// void SetChar1Name__17DialogueObjectivePCc();
// void SetChar2Name__17DialogueObjectivePCc();
// void SetDialogueName__17DialogueObjectivePCc();
// void OnInitialize__17DialogueObjective();
// void OnFinalize__17DialogueObjective();
// void ResetCharacterPositions__17DialogueObjective();
// void __15FollowObjective();
// void _$_15FollowObjective();
// void OnInitialize__15FollowObjective();
// void OnFinalize__15FollowObjective();
// void OnUpdate__15FollowObjectiveUi();
// void HandleEvent__15FollowObjective9EventEnumPv();
// void __14GetInObjective();
// void _$_14GetInObjective();
// void OnInitialize__14GetInObjective();
// void OnFinalize__14GetInObjective();
// void OnUpdate__14GetInObjectiveUi();
// void SetStrict__14GetInObjectivePCc();
// void GetPosition__14GetInObjectivePQ218RadicalMathLibrary6Vector();
// void GetHeading__14GetInObjectivePQ218RadicalMathLibrary6Vector();
// void __13GoToObjective();
// void _$_13GoToObjective();
// void OnInitialize__13GoToObjective();
// void OnFinalize__13GoToObjective();
// void OnUpdate__13GoToObjectiveUi();
// void HandleEvent__13GoToObjective9EventEnumPv();
// void SetDestinationNames__13GoToObjectivePcT1f();
// void SetCollectEffectName__13GoToObjectivePc();
// void __13LoseObjective();
// void _$_13LoseObjective();
// void OnInitialize__13LoseObjective();
// void OnFinalize__13LoseObjective();
// void OnUpdate__13LoseObjectiveUi();
// void __16MissionObjective();
// void _$_16MissionObjective();
// void AddNPCWaypoint__16MissionObjectivePCcT1();
// void Initialize__16MissionObjective();
// void Finalize__16MissionObjective();
// void Update__16MissionObjectiveUi();
// void HandleEvent__16MissionObjective9EventEnumPv();
// void AddNPC__16MissionObjectivePCcT1b();
// void RemoveNPC__16MissionObjectivePCcb();
// void RegisterLocator__16MissionObjectiveP7LocatorRibQ210HudMapIcon9eIconType();
// void RegisterPosition__16MissionObjectiveRCQ218RadicalMathLibrary6VectorRibQ210HudMapIcon9eIconTypeP18IHudMapIconLocator();
// void UnregisterLocator__16MissionObjectiveRi();
// void UnregisterPosition__16MissionObjectiveRi();
// void func_001913E0();
// void GetObjectiveType__C16MissionObjective();
// void SetObjectiveType__16MissionObjectiveQ216MissionObjective17ObjectiveTypeEnum();
// void UnlightPath__16MissionObjectiveRt9SwapArray1ZQ211RoadManager11PathElement();
// void func_001915B0();
// void UnlightCurrentPath__16MissionObjectiveRt9SwapArray1ZQ211RoadManager11PathElement();
// void LightPathRightWay__16MissionObjectiveRt9SwapArray1ZQ211RoadManager11PathElementii();
// void LightPathWrongWay__16MissionObjectiveRt9SwapArray1ZQ211RoadManager11PathElementii();
// void UpdateLightPath__16MissionObjectiveRQ216MissionObjective10PathStruct();
// void FindIntersectionInPath__16MissionObjectiveRt9SwapArray1ZQ211RoadManager11PathElementP12Intersection();
// void FindRoadInPath__16MissionObjectiveRt9SwapArray1ZQ211RoadManager11PathElementP4Road();
// void UpdateGroundHeights__16MissionObjectiveRt9SwapArray1ZQ211RoadManager11PathElement();
// void UpdateLongRoadArrows__16MissionObjectiveRQ216MissionObjective10PathStruct();
// void func_00192390();
// void LightPath__16MissionObjectiveRQ218RadicalMathLibrary6VectorRQ216MissionObjective10PathStruct();
// void GetHeadingAlongPath__16MissionObjectiveRt9SwapArray1ZQ211RoadManager11PathElementiP11RoadSegmentRQ218RadicalMathLibrary6Vector();
// void UpdateAnimPosition__16MissionObjectiveP13AnimEntityDSGRQ218RadicalMathLibrary6Vector();
// void IsPattyAndSelmaDialog__C16MissionObjective();
// void IsRaceDialog__C16MissionObjective();
// void __13RaceObjective();
// void _$_13RaceObjective();
// void OnInitialize__13RaceObjective();
// void OnInitCollectibles__13RaceObjective();
// void OnInitCollectibleObjective__13RaceObjective();
// void OnFinalizeCollectibleObjective__13RaceObjective();
// void OnCollection__13RaceObjectiveUiRb();
// void OnUpdateCollectibleObjective__13RaceObjectiveUi();
// void QueryIsGambleRace__13RaceObjective();
// void SetGambleRace__13RaceObjectiveb();
// void SetParTime__13RaceObjectivei();
// void GetParTime__13RaceObjective();
// void CalculatePosition__13RaceObjective();
// void __15TalkToObjective();
// void _$_15TalkToObjective();
// void SetTalkToTarget__15TalkToObjectivePCcQ215TalkToObjective8IconTypeff();
// void GetPosition__15TalkToObjectivePQ218RadicalMathLibrary6Vector();
// void GetHeading__15TalkToObjectivePQ218RadicalMathLibrary6Vector();
// void OnInitialize__15TalkToObjective();
// void OnFinalize__15TalkToObjective();
// void HandleEvent__15TalkToObjective9EventEnumPv();
// void OnUpdate__15TalkToObjectiveUi();
// void __20CollectibleObjective();
// void _$_20CollectibleObjective();
// void MoveCollectible__20CollectibleObjectiveUiRCQ218RadicalMathLibrary6Vector();
// void AddCollectibleLocatorName__20CollectibleObjectivePcT1UiG13tUidUnalignedf();
// void SetCollectEffectName__20CollectibleObjectivePc();
// void HandleEvent__20CollectibleObjective9EventEnumPv();
// void OnUpdate__20CollectibleObjectiveUi();
// void OnInitialize__20CollectibleObjective();
// void GetCollectiblePathInfo__20CollectibleObjectiveUiRQ211RoadManager11PathElementRf();
// void OnFinalize__20CollectibleObjective();
// void CheckCollectibleLocators__20CollectibleObjectiveP7Locator();
// void Collect__20CollectibleObjectiveUib();
// void Activate__20CollectibleObjectiveUibT2Q210HudMapIcon9eIconTypeT2();
// void SetFocus__20CollectibleObjectiveUi();
// void func_001960B0();
// void ResetCollectibles__20CollectibleObjective();
// void DumpCollectible__20CollectibleObjectiveiP7VehicleT2bT4();
// void GetAnyCollectedID__C20CollectibleObjective();
// void Uncollect__20CollectibleObjectivei();
// void __22CollectDumpedObjective();
// void _$_22CollectDumpedObjective();
// void BindCollectibleToWaypoint__22CollectDumpedObjectiveiUi();
// void SetDumpVehicle__22CollectDumpedObjectiveP7Vehicle();
// void HandleEvent__22CollectDumpedObjective9EventEnumPv();
// void OnInitCollectibles__22CollectDumpedObjective();
// void OnInitCollectibleObjective__22CollectDumpedObjective();
// void OnFinalizeCollectibleObjective__22CollectDumpedObjective();
// void OnCollection__22CollectDumpedObjectiveUiRb();
// void OnUpdateCollectibleObjective__22CollectDumpedObjectiveUi();
// void FindFreeSlot__22CollectDumpedObjective();
// void __12FMVObjective();
// void _$_12FMVObjective();
// void OnPresentationEventEnd__12FMVObjectiveP17PresentationEvent();
// void OnInitialize__12FMVObjective();
// void SetFileName__12FMVObjectivePCc();
// void __17InteriorObjective();
// void _$_17InteriorObjective();
// void OnInitialize__17InteriorObjective();
// void OnFinalize__17InteriorObjective();
// void OnUpdate__17InteriorObjectiveUi();
// void HandleEvent__17InteriorObjective9EventEnumPv();
// void GetPosition__17InteriorObjectivePQ218RadicalMathLibrary6Vector();
// void GetHeading__17InteriorObjectivePQ218RadicalMathLibrary6Vector();
// void SetDestination__17InteriorObjectivePCc();
// void SetIcon__17InteriorObjectivePCc();
// void __13CoinObjective();
// void _$_13CoinObjective();
// void HandleEvent__13CoinObjective9EventEnumPv();
// void OnInitialize__13CoinObjective();
// void OnFinalize__13CoinObjective();
// void Update__13CoinObjectiveUi();
// void OnUpdate__13CoinObjectiveUi();
// void func_00197E30();
// void SetCoinFee__13CoinObjectivei();
// void GetCoinAmount__13CoinObjective();
// void __20LoadVehicleObjective();
// void _$_20LoadVehicleObjective();
// void OnInitialize__20LoadVehicleObjective();
// void OnFinalize__20LoadVehicleObjective();
// void OnProcessRequestsComplete__Q220LoadVehicleObjective30LoadDisposableCarAsyncCallbackPv();
// void __19PickupItemObjective();
// void _$_19PickupItemObjective();
// void SetTarget__19PickupItemObjectivePCc();
// void OnInitialize__19PickupItemObjective();
// void OnFinalize__19PickupItemObjective();
// void OnUpdate__19PickupItemObjectiveUi();
// void HandleEvent__19PickupItemObjective9EventEnumPv();
// void MoveObjectToStartPosition__19PickupItemObjective();
// void __14TimerObjective();
// void _$_14TimerObjective();
// void SetTimer__14TimerObjectiveUi();
// void OnInitialize__14TimerObjective();
// void OnFinalize__14TimerObjective();
// void Update__14TimerObjectiveUi();
// void OnUpdate__14TimerObjectiveUi();
// void __15BuyCarObjective();
// void _$_15BuyCarObjective();
// void SetVehicleName__15BuyCarObjectivePCc();
// void OnUpdate__15BuyCarObjectiveUi();
// void __16BuySkinObjective();
// void _$_16BuySkinObjective();
// void SetSkinName__16BuySkinObjectivePCc();
// void OnUpdate__16BuySkinObjectiveUi();
// void __18GoOutsideObjective();
// void _$_18GoOutsideObjective();
// void OnInitialize__18GoOutsideObjective();
// void func_00198E50();
// void func_00198E60();
// void __tf16MissionObjective();
// void __tf20CollectibleObjective();
// void __tf17DeliveryObjective();
// void __tf16DestroyObjective();
// void __tf20DestroyBossObjective();
// void func_00199068();
// void __tf17DialogueObjective();
// void __tf15FollowObjective();
// void __tf14GetInObjective();
// void __tf13GoToObjective();
// void __tf13LoseObjective();
// void __tf13RaceObjective();
// void __tf15TalkToObjective();
// void __tf22CollectDumpedObjective();
// void __tf19CollectionCondition();
// void __tf12FMVObjective();
// void __tf17InteriorObjective();
// void __tf13CoinObjective();
// void __tfQ220LoadVehicleObjective30LoadDisposableCarAsyncCallback();
// void __tf20LoadVehicleObjective();
// void __tf19PickupItemObjective();
// void __tf14TimerObjective();
// void __tf15BuyCarObjective();
// void __tf16BuySkinObjective();
// void __tf18GoOutsideObjective();
// void func_00199718();
// void _$_Q216MissionObjective10PathStruct();
// void _$_Q216MissionObjective9NPCStruct();
// void func_001997F8();
// void OnInitialize__16MissionObjective();
// void OnFinalize__16MissionObjective();
// void OnUpdate__16MissionObjectiveUi();
// void _$_Q220CollectibleObjective22CollectibleLocatorData();
// void OnUpdateCollectibleObjective__20CollectibleObjectiveUi();
// void func_00199870();
// void __Q216radLoadInventoryt8SafeCast1Z16ZoneEventLocator();
// void _$_19CollectionCondition();
// void Update__19CollectionConditionUi();
// void IsClose__19CollectionCondition();
// void func_00199930();
// void OnFinalize__12FMVObjective();
// void OnPresentationEventBegin__12FMVObjectiveP17PresentationEvent();
// void OnPresentationEventLoadComplete__12FMVObjectiveP17PresentationEvent();
// void func_00199950();
// void __Q216radLoadInventoryt8SafeCast1Z20StatePropCollectible();
// void func_001999A8();
// void __tfQ216radLoadInventoryt8SafeCast1Z16ZoneEventLocator();
// void __tfQ216radLoadInventoryt8SafeCast1Z20StatePropCollectible();
// void func_00199A98();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z20StatePropCollectibleP9IRefCount();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z16ZoneEventLocatorP9IRefCount();
// void func_00199B40();
// void _GLOBAL_$I$__17DeliveryObjective();

// rodata

// extern UNK_TYPE D_00461F10;
// extern UNK_TYPE D_00461F40;
// extern UNK_TYPE D_00461F50;
// extern UNK_TYPE D_00461F60;
// extern UNK_TYPE D_00461F70;
// extern UNK_TYPE D_00461F80;
// extern UNK_TYPE D_00461F90;
// extern UNK_TYPE D_00461FA0;
// extern UNK_TYPE D_00461FD0;
// extern UNK_TYPE D_00461FE0;
// extern UNK_TYPE D_00461FE8;
// extern UNK_TYPE D_00461FF0;
// extern UNK_TYPE D_00462000;
// extern UNK_TYPE D_00462010;
// extern UNK_TYPE D_00462020;
// extern UNK_TYPE D_00462030;
// extern UNK_TYPE D_00462038;
// extern UNK_TYPE D_00462048;
// extern UNK_TYPE D_00462050;
// extern UNK_TYPE D_00462058;
// extern UNK_TYPE D_00462060;
// extern UNK_TYPE D_00462068;
// extern UNK_TYPE D_00462070;
// extern UNK_TYPE D_00462078;
// extern UNK_TYPE D_00462080;
// extern UNK_TYPE D_00462088;
// extern UNK_TYPE D_00462098;
// extern UNK_TYPE D_004620A0;
// extern UNK_TYPE D_004620A8;
// extern UNK_TYPE D_00462178;
// extern UNK_TYPE D_00462188;
// extern UNK_TYPE D_00462198;
// extern UNK_TYPE D_004621A8;
// extern UNK_TYPE D_004621B8;
// extern UNK_TYPE _vt$18GoOutsideObjective;
// extern UNK_TYPE _vt$16BuySkinObjective;
// extern UNK_TYPE _vt$15BuyCarObjective;
// extern UNK_TYPE _vt$14TimerObjective;
// extern UNK_TYPE _vt$19PickupItemObjective;
// extern UNK_TYPE _vt$20LoadVehicleObjective;
// extern UNK_TYPE _vt$Q220LoadVehicleObjective30LoadDisposableCarAsyncCallback;
// extern UNK_TYPE _vt$13CoinObjective;
// extern UNK_TYPE _vt$17InteriorObjective$18IHudMapIconLocator;
// extern UNK_TYPE _vt$17InteriorObjective;
// extern UNK_TYPE _vt$12FMVObjective$Q217PresentationEvent25PresentationEventCallBack;
// extern UNK_TYPE _vt$12FMVObjective;
// extern UNK_TYPE _vt$19CollectionCondition;
// extern UNK_TYPE _vt$22CollectDumpedObjective;
// extern UNK_TYPE _vt$15TalkToObjective$18IHudMapIconLocator;
// extern UNK_TYPE _vt$15TalkToObjective;
// extern UNK_TYPE _vt$13RaceObjective;
// extern UNK_TYPE _vt$13LoseObjective;
// extern UNK_TYPE _vt$13GoToObjective;
// extern UNK_TYPE _vt$14GetInObjective$18IHudMapIconLocator;
// extern UNK_TYPE _vt$14GetInObjective;
// extern UNK_TYPE _vt$15FollowObjective;
// extern UNK_TYPE _vt$17DialogueObjective;
// extern UNK_TYPE _vt$20DestroyBossObjective;
// extern UNK_TYPE _vt$16DestroyObjective;
// extern UNK_TYPE _vt$17DeliveryObjective;
// extern UNK_TYPE _vt$20CollectibleObjective;
// extern UNK_TYPE _vt$16MissionObjective;
// extern UNK_TYPE D_004628B0;
// extern UNK_TYPE D_004628C8;
// extern UNK_TYPE D_004628E0;
// extern UNK_TYPE D_004628F8;
// extern UNK_TYPE D_00462910;
// extern UNK_TYPE D_00462940;
// extern UNK_TYPE D_00462958;
// extern UNK_TYPE D_00462970;
// extern UNK_TYPE D_00462988;
// extern UNK_TYPE D_00462998;
// extern UNK_TYPE D_004629A8;
// extern UNK_TYPE D_004629B8;
// extern UNK_TYPE D_004629C8;
// extern UNK_TYPE D_004629E0;
// extern UNK_TYPE D_00462A00;
// extern UNK_TYPE D_00462A18;
// extern UNK_TYPE D_00462A28;
// extern UNK_TYPE D_00462A38;
// extern UNK_TYPE D_00462A50;
// extern UNK_TYPE D_00462A60;
// extern UNK_TYPE D_00462AA0;
// extern UNK_TYPE D_00462AB8;
// extern UNK_TYPE D_00462AD0;
// extern UNK_TYPE D_00462AE8;
// extern UNK_TYPE D_00462B00;
// extern UNK_TYPE D_00462B18;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z20StatePropCollectible;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z16ZoneEventLocator;
// extern UNK_TYPE D_00462D80;
// extern UNK_TYPE D_00462DB8;

// data

// extern UNK_TYPE D_0042C514;
// extern UNK_TYPE D_0042C538;
// extern UNK_TYPE D_0042C53C;
// extern UNK_TYPE D_0042C540;
// extern UNK_TYPE D_0042C544;
// extern UNK_TYPE D_0042C548;

// bss

// extern UNK_TYPE D_004B1B50;
// extern UNK_TYPE D_004B1B58;
// extern UNK_TYPE D_004B1B60;
// extern UNK_TYPE D_004B1B68;

#endif
