#ifndef ALLREDBRICK_HPP
#define ALLREDBRICK_HPP

// text

// void __15GeometryVehicle();
// void _$_15GeometryVehicle();
// void Init__15GeometryVehiclePCcP7Vehiclei();
// void InitSkidMarks__15GeometryVehicle();
// void InitParticles__15GeometryVehicle();
// void GetHeadlightScale__15GeometryVehicle();
// void SetHeadlightScale__15GeometryVehiclef();
// void AttachCollectible__15GeometryVehicleP20StatePropCollectible();
// void GetAttachedCollectible__15GeometryVehicle();
// void DetachCollectible__15GeometryVehicleRCQ218RadicalMathLibrary6Vectorb();
// void Display__15GeometryVehicle();
// void SetSkidValues__15GeometryVehicleifRQ218RadicalMathLibrary6Vector12eTerrainType();
// void UpdateSkids__15GeometryVehicle();
// void DisplayShadow__15GeometryVehicleP16BlobShadowParams();
// void func_00276688();
// void FindAndTurnOffWheels__15GeometryVehicle();
// void FindAndTurnOffFrontWheelsOnly__15GeometryVehicle();
// void FindHeadLightBillboardJoints__15GeometryVehicle();
// void FindBrakeLightBillboardJoints__15GeometryVehicle();
// void FindGhostGlowBillboards__15GeometryVehiclePCc();
// void FindNukeGlowBillboards__15GeometryVehiclePCc();
// void SetCollectibleHardpointPosition__15GeometryVehicleRCQ218RadicalMathLibrary6Vector();
// void SetCollectibleHardpointTransform__15GeometryVehiclefffRCQ218RadicalMathLibrary6Vector();
// void ShowBrakeLights__15GeometryVehicle();
// void HideBrakeLights__15GeometryVehicle();
// void ShowReverseLights__15GeometryVehicle();
// void HideReverseLights__15GeometryVehicle();
// void GetArt__15GeometryVehiclePCc();
// void FindDamageShadersAndTextures__15GeometryVehiclePCc();
// void SetEngineSmoke__15GeometryVehicleQ212ParticleEnum10ParticleID();
// void SetWheelSmoke__15GeometryVehicleiQ212ParticleEnum10ParticleIDf();
// void DamageTextureTrunk__15GeometryVehicleb();
// void DamageTextureHood__15GeometryVehicleb();
// void DamageTextureDoorP__15GeometryVehicleb();
// void DamageTextureDoorD__15GeometryVehicleb();
// void HideFlappingPiece__15GeometryVehicleib();
// void Update__15GeometryVehiclef();
// void SetTrafficBodyColour__15GeometryVehicleG10pddiColour();
// void GetP3DPose__15GeometryVehicle();
// void SetShadowAdjustments__15GeometryVehiclePA1_f();
// void SetFadeAlpha__15GeometryVehiclei();
// void IsTrafficModel__15GeometryVehicle();
// void FadeRoof__15GeometryVehicleb();
// void FindRoofGeometry__15GeometryVehiclePCc();
// void EnableLights__15GeometryVehicleb();
// void GetVehicleColour__C15GeometryVehicle();
// void FindAnimationControllers__15GeometryVehiclePCc();
// void GetSpecialController__15GeometryVehicleG13tUidUnalignedPQ215GeometryVehicle22VehicleFrameController();
// void AdvanceAnimationControllers__15GeometryVehiclef();
// void __17PhysicsLocomotionP7Vehicle();
// void _$_17PhysicsLocomotion();
// void SetTerrainIntersectCachePointsForNewTransform__17PhysicsLocomotion();
// void MoveWheelsToBottomOfSuspension__17PhysicsLocomotion();
// void UpdateVehicleGroundPlane__17PhysicsLocomotion();
// void PreCollisionPrep__17PhysicsLocomotionb();
// void CompareNormalAndHeight__17PhysicsLocomotioniRQ218RadicalMathLibrary6VectorT2();
// void PreSubstepUpdate__17PhysicsLocomotion();
// void SetForceApplicationPoints__17PhysicsLocomotion();
// void ApplySuspensionForces__17PhysicsLocomotionfb();
// void CalculateSuspensionForce__17PhysicsLocomotionP5WheelffRf();
// void ApplyDragForce__17PhysicsLocomotion();
// void ApplyAngularDrag__17PhysicsLocomotion();
// void ApplyRollingFriction__17PhysicsLocomotion();
// void Weeble__17PhysicsLocomotion();
// void PreUpdate__17PhysicsLocomotion();
// void Update__17PhysicsLocomotionf();
// void DurangoStyleStabilizer__17PhysicsLocomotionf();
// void StuckOnSideTest__17PhysicsLocomotionf();
// void PostUpdate__17PhysicsLocomotion();
// void CorrectWheelYPositions__17PhysicsLocomotion();
// void FetchWheelTerrainCollisionInfo__17PhysicsLocomotion();
// void UseWheelTerrainCollisionInfo__17PhysicsLocomotionf();
// void ApplyControllerForces2__17PhysicsLocomotionf();
// void ApplyTerrainFriction__17PhysicsLocomotionPQ218RadicalMathLibrary6Vector();
// void GasForce2__17PhysicsLocomotionRQ218RadicalMathLibrary6Vectorif();
// void BrakeForce2__17PhysicsLocomotionRQ218RadicalMathLibrary6Vectorif();
// void ReverseForce2__17PhysicsLocomotionRQ218RadicalMathLibrary6Vectori();
// void EBrakeEffect__17PhysicsLocomotionRQ218RadicalMathLibrary6Vectori();
// void SteeringForce2__17PhysicsLocomotionRQ218RadicalMathLibrary6Vectorif();
// void TestControllerForces__17PhysicsLocomotionPQ218RadicalMathLibrary6Vector();
// void SetSkidLevel__17PhysicsLocomotion();
// void __28RedBrickCollisionSolverAgent();
// void _$_28RedBrickCollisionSolverAgent();
// void ResetCollisionFlags__28RedBrickCollisionSolverAgent();
// void TestImpulse__28RedBrickCollisionSolverAgentRQ218RadicalMathLibrary6VectorRQ23sim9Collision();
// void CarOnCarPreTest__28RedBrickCollisionSolverAgentRQ23sim9Collisioni();
// void PreCollisionEvent__28RedBrickCollisionSolverAgentRQ23sim9Collisioni();
// void EndObjectCollision__28RedBrickCollisionSolverAgentPQ23sim8SimStatei();
// void TestCache__28RedBrickCollisionSolverAgentPQ23sim8SimStatei();
// void Update__16RootMatrixDriverPQ25poser4Pose();
// void __21SuspensionJointDriverP5Wheeli();
// void _$_21SuspensionJointDriver();
// void Update__21SuspensionJointDriverPQ25poser4Pose();
// void __17TrafficLocomotionP7Vehicle();
// void _$_17TrafficLocomotion();
// void InitPos__17TrafficLocomotionRCQ218RadicalMathLibrary6Vector();
// void InitFacing__17TrafficLocomotionRCQ218RadicalMathLibrary6Vector();
// void Init__17TrafficLocomotion();
// void InitVehicleAI__17TrafficLocomotionP7Vehicle();
// void InitLane__17TrafficLocomotionP4LaneUif();
// void InitSegment__17TrafficLocomotionP11RoadSegmentUif();
// void UpdateVehicleGroundPlane__17TrafficLocomotion();
// void PreCollisionPrep__17TrafficLocomotionb();
// void PreSubstepUpdate__17TrafficLocomotion();
// void PreUpdate__17TrafficLocomotion();
// void func_00280030();
// void StopSuddenly__17TrafficLocomotionRQ218RadicalMathLibrary6VectorT1();
// void Update__17TrafficLocomotionf();
// void PostUpdate__17TrafficLocomotion();
// void FindOutLane__17TrafficLocomotionPC4LaneUiRP4LaneRUi();
// void BuildCurve__17TrafficLocomotionP11RoadSegmentUiT1Ui();
// void EnterIntersection__17TrafficLocomotion();
// void PivotFrontWheels__17TrafficLocomotionGQ218RadicalMathLibrary6Vector();
// void UpdateLanes__17TrafficLocomotionP14TrafficVehicleP4LaneT2();
// void GetAIPrevLane__17TrafficLocomotion();
// void BuildLaneChangeCurve__17TrafficLocomotionP11RoadSegmentfUiUif();
// void BuildArbitraryCurve__17TrafficLocomotionRCQ218RadicalMathLibrary6VectorN31();
// void GetSplineCurve__17TrafficLocomotionRPQ218RadicalMathLibrary6VectorRiT2();
// void ActivateTriggers__7Vehicleb();
// void SetUserDrivingCar__7Vehicleb();
// void TransitToAI__7Vehicle();
// void EnteringJumpBoostVolume__7Vehicle();
// void ExitingJumpBoostVolume__7Vehicle();
// void CastsShadow__7Vehicle();
// void DisplayShadow__7Vehicle();
// void DisplaySimpleShadow__7Vehicle();
// void SetInCarSimState__7Vehicle();
// void SetOutOfCarSimState__7Vehicle();
// void SetLocomotion__7Vehicle21VehicleLocomotionType();
// void IsAFlappingJoint__7Vehiclei();
// void CalculateDragCoeffBasedOnTopSpeed__7Vehicle();
// void IsJointAWheel__7Vehiclei();
// void SetWheelCorrectionOffset__7VehicleifRQ218RadicalMathLibrary6VectorT3();
// void func_00282D18();
// void GetCollisionAreaIndexAndAddSelf__7Vehicle();
// void RemoveSelfAndFreeCollisionAreaIndex__7Vehicle();
// void AddSelfToCollisionManager__7Vehicle();
// void RemoveSelfFromCollisionManager__7Vehicle();
// void func_00282E68();
// void CalculateValuesBasedOnDesignerParams__7Vehicle();
// void TrafficSetTransform__7VehicleRQ218RadicalMathLibrary6Matrix();
// void GetRestHeightAboveGround__7Vehicle();
// void SetTransform__7VehicleRQ218RadicalMathLibrary6Matrix();
// void SetPosition__7VehiclePQ218RadicalMathLibrary6Vector();
// void SetInitialPositionGroundOffsetAutoAdjust__7VehiclePQ218RadicalMathLibrary6Vector();
// void SetInitialPosition__7VehiclePQ218RadicalMathLibrary6Vector();
// void SetResetFacingInRadians__7Vehiclef();
// void Reset__7VehiclebT1();
// void ResetFlagsOnly__7Vehicleb();
// void ResetOnSpot__7VehiclebT1();
// void GetFacingInRadians__7Vehicle();
// void FacingIntoRad__7VehicleGQ218RadicalMathLibrary6Vector();
// void SetGas__7Vehiclef();
// void SetBrake__7Vehiclef();
// void SetEBrake__7Vehicleff();
// void SetWheelTurnAngle__7Vehiclefbf();
// void SetWheelTurnAngleDirectlyInRadiansForDusitOnly__7Vehiclef();
// void SetReverse__7Vehiclef();
// void PreSubstepUpdate__7Vehiclef();
// void PreCollisionPrep__7Vehiclefb();
// void SetNoDamperDownFlagOnWheel__7Vehiclei();
// void CalculateSuspensionLocationAndVelocity__7Vehicle();
// void JumpOnHorn__7Vehiclef();
// void TurboOnHorn__7Vehicle();
// void Update__7Vehiclef();
// void GetGroundY__7Vehicle();
// void PostSubstepUpdate__7Vehiclef();
// void BounceCharacters__7Vehiclef();
// void MoveCharactersTowardsRestPosition__7Vehiclef();
// void ApplyDisplacementToCharacters__7Vehiclef();
// void RecordRestSeatingPositionsOnEntry__7Vehicle();
// void RestTest__7Vehicle();
// void SelfRestTest__7Vehicle();
// void ZeroOutXZVelocity__7Vehicle();
// void SetGeometryVehicleWheelSmokeLevel__7Vehicle();
// void DSGUpdateAndMove__7Vehicle();
// void UpdateGearAndRPM__7Vehicle();
// void UpdateWheelRenderingInfo__7Vehiclef();
// void GetTransform__7Vehicle();
// void pPosition__7Vehicle();
// void rPosition__7Vehicle();
// void Display__7Vehicle();
// void CarDisplay__7Vehicleb();
// void GetSpeedKmh__7Vehicle();
// void GetAccelMss__7Vehicle();
// void GetSkidLevel__7Vehicle();
// void GetPosition__7VehiclePQ218RadicalMathLibrary6Vector();
// void GetHeading__7VehiclePQ218RadicalMathLibrary6Vector();
// void GetVUP__7VehiclePQ218RadicalMathLibrary6Vector();
// void GetVelocity__7VehiclePQ218RadicalMathLibrary6Vector();
// void GetID__7Vehicle();
// void IsCar__C7Vehicle();
// void IsAirborn__7Vehicle();
// void IsUnstable__7Vehicle();
// void IsSafeToUpShift__7Vehicle();
// void IsQuickTurn__7Vehicle();
// void IsInReverse__7Vehicle();
// void GetTerrainIntersect__C7VehicleRQ218RadicalMathLibrary6VectorT1();
// void IsMovingBackward__7Vehicle();
// void GetName__7Vehicle();
// void GetPassengerLocation__C7Vehicle();
// void GetDriverLocation__C7Vehicle();
// void PreReactToCollision__7VehiclePQ23sim8SimStateRQ23sim9Collision();
// void ResetDamageState__7Vehicle();
// void func_00286BF8();
// void PostReactToCollision__7VehicleRQ218RadicalMathLibrary6VectorRQ23sim9Collision();
// void DusitsStunTest__7Vehiclef();
// void TestWhoHitWhom__7VehiclePQ23sim8SimStateT1fRCQ23sim9Collision();
// void SwitchOnDamageTypeAndApply__7VehiclefRQ23sim9Collision();
// void CarOnCarDamageLogic__7VehiclebPQ23sim8SimStateT2();
// void CameraShakeTest__7VehiclefRQ23sim9Collision();
// void SparksTest__7VehiclefRQ23sim9Collision();
// void VisualDamageType1__7VehiclefQ27Vehicle14DamageLocation();
// void VisualDamageType2__7VehiclefQ27Vehicle14DamageLocation();
// void VisualDamageType3__7Vehiclef();
// void SyncVisualDamage__7Vehiclef();
// void TranslateCollisionIntoLocation__7VehicleRQ23sim9Collision();
// void BeefUpHitPointsOnTrafficCarsWhenUserDriving__7Vehicle();
// void GetVehicleLifePercentage__7Vehiclef();
// void TriggerDamage__7Vehiclefb();
// void NeedToOpenDoor__7VehicleQ27Vehicle4Door();
// void NeedToCloseDoor__7VehicleQ27Vehicle4Door();
// void HasActiveDoor__7VehicleQ27Vehicle4Door();
// void UpdateDoorState__7Vehicle();
// void ReleaseDoors__7Vehicle();
// void PlayExplosionEffect__7Vehicle();
// void AddToSimulation__7Vehicle();
// void ApplyForce__7VehicleRCQ218RadicalMathLibrary6Vectorf();
// void AttachCollectible__7VehicleP20StatePropCollectible();
// void GetAttachedCollectible__7Vehicle();
// void DetachCollectible__7VehicleRCQ218RadicalMathLibrary6Vectorb();
// void MoveDoor__7VehicleQ27Vehicle4DoorQ27Vehicle10DoorActionf();
// void CalcDoor__7VehicleUiUif();
// void CalcDoors__7Vehicle();
// void SetDriverName__7VehiclePCc();
// void GetDriverName__7Vehicle();
// void SetDriver__7VehicleP9Character();
// void SetShadowAdjustments__7VehiclePA1_f();
// void SetShininess__7VehicleUc();
// void GetTopSpeed__C7Vehicle();
// void __7Vehicle();
// void Init__7VehiclePCcPQ23sim14SimEnvironment21VehicleLocomotionType11VehicleTypeb();
// void InitEventLocator__7Vehicle();
// void AssignEnumBasedOnName__7Vehicle();
// void func_0028A5A8();
// void SetupRadDebugWatchStuff__7Vehicle();
// void _$_7Vehicle();
// void CreateLocomotions__7Vehicle();
// void InitWheelsAndLinkSuspensionJointDrivers__7Vehicle();
// void InitFlappingJoints__7Vehicle();
// void AddFlappingJoint__7VehiclePCcT1RQ218RadicalMathLibrary6VectorT3iPi();
// void InitGears__7Vehicle();
// void SetupPhysicsProperties__7Vehicle();
// void InitGroundPlane__7Vehicle();
// void FetchWheelMapping__7Vehicle();
// void GetWheel0Offset__7Vehicle();
// void GetWheel1Offset__7Vehicle();
// void InitSimState__7VehiclePQ23sim14SimEnvironment();
// void CreatePoseEngine__7Vehicle();
// void __5Wheel();
// void _$_5Wheel();
// void Init__5WheelP7VehicleifbT4();
// void SetDesignerParams__5WheelPQ27Vehicle14DesignerParams();
// void func_0028BD80();
// void CalculateRenderingSpinUpRateBase__5Wheelf();
// void CalculateRotAngle__5Wheelf();
// void SetYOffsetFromCurrentPosition__5Wheelf();
// void ResolveOffset__5Wheel();
// void GetYCorrectionValue__5Wheel();
// void Reset__5Wheel();
// void __20VehicleEventListenerP7Vehicle();
// void _$_20VehicleEventListener();
// void HandleEvent__20VehicleEventListener9EventEnumPv();
// void __19TrafficBodyDrawable();
// void _$_19TrafficBodyDrawable();
// void SetBodyPropDrawable__19TrafficBodyDrawableP9tDrawable();
// void SetBodyShader__19TrafficBodyDrawableP7tShader();
// void Display__19TrafficBodyDrawable();
// void ProcessShaders__19TrafficBodyDrawableRQ29tDrawable14ShaderCallback();
// void __uninitialized_copy_aux__H2ZPQ215GeometryVehicle22VehicleFrameControllerZPQ215GeometryVehicle22VehicleFrameController_X01X01X11G12__false_type_X11();
// void _M_insert_aux__t6vector2ZQ215GeometryVehicle22VehicleFrameControllerZt7s2alloc1ZQ215GeometryVehicle22VehicleFrameControllerPQ215GeometryVehicle22VehicleFrameControllerRCQ215GeometryVehicle22VehicleFrameController();
// void func_0028CDE8();
// void func_0028CE00();
// void func_0028D098();
// void __tf7Vehicle();
// void __tf19TrafficBodyDrawable();
// void _$_Q23sim26PhysicsJointMatrixModifier();
// void __tfQ23sim26PhysicsJointMatrixModifier();
// void _$_Q23sim28PhysicsJointInertialEffector();
// void __tfQ23sim28PhysicsJointInertialEffector();
// void __tf17VehicleLocomotion();
// void __tf17PhysicsLocomotion();
// void __tf28RedBrickCollisionSolverAgent();
// void _$_16RootMatrixDriver();
// void __tf16RootMatrixDriver();
// void __tf21SuspensionJointDriver();
// void __tf17TrafficLocomotion();
// void func_0028D4E8();
// void __tf20VehicleEventListener();
// void func_0028D548();
// void _$_t18_Vector_alloc_base3ZQ215GeometryVehicle22VehicleFrameControllerZt7s2alloc1ZQ215GeometryVehicle22VehicleFrameControllerb0();
// void func_0028D580();
// void __Q27Vehicle14DesignerParams();
// void SetShadow__7VehicleP11tShadowMesh();
// void GetSimState__C7Vehicle();
// void mpSimState__C7Vehicle();
// void OnSetSimState__7VehiclePQ23sim8SimState();
// void GetFirstPersonPosition__7VehiclePQ218RadicalMathLibrary6Vector();
// void func_0028D5D8();
// void GetAIRef__7Vehicle();
// void GetGroundPlaneAIRef__7Vehicle();
// void __Q216radLoadInventoryt8SafeCast1Z19tBillboardQuadGroup();
// void func_0028D628();
// void __Q216radLoadInventoryt8SafeCast1Z17tEffectController();
// void func_0028D668();
// void __Q216radLoadInventoryt8SafeCast1Z24tPoseAnimationController();
// void func_0028D6A8();
// void GetMinimumJointIndex__CQ23sim26PhysicsJointMatrixModifier();
// void GetPriority__CQ23sim26PhysicsJointMatrixModifier();
// void Advance__Q23sim26PhysicsJointMatrixModifierf();
// void Update__Q23sim26PhysicsJointMatrixModifierPQ25poser4Pose();
// void GetMinimumJointIndex__CQ23sim28PhysicsJointInertialEffector();
// void GetPriority__CQ23sim28PhysicsJointInertialEffector();
// void SetIsEnabled__Q23sim28PhysicsJointInertialEffectorb();
// void Advance__Q23sim28PhysicsJointInertialEffectorf();
// void Update__Q23sim28PhysicsJointInertialEffectorPQ25poser4Pose();
// void _$_17VehicleLocomotion();
// void __Q217PhysicsLocomotion21TerrainIntersectCache();
// void _$_25WorldCollisionSolverAgent();
// void __25WorldCollisionSolverAgent();
// void func_0028DA98();
// void GetMinimumJointIndex__C16RootMatrixDriver();
// void GetPriority__C16RootMatrixDriver();
// void Advance__16RootMatrixDriverf();
// void Advance__21SuspensionJointDriverf();
// void CompareNormalAndHeight__17TrafficLocomotioniRQ218RadicalMathLibrary6VectorT2();
// void func_0028DAC8();
// void __tfQ216radLoadInventoryt8SafeCast1Z19tBillboardQuadGroup();
// void func_0028DB58();
// void __tfQ216radLoadInventoryt8SafeCast1Z17tEffectController();
// void func_0028DBB8();
// void __tfQ216radLoadInventoryt8SafeCast1Z24tPoseAnimationController();
// void func_0028DC18();
// void __tf25WorldCollisionSolverAgent();
// void func_0028DC80();
// void ResetCollisionFlags__25WorldCollisionSolverAgent();
// void func_0028DC90();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z24tPoseAnimationControllerP9IRefCount();
// void func_0028DCF0();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z17tEffectControllerP9IRefCount();
// void func_0028DD48();
// void safe_cast__Q216radLoadInventoryt8SafeCast1Z19tBillboardQuadGroupP9IRefCount();
// void func_0028DDA0();
// void _GLOBAL_$I$__15GeometryVehicle();

// data

// extern UNK_TYPE D_00435E04;
// extern UNK_TYPE D_00435E08;
// extern UNK_TYPE D_00435E0C;
// extern UNK_TYPE D_00435E2C;
// extern UNK_TYPE _7Vehicle$s_DamageFromExplosion;
// extern UNK_TYPE _7Vehicle$s_DamageFromExplosionPlayer;
// extern UNK_TYPE _7Vehicle$sDoBounce;
// extern UNK_TYPE D_00435E75;
// extern UNK_TYPE D_00435E78;
// extern UNK_TYPE D_00435E7C;

// bss

// extern UNK_TYPE D_004B2938;
// extern UNK_TYPE D_004B2968;
// extern UNK_TYPE D_004B2AD8;
// extern UNK_TYPE D_004B2AE8;
// extern UNK_TYPE D_004B2AF0;
// extern UNK_TYPE D_004B2B00;
// extern UNK_TYPE D_004B2B10;
// extern UNK_TYPE D_004B2B20;
// extern UNK_TYPE D_004B2B30;
// extern UNK_TYPE D_004B2B40;
// extern UNK_TYPE D_004B2B50;
// extern UNK_TYPE D_004B2B60;
// extern UNK_TYPE D_004B2B70;
// extern UNK_TYPE D_004B2BB0;

// rodata

// extern UNK_TYPE D_0047AC10;
// extern UNK_TYPE D_0047AC68;
// extern UNK_TYPE D_0047AC70;
// extern UNK_TYPE D_0047AC78;
// extern UNK_TYPE D_0047AC80;
// extern UNK_TYPE D_0047AC90;
// extern UNK_TYPE D_0047ACA0;
// extern UNK_TYPE D_0047ACB0;
// extern UNK_TYPE D_0047ACC0;
// extern UNK_TYPE D_0047ACC8;
// extern UNK_TYPE D_0047ACD0;
// extern UNK_TYPE D_0047ACD8;
// extern UNK_TYPE D_0047ACE0;
// extern UNK_TYPE D_0047ACF0;
// extern UNK_TYPE D_0047AD08;
// extern UNK_TYPE D_0047AD10;
// extern UNK_TYPE D_0047AD28;
// extern UNK_TYPE D_0047AD30;
// extern UNK_TYPE D_0047AD38;
// extern UNK_TYPE D_0047AD48;
// extern UNK_TYPE D_0047AD50;
// extern UNK_TYPE D_0047AD58;
// extern UNK_TYPE D_0047AD60;
// extern UNK_TYPE D_0047AD70;
// extern UNK_TYPE D_0047AD78;
// extern UNK_TYPE D_0047AD80;
// extern UNK_TYPE D_0047AD90;
// extern UNK_TYPE D_0047ADA0;
// extern UNK_TYPE D_0047ADB0;
// extern UNK_TYPE D_0047ADC8;
// extern UNK_TYPE D_0047ADD8;
// extern UNK_TYPE D_0047ADF0;
// extern UNK_TYPE D_0047AE00;
// extern UNK_TYPE D_0047AE10;
// extern UNK_TYPE D_0047AE20;
// extern UNK_TYPE D_0047AE38;
// extern UNK_TYPE D_0047AE48;
// extern UNK_TYPE D_0047AE60;
// extern UNK_TYPE D_0047AE68;
// extern UNK_TYPE D_0047AE78;
// extern UNK_TYPE D_0047AE80;
// extern UNK_TYPE D_0047AE90;
// extern UNK_TYPE D_0047AE98;
// extern UNK_TYPE D_0047AEA0;
// extern UNK_TYPE D_0047AEA8;
// extern UNK_TYPE D_0047AEB0;
// extern UNK_TYPE D_0047AEB8;
// extern UNK_TYPE D_0047AEC8;
// extern UNK_TYPE D_0047AED8;
// extern UNK_TYPE D_0047AEE8;
// extern UNK_TYPE D_0047AEF8;
// extern UNK_TYPE D_0047AF08;
// extern UNK_TYPE D_0047AF18;
// extern UNK_TYPE D_0047AF28;
// extern UNK_TYPE D_0047AF38;
// extern UNK_TYPE D_0047AF48;
// extern UNK_TYPE D_0047AF58;
// extern UNK_TYPE D_0047AF68;
// extern UNK_TYPE D_0047AF78;
// extern UNK_TYPE D_0047AF88;
// extern UNK_TYPE jtbl_0047AFA0;
// extern UNK_TYPE jtbl_0047AFC0;
// extern UNK_TYPE _17TrafficLocomotion$SECONDS_BETW_HISTORY_UPDATES;
// extern UNK_TYPE jtbl_0047AFF0;
// extern UNK_TYPE D_0047B010;
// extern UNK_TYPE D_0047B020;
// extern UNK_TYPE D_0047B028;
// extern UNK_TYPE D_0047B030;
// extern UNK_TYPE D_0047B040;
// extern UNK_TYPE D_0047B050;
// extern UNK_TYPE D_0047B060;
// extern UNK_TYPE D_0047B148;
// extern UNK_TYPE D_0047B158;
// extern UNK_TYPE D_0047B168;
// extern UNK_TYPE D_0047B178;
// extern UNK_TYPE D_0047B188;
// extern UNK_TYPE D_0047B198;
// extern UNK_TYPE D_0047B1A8;
// extern UNK_TYPE jtbl_0047B1C0;
// extern UNK_TYPE D_0047B1E0;
// extern UNK_TYPE D_0047B1E8;
// extern UNK_TYPE D_0047B1F0;
// extern UNK_TYPE D_0047B1F8;
// extern UNK_TYPE D_0047B200;
// extern UNK_TYPE D_0047B208;
// extern UNK_TYPE D_0047B210;
// extern UNK_TYPE D_0047B218;
// extern UNK_TYPE D_0047B220;
// extern UNK_TYPE D_0047B228;
// extern UNK_TYPE D_0047B230;
// extern UNK_TYPE D_0047B238;
// extern UNK_TYPE D_0047B240;
// extern UNK_TYPE D_0047B248;
// extern UNK_TYPE D_0047B258;
// extern UNK_TYPE D_0047B260;
// extern UNK_TYPE D_0047B268;
// extern UNK_TYPE D_0047B270;
// extern UNK_TYPE D_0047B278;
// extern UNK_TYPE D_0047B280;
// extern UNK_TYPE D_0047B288;
// extern UNK_TYPE D_0047B290;
// extern UNK_TYPE D_0047B298;
// extern UNK_TYPE D_0047B2A0;
// extern UNK_TYPE D_0047B2B0;
// extern UNK_TYPE D_0047B2B8;
// extern UNK_TYPE D_0047B2C0;
// extern UNK_TYPE D_0047B2C8;
// extern UNK_TYPE D_0047B2D0;
// extern UNK_TYPE D_0047B2D8;
// extern UNK_TYPE D_0047B2E0;
// extern UNK_TYPE D_0047B2E8;
// extern UNK_TYPE D_0047B2F0;
// extern UNK_TYPE D_0047B300;
// extern UNK_TYPE D_0047B308;
// extern UNK_TYPE D_0047B310;
// extern UNK_TYPE D_0047B318;
// extern UNK_TYPE D_0047B320;
// extern UNK_TYPE D_0047B328;
// extern UNK_TYPE D_0047B330;
// extern UNK_TYPE D_0047B338;
// extern UNK_TYPE D_0047B340;
// extern UNK_TYPE D_0047B350;
// extern UNK_TYPE D_0047B358;
// extern UNK_TYPE D_0047B360;
// extern UNK_TYPE D_0047B368;
// extern UNK_TYPE D_0047B370;
// extern UNK_TYPE D_0047B378;
// extern UNK_TYPE D_0047B380;
// extern UNK_TYPE D_0047B388;
// extern UNK_TYPE D_0047B390;
// extern UNK_TYPE D_0047B398;
// extern UNK_TYPE D_0047B3A0;
// extern UNK_TYPE D_0047B3A8;
// extern UNK_TYPE D_0047B3B0;
// extern UNK_TYPE D_0047B3B8;
// extern UNK_TYPE D_0047B3C0;
// extern UNK_TYPE D_0047B3C8;
// extern UNK_TYPE D_0047B3D0;
// extern UNK_TYPE D_0047B3D8;
// extern UNK_TYPE D_0047B3E0;
// extern UNK_TYPE D_0047B3E8;
// extern UNK_TYPE D_0047B3F0;
// extern UNK_TYPE D_0047B3F8;
// extern UNK_TYPE D_0047B400;
// extern UNK_TYPE D_0047B410;
// extern UNK_TYPE D_0047B420;
// extern UNK_TYPE D_0047B428;
// extern UNK_TYPE D_0047B438;
// extern UNK_TYPE D_0047B440;
// extern UNK_TYPE D_0047B448;
// extern UNK_TYPE D_0047B458;
// extern UNK_TYPE D_0047B468;
// extern UNK_TYPE D_0047B478;
// extern UNK_TYPE D_0047B480;
// extern UNK_TYPE D_0047B488;
// extern UNK_TYPE D_0047B7B8;
// extern UNK_TYPE D_0047B7C8;
// extern UNK_TYPE D_0047B7D8;
// extern UNK_TYPE D_0047B7E8;
// extern UNK_TYPE D_0047B7F8;
// extern UNK_TYPE D_0047B808;
// extern UNK_TYPE D_0047B810;
// extern UNK_TYPE D_0047B820;
// extern UNK_TYPE D_0047B830;
// extern UNK_TYPE D_0047B850;
// extern UNK_TYPE D_0047B860;
// extern UNK_TYPE D_0047B868;
// extern UNK_TYPE D_0047B870;
// extern UNK_TYPE D_0047B878;
// extern UNK_TYPE D_0047B890;
// extern UNK_TYPE _vt$20VehicleEventListener;
// extern UNK_TYPE _vt$17TrafficLocomotion;
// extern UNK_TYPE _vt$21SuspensionJointDriver;
// extern UNK_TYPE _vt$16RootMatrixDriver;
// extern UNK_TYPE _vt$28RedBrickCollisionSolverAgent;
// extern UNK_TYPE _vt$17PhysicsLocomotion;
// extern UNK_TYPE _vt$17VehicleLocomotion;
// extern UNK_TYPE _vt$Q23sim28PhysicsJointInertialEffector;
// extern UNK_TYPE _vt$Q23sim26PhysicsJointMatrixModifier;
// extern UNK_TYPE _vt$19TrafficBodyDrawable;
// extern UNK_TYPE _vt$7Vehicle$18IHudMapIconLocator;
// extern UNK_TYPE _vt$7Vehicle$15ISuperCamTarget;
// extern UNK_TYPE _vt$7Vehicle$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$7Vehicle;
// extern UNK_TYPE D_0047BE88;
// extern UNK_TYPE D_0047BE98;
// extern UNK_TYPE D_0047BEB0;
// extern UNK_TYPE D_0047BEC8;
// extern UNK_TYPE D_0047BEF0;
// extern UNK_TYPE D_0047BF18;
// extern UNK_TYPE D_0047BF30;
// extern UNK_TYPE D_0047BF48;
// extern UNK_TYPE D_0047BF68;
// extern UNK_TYPE D_0047BF80;
// extern UNK_TYPE D_0047BF98;
// extern UNK_TYPE D_0047BFC8;
// extern UNK_TYPE D_0047C098;
// extern UNK_TYPE _vt$25WorldCollisionSolverAgent;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z24tPoseAnimationController;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z17tEffectController;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1Z19tBillboardQuadGroup;
// extern UNK_TYPE D_0047C378;
// extern UNK_TYPE D_0047C3E8;
// extern UNK_TYPE D_0047C450;
// extern UNK_TYPE D_0047C4F8;

#endif
