#ifndef ALLROADS_H
#define ALLROADS_H

// text

// void InitOnceLUTs__11CubicBezier();
// void __11CubicBezier();
// void _$_11CubicBezier();
// void GetCubicBezierCurve__11CubicBezierRPQ218RadicalMathLibrary6VectorRi();
// void SetControlPoint__11CubicBezierRCQ218RadicalMathLibrary6Vectori();
// void AddControlPoint__11CubicBezierRCQ218RadicalMathLibrary6Vector();
// void CreateCubicBezierCurve__11CubicBezier();
// void __10DListArray();
// void Clear__10DListArray();
// void AddLast__10DListArrayPv();
// void func_0021F458();
// void Remove__10DListArrayi();
// void IntersectLineSphere__FRCQ218RadicalMathLibrary6VectorT0RCQ218RadicalMathLibrary6SpherePQ218RadicalMathLibrary6Vector();
// void func_0021F730();
// void WillCollide__FRCQ218RadicalMathLibrary6VectorN20ffT0Rb();
// void UpdateVUP__FRCQ218RadicalMathLibrary6VectorT0();
// void PointsOnSameSideOfLine__FRCQ218RadicalMathLibrary6VectorN30();
// void func_0021FA98();
// void Get90DegreeRightTurn__FRCQ218RadicalMathLibrary6Vector();
// void GetRotationAboutY__Fff();
// void func_0021FBB8();
// void FindClosestPointOnLine__FRCQ218RadicalMathLibrary6VectorN20RQ218RadicalMathLibrary6Vector();
// void GetLineSegmentT__FRCQ218RadicalMathLibrary6VectorN20();
// void __12Intersection();
// void func_0021FFC0();
// void _$_12Intersection();
// void Update__12IntersectionUi();
// void AdvanceTraffic__C12IntersectionUiUi();
// void AdvanceNextWaitingRoad__12Intersection();
// void AddRoadIn__12IntersectionP4Road();
// void AddRoadOut__12IntersectionP4Road();
// void FindRoadIn__C12IntersectionPC4Road();
// void func_00220438();
// void GetLocation__C12IntersectionRQ218RadicalMathLibrary6Vector();
// void PopulateShortestRoads__12IntersectionRt9SwapArray1ZQ211RoadManager12ShortestRoadb();
// void SortRoads__12Intersection();
// void GetType__C12Intersection();
// void SetType__12IntersectionQ212Intersection4Type();
// void IsPointInIntersection__C12IntersectionRQ218RadicalMathLibrary6Vector();
// void FindGoodTrafficLane__12IntersectionRC4RoadUiRP4LaneRUi();
// void GetLeftTurnForTraffic__12IntersectionRC4RoadUiRP4RoadRP4LaneRUi();
// void GetStraightForTraffic__12IntersectionRC4RoadUiRP4RoadRP4LaneRUi();
// void GetRightTurnForTraffic__12IntersectionRC4RoadUiRP4RoadRP4LaneRUi();
// void GetOtherIntersection__12IntersectionbP12IntersectionRP12IntersectionRPQ211RoadManager12ShortestRoad();
// void __4Lane();
// void _$_4Lane();
// void Create__4LaneiP4Road();
// void NotifyWaitingTraffic__4LaneUi();
// void __4Road();
// void _$_4Road();
// void AllocateSegments__4RoadUi();
// void AddRoadSegment__4RoadP11RoadSegment();
// void CreateLanes__4Road();
// void GetLane__C4RoadUi();
// void GetRoadSegment__C4RoadUi();
// void func_002220D0();
// void GetRoadSegmentAtPoint__C4RoadRCQ218RadicalMathLibrary6VectorPP11RoadSegmentRfT3i();
// void IsPointInRoadSegment__C4RoadiRCQ218RadicalMathLibrary6VectorRfT3();
// void func_00222400();
// void SetDensity__4RoadUi();
// void FindRoadSegmentAtDist__4RoadfPP11RoadSegment();
// void GetInstance__11RoadManager();
// void Destroy__11RoadManager();
// void __11RoadManager();
// void _$_11RoadManager();
// void Init__11RoadManagerb();
// void InitializeRoadMemory__11RoadManagerUi();
// void InitializeIntersectionMemory__11RoadManagerUi();
// void InitializeRoadSegmentDataMemory__11RoadManagerUi();
// void DumpRoadSegmentDataMemory__11RoadManager();
// void InitializeRoadSegmentMemory__11RoadManagerUi();
// void GetFreeRoadMemory__11RoadManager();
// void GetFreeIntersectionMemory__11RoadManager();
// void GetFreeRoadSegmentDataMemory__11RoadManager();
// void GetFreeRoadSegmentMemory__11RoadManager();
// void GetMaxPathElements__11RoadManager();
// void FindClosestPointOnRoad__11RoadManagerPC4RoadRCQ218RadicalMathLibrary6VectorRQ218RadicalMathLibrary6VectorRfRi();
// void DetermineRoadT__11RoadManagerP11RoadSegmentf();
// void DetermineSegmentT__11RoadManagerRCQ218RadicalMathLibrary6VectorP11RoadSegment();
// void CreateRoadNetwork__11RoadManager();
// void PopulateConnectivityData__11RoadManagerbP12Intersectioni();
// void VisitAll__11RoadManagerRt9SwapArray1ZQ211RoadManager12DijkstraNode();
// void FindPathElementsBetween__11RoadManagerbRQ211RoadManager11PathElementfRCQ218RadicalMathLibrary6VectorT2fT4Rt9SwapArray1ZQ211RoadManager11PathElement();
// void GetTraversalDistance__11RoadManagerPQ211RoadManager12ShortestRoadT1();
// void FindDistToTargetInOneDirection__11RoadManagerbP12IntersectionN22PQ211RoadManager12ShortestRoadRt9SwapArray1ZQ211RoadManager11PathElementRPQ211RoadManager12ShortestRoadT7RQ211RoadManager10ErrorValue();
// void TraverseRoads__11RoadManagerbP12IntersectionN22Rt9SwapArray1ZQ211RoadManager11PathElementRQ211RoadManager10ErrorValue();
// void FindIntersection__11RoadManagerPCc();
// void FindIntersection__11RoadManagerG13tUidUnaligned();
// void FindIntersection__11RoadManagerRQ218RadicalMathLibrary6Vector();
// void FindIntersection__11RoadManageri();
// void FindRoad__C11RoadManagerRCQ218RadicalMathLibrary6VectorPPC4RoadPP11RoadSegmentRiRfT5b();
// void FindRoadSegmentData__11RoadManagerPCc();
// void FindRoadSegmentData__11RoadManagerG13tUidUnaligned();
// void AddRoad__11RoadManagerP4Road();
// void AddIntersection__11RoadManagerP12Intersection();
// void AddRoadSegmentData__11RoadManagerP15RoadSegmentData();
// void AddRoadSegment__11RoadManagerP11RoadSegment();
// void func_00225FC0();
// void __11RoadSegment();
// void _$_11RoadSegment();
// void Init__11RoadSegmentP15RoadSegmentDataRQ218RadicalMathLibrary6Matrixf();
// void GetBoundingBox__11RoadSegmentPQ218RadicalMathLibrary5Box3D();
// void GetBoundingSphere__11RoadSegmentPQ218RadicalMathLibrary6Sphere();
// void CalculateUnitDistIntoRoadSegment__11RoadSegmentff();
// void CalculateUnitHeightInRoadSegment__11RoadSegmentff();
// void GetPosition__11RoadSegmentffPQ218RadicalMathLibrary6Vector();
// void GetLaneLocation__11RoadSegmentfiRQ218RadicalMathLibrary6VectorT3();
// void GetCorner__11RoadSegmentiRQ218RadicalMathLibrary6Vector();
// void GetEdgeNormal__11RoadSegmentiRQ218RadicalMathLibrary6Vector();
// void GetSegmentNormal__11RoadSegmentRQ218RadicalMathLibrary6Vector();
// void GetNumLanes__11RoadSegment();
// void GetLaneLength__11RoadSegmentUi();
// void GetRoadWidth__11RoadSegment();
// void __15RoadSegmentData();
// void _$_15RoadSegmentData();
// void SetData__15RoadSegmentDataRCQ218RadicalMathLibrary6VectorN21Ui();
// void GetCorner__C15RoadSegmentDatai();
// void GetEdgeNormal__C15RoadSegmentDatai();
// void GetSegmentNormal__C15RoadSegmentData();
// void GetNumLanes__C15RoadSegmentData();
// void Update__12TrafficLightUi();
// void SwitchControl__12TrafficLight();
// void Update__8NWayStopUi();
// void Update__12CourtesyStopUi();
// void __tf14TrafficControl();
// void __tf12TrafficLight();
// void __tf8NWayStop();
// void _$_12CourtesyStop();
// void __tf12CourtesyStop();
// void __tf4Lane();
// void __tf11RoadManager();
// void __tf11RoadSegment();
// void _$_14TrafficControl();
// void _$_12TrafficLight();
// void _$_8NWayStop();
// void __16ILaneInformation();
// void __12ILaneControl();
// void SetSpeedLimit__4Lanef();
// void GetRoad__C4Lane();
// void GetSpeedLimit__C4Lane();
// void SetDensity__4Lanei();
// void GetDensity__C4Lane();
// void _$_Q211RoadManager15BigIntersection();
// void __Q211RoadManager15BigIntersection();
// void Display__11RoadSegment();
// void pPosition__11RoadSegment();
// void rPosition__11RoadSegment();
// void GetPosition__11RoadSegmentPQ218RadicalMathLibrary6Vector();
// void __tf16ILaneInformation();
// void __tf12ILaneControl();

// bss

// extern UNK_TYPE D_004B2098;

// rodata

// extern UNK_TYPE D_004713D8;
// extern UNK_TYPE _11RoadManager$AGAINST_TRAFFIC_COST_MULTIPLIER;
// extern UNK_TYPE _vt$11RoadSegment$Q29tDrawable14ShaderCallback;
// extern UNK_TYPE _vt$11RoadSegment;
// extern UNK_TYPE _vt$11RoadManager;
// extern UNK_TYPE _vt$4Lane$12ILaneControl;
// extern UNK_TYPE _vt$4Lane;
// extern UNK_TYPE _vt$12CourtesyStop;
// extern UNK_TYPE _vt$8NWayStop;
// extern UNK_TYPE _vt$12TrafficLight;
// extern UNK_TYPE _vt$14TrafficControl;
// extern UNK_TYPE D_00471590;
// extern UNK_TYPE D_004715A8;
// extern UNK_TYPE D_004715B8;
// extern UNK_TYPE D_004715C8;
// extern UNK_TYPE D_004715D8;
// extern UNK_TYPE D_004715E0;
// extern UNK_TYPE D_004715F0;
// extern UNK_TYPE D_00471600;
// extern UNK_TYPE D_00471610;
// extern UNK_TYPE _vt$12ILaneControl;
// extern UNK_TYPE _vt$16ILaneInformation;
// extern UNK_TYPE D_00471660;
// extern UNK_TYPE D_00471678;

// data

// extern UNK_TYPE _11CubicBezier$sIsInitialized;
// extern UNK_TYPE D_0042E2C1;
// extern UNK_TYPE _11CubicBezier$B0;
// extern UNK_TYPE _11CubicBezier$B1;
// extern UNK_TYPE _11CubicBezier$B2;
// extern UNK_TYPE _11CubicBezier$B3;
// extern UNK_TYPE _11RoadManager$mInstance;
// extern UNK_TYPE gpShader;
// extern UNK_TYPE D_0042E4B0;

#endif
