#ifndef ALLSEQUENCER_H
#define ALLSEQUENCER_H

// text

// void _$_6Action();
// void IsSlave__C6Action();
// void WakeUp__6Actionf();
// void DoSimulation__6Actionf();
// void Update__6Actionf();
// void Clear__6Action();
// void IsSlave__C11SlaveAction();
// void __22WalkerLocomotionActionP9Character();
// void _$_22WalkerLocomotionAction();
// void PlayDriver__22WalkerLocomotionAction();
// void StopDriver__22WalkerLocomotionAction();
// void SwitchLocomotion__22WalkerLocomotionAction();
// void SolveActualDir__22WalkerLocomotionActionff();
// void SolveActualSpeed__22WalkerLocomotionActionff();
// void WakeUp__22WalkerLocomotionActionf();
// void DoSimulation__22WalkerLocomotionActionf();
// void Update__22WalkerLocomotionActionf();
// void __11InCarActionP9Character();
// void _$_11InCarAction();
// void WakeUp__11InCarActionf();
// void IWannaRock__11InCarActionb();
// void DoSimulation__11InCarActionf();
// void Update__11InCarActionf();
// void Clear__11InCarAction();
// void __19HoldAnimationActionP9CharacterPCcf();
// void _$_19HoldAnimationAction();
// void WakeUp__19HoldAnimationActionf();
// void DoSimulation__19HoldAnimationActionf();
// void Update__19HoldAnimationActionf();
// void Clear__19HoldAnimationAction();
// void __11SteerActionP9CharacterPCcf();
// void ShouldRelease__11SteerAction();
// void __13ReverseActionP9CharacterPCcf();
// void ShouldRelease__13ReverseAction();
// void __11AccelActionP9CharacterPCcf();
// void ShouldRelease__11AccelAction();
// void __11DecelActionP9CharacterPCcf();
// void ShouldRelease__11DecelAction();
// void __6ArriveP9CharacterRQ218RadicalMathLibrary6Vectorb();
// void _$_6Arrive();
// void WakeUp__6Arrivef();
// void DoSimulation__6Arrivef();
// void Update__6Arrivef();
// void Clear__6Arrive();
// void __6OrientP9CharacterRQ218RadicalMathLibrary6Vector();
// void _$_6Orient();
// void WakeUp__6Orientf();
// void DoSimulation__6Orientf();
// void Update__6Orientf();
// void __8PositionP9CharacterRQ218RadicalMathLibrary6Vectorfb();
// void _$_8Position();
// void WakeUp__8Positionf();
// void DoSimulation__8Positionf();
// void Update__8Positionf();
// void WakeUp__10GroundSnapf();
// void __19PlayAnimationActionP9CharacterPCcf();
// void __19PlayAnimationActionP9CharacterRC5tNamef();
// void AbortWhenMovementOccurs__19PlayAnimationActionb();
// void WakeUp__19PlayAnimationActionf();
// void DoSimulation__19PlayAnimationActionf();
// void Update__19PlayAnimationActionf();
// void ShouldAbort__19PlayAnimationAction();
// void Clear__19PlayAnimationAction();
// void __23PlayIdleAnimationActionP9CharacterPCcf();
// void func_00123E78();
// void WakeUp__23PlayIdleAnimationActionf();
// void Clear__23PlayIdleAnimationAction();
// void Abort__23PlayIdleAnimationAction();
// void __13CarDoorActionP7VehicleQ27Vehicle10DoorActionQ27Vehicle4DoorffP9CharacterP9Sequencer();
// void WakeUp__13CarDoorActionf();
// void DoSimulation__13CarDoorActionf();
// void Update__13CarDoorActionf();
// void Clear__13CarDoorAction();
// void Update__18ReleaseDoorsActionf();
// void __10JumpActionP9CharacterPCcf();
// void _$_10JumpAction();
// void SetRootTransform__10JumpAction();
// void SetRootPosition__10JumpActionRCQ218RadicalMathLibrary6Vector();
// void Reset__10JumpActionRCQ218RadicalMathLibrary6Vectorb();
// void Reset__10JumpActionfb();
// void WakeUp__10JumpActionf();
// void DoSimulation__10JumpActionf();
// void SolveActualDir__10JumpActionff();
// void Update__10JumpActionf();
// void TestForJumpAgain__10JumpActionRCQ218RadicalMathLibrary6VectorfRQ218RadicalMathLibrary6Vector();
// void Clear__10JumpAction();
// void __11DodgeActionP9Character();
// void WakeUp__11DodgeActionf();
// void DoSimulation__11DodgeActionf();
// void Update__11DodgeActionf();
// void Clear__11DodgeAction();
// void SolveActualDir__11DodgeActionff();
// void __12CringeActionP9Character();
// void WakeUp__12CringeActionf();
// void DoSimulation__12CringeActionf();
// void Update__12CringeActionf();
// void Clear__12CringeAction();
// void __11FlailActionP9Character();
// void WakeUp__11FlailActionf();
// void DoSimulation__11FlailActionf();
// void Update__11FlailActionf();
// void Clear__11FlailAction();
// void __11GetUpActionP9Character();
// void WakeUp__11GetUpActionf();
// void DoSimulation__11GetUpActionf();
// void Update__11GetUpActionf();
// void Clear__11GetUpAction();
// void Update__16ChangeLocomotionf();
// void Update__24ChangeNPCControllerStatef();
// void Abort__24ChangeNPCControllerState();
// void Update__10KickActionf();
// void __10SurfActionP9Character();
// void ShouldAbort__10SurfAction();
// void Update__10SurfActionf();
// void __16ActionController();
// void _$_16ActionController();
// void Clear__16ActionController();
// void WakeUp__16ActionControllerf();
// void DoSimulation__16ActionControllerf();
// void Update__16ActionControllerf();
// void __9Sequencer();
// void _$_9Sequencer();
// void ClearSequence__9SequencerPQ29Sequencer9sSequence();
// void Clear__9Sequencer();
// void BeginSequence__9Sequencer();
// void EndSequence__9Sequencer();
// void AddAction__9SequencerffP6Action();
// void AddActionToSequence__9SequencerffP6Action();
// void IsBusy__C9Sequencer();
// void WakeUp__9Sequencerf();
// void DoSimulation__9Sequencerf();
// void Update__9Sequencerf();
// void __4Task();
// void _$_4Task();
// void GetStatus__4Task();
// void SetStatus__4Task6Status();
// void IsSleeping__4Task();
// void Run__4Task();
// void IsRunning__4Task();
// void Done__4Task();
// void IsDone__4Task();
// void func_001271F0();
// void __tf4Task();
// void __tf6Action();
// void __tf11SlaveAction();
// void __tf22WalkerLocomotionAction();
// void __tf11InCarAction();
// void __tf19HoldAnimationAction();
// void _$_11SteerAction();
// void __tf11SteerAction();
// void _$_13ReverseAction();
// void __tf13ReverseAction();
// void _$_11AccelAction();
// void __tf11AccelAction();
// void _$_11DecelAction();
// void __tf11DecelAction();
// void __tf10JumpAction();
// void _$_11DodgeAction();
// void __tf11DodgeAction();
// void _$_12CringeAction();
// void __tf12CringeAction();
// void _$_11FlailAction();
// void __tf11FlailAction();
// void _$_11GetUpAction();
// void __tf11GetUpAction();
// void __tf19PlayAnimationAction();
// void _$_23PlayIdleAnimationAction();
// void __tf23PlayIdleAnimationAction();
// void _$_13CarDoorAction();
// void __tf13CarDoorAction();
// void _$_18ReleaseDoorsAction();
// void __tf18ReleaseDoorsAction();
// void __tf6Arrive();
// void __tf6Orient();
// void __tf8Position();
// void __tf10GroundSnap();
// void _$_16ChangeLocomotion();
// void __tf16ChangeLocomotion();
// void _$_24ChangeNPCControllerState();
// void __tf24ChangeNPCControllerState();
// void _$_10KickAction();
// void __tf10KickAction();
// void _$_10SurfAction();
// void __tf10SurfAction();
// void __tf9Sequencer();
// void __tf16ActionController();
// void func_00128120();
// void Abort__6Action();
// void func_00128138();
// void _$_11SlaveAction();
// void func_00128190();
// void _$_19PlayAnimationAction();
// void func_001281F0();
// void _$_10GroundSnap();
// void DoSimulation__10GroundSnapf();
// void Update__10GroundSnapf();
// void func_00128270();
// void __Q216radLoadInventoryt8SafeCast1ZQ26choreo9Animation();
// void __Q216radLoadInventoryt8SafeCast1ZQ26choreo10Locomotion();
// void func_00128308();
// void __tfQ216radLoadInventoryt8SafeCast1ZQ26choreo9Animation();
// void __tfQ216radLoadInventoryt8SafeCast1ZQ26choreo10Locomotion();
// void func_001283C8();
// void safe_cast__Q216radLoadInventoryt8SafeCast1ZQ26choreo10LocomotionP9IRefCount();
// void safe_cast__Q216radLoadInventoryt8SafeCast1ZQ26choreo9AnimationP9IRefCount();
// void func_00128470();
// void _GLOBAL_$I$_6Action$sMemoryPool();
// void _GLOBAL_$D$_6Action$sMemoryPool();

// rodata

// extern UNK_TYPE D_00454A68;
// extern UNK_TYPE D_00454B40;
// extern UNK_TYPE D_00454B48;
// extern UNK_TYPE D_00454B58;
// extern UNK_TYPE D_00454B68;
// extern UNK_TYPE D_00454B70;
// extern UNK_TYPE D_00454B80;
// extern UNK_TYPE D_00454BA0;
// extern UNK_TYPE D_00454BB8;
// extern UNK_TYPE D_00454BD0;
// extern UNK_TYPE D_00454BE0;
// extern UNK_TYPE D_00454BF8;
// extern UNK_TYPE D_00454C10;
// extern UNK_TYPE D_00454C20;
// extern UNK_TYPE D_00454C30;
// extern UNK_TYPE D_00454C40;
// extern UNK_TYPE D_00454C50;
// extern UNK_TYPE D_00454C60;
// extern UNK_TYPE D_00454C70;
// extern UNK_TYPE D_00454C78;
// extern UNK_TYPE D_00454C80;
// extern UNK_TYPE D_00454C88;
// extern UNK_TYPE D_00454C90;
// extern UNK_TYPE _vt$16ActionController;
// extern UNK_TYPE _vt$9Sequencer;
// extern UNK_TYPE _vt$10SurfAction;
// extern UNK_TYPE _vt$10KickAction;
// extern UNK_TYPE _vt$24ChangeNPCControllerState;
// extern UNK_TYPE _vt$16ChangeLocomotion;
// extern UNK_TYPE _vt$10GroundSnap;
// extern UNK_TYPE _vt$8Position;
// extern UNK_TYPE _vt$6Orient;
// extern UNK_TYPE _vt$6Arrive;
// extern UNK_TYPE _vt$18ReleaseDoorsAction;
// extern UNK_TYPE _vt$13CarDoorAction;
// extern UNK_TYPE _vt$23PlayIdleAnimationAction;
// extern UNK_TYPE _vt$19PlayAnimationAction;
// extern UNK_TYPE _vt$11GetUpAction;
// extern UNK_TYPE _vt$11FlailAction;
// extern UNK_TYPE _vt$12CringeAction;
// extern UNK_TYPE _vt$11DodgeAction;
// extern UNK_TYPE _vt$10JumpAction;
// extern UNK_TYPE _vt$11DecelAction;
// extern UNK_TYPE _vt$11AccelAction;
// extern UNK_TYPE _vt$13ReverseAction;
// extern UNK_TYPE _vt$11SteerAction;
// extern UNK_TYPE _vt$19HoldAnimationAction;
// extern UNK_TYPE _vt$11InCarAction;
// extern UNK_TYPE _vt$22WalkerLocomotionAction;
// extern UNK_TYPE _vt$11SlaveAction;
// extern UNK_TYPE _vt$6Action;
// extern UNK_TYPE _vt$4Task;
// extern UNK_TYPE D_00455628;
// extern UNK_TYPE D_00455630;
// extern UNK_TYPE D_00455638;
// extern UNK_TYPE D_00455648;
// extern UNK_TYPE D_00455668;
// extern UNK_TYPE D_00455678;
// extern UNK_TYPE D_00455690;
// extern UNK_TYPE D_004556A0;
// extern UNK_TYPE D_004556B0;
// extern UNK_TYPE D_004556C0;
// extern UNK_TYPE D_004556D0;
// extern UNK_TYPE D_004556E0;
// extern UNK_TYPE D_004556F0;
// extern UNK_TYPE D_00455700;
// extern UNK_TYPE D_00455710;
// extern UNK_TYPE D_00455720;
// extern UNK_TYPE D_00455738;
// extern UNK_TYPE D_00455758;
// extern UNK_TYPE D_00455768;
// extern UNK_TYPE D_00455780;
// extern UNK_TYPE D_00455788;
// extern UNK_TYPE D_00455790;
// extern UNK_TYPE D_004557A0;
// extern UNK_TYPE D_004557B0;
// extern UNK_TYPE D_004557C8;
// extern UNK_TYPE D_004557E8;
// extern UNK_TYPE D_004557F8;
// extern UNK_TYPE D_00455808;
// extern UNK_TYPE D_00455818;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1ZQ26choreo10Locomotion;
// extern UNK_TYPE _vt$Q216radLoadInventoryt8SafeCast1ZQ26choreo9Animation;
// extern UNK_TYPE D_004558A8;
// extern UNK_TYPE D_004558E0;

// data

// extern UNK_TYPE _6Action$sMemoryPool;
// extern UNK_TYPE _22WalkerLocomotionAction$sRandom;
// extern UNK_TYPE _22WalkerLocomotionAction$sRandomSeeded;
// extern UNK_TYPE D_00424B01;
// extern UNK_TYPE D_00424B08;
// extern UNK_TYPE D_00424B30;
// extern UNK_TYPE D_00424B34;
// extern UNK_TYPE D_00424B38;
// extern UNK_TYPE D_00424B40;

// bss

// extern UNK_TYPE D_004B1240;
// extern UNK_TYPE D_004B1248;
// extern UNK_TYPE D_004B1250;
// extern UNK_TYPE D_004B1258;
// extern UNK_TYPE D_004B1260;
// extern UNK_TYPE D_004B1264;
// extern UNK_TYPE D_004B1270;
// extern UNK_TYPE D_004B127C;

#endif
