#ifndef ALLSOUNDAVATAR_H
#define ALLSOUNDAVATAR_H

// text

// void __17AvatarSoundPlayer();
// void _$_17AvatarSoundPlayer();
// void Initialize__17AvatarSoundPlayer();
// void UpdateOncePerFrame__17AvatarSoundPlayerUi();
// void OnBeginGameplay__17AvatarSoundPlayer();
// void OnEndGameplay__17AvatarSoundPlayer();
// void __18carSoundParameters();
// void _$_18carSoundParameters();
// void SetWatcherName__18carSoundParametersPCc();
// void SetShiftPoint__18carSoundParametersUif();
// void GetShiftPoint__18carSoundParametersi();
// void SetAttackTimeMsecs__18carSoundParametersf();
// void SetDelayTimeMsecs__18carSoundParametersUi();
// void SetDecayTimeMsecs__18carSoundParametersf();
// void SetDecayFinishTrim__18carSoundParametersf();
// void SetDownshiftDamperSize__18carSoundParametersf();
// void SetEngineClipName__18carSoundParametersPCc();
// void SetEngineIdleClipName__18carSoundParametersPCc();
// void SetDamagedEngineClipName__18carSoundParametersPCc();
// void SetHornClipName__18carSoundParametersPCc();
// void SetCarDoorOpenClipName__18carSoundParametersPCc();
// void SetCarDoorCloseClipName__18carSoundParametersPCc();
// void SetOverlayClipName__18carSoundParametersPCc();
// void SetRoadSkidClipName__18carSoundParametersPCc();
// void SetDirtSkidClipName__18carSoundParametersPCc();
// void SetBackupClipName__18carSoundParametersPCc();
// void SetGearPitchRange__18carSoundParametersUiff();
// void SetNumberOfGears__18carSoundParametersUi();
// void SetReversePitchCapKmh__18carSoundParametersf();
// void SetReversePitchRange__18carSoundParametersff();
// void SetGearShiftPitchDrop__18carSoundParametersUif();
// void GetGearShiftPitchDrop__18carSoundParametersUi();
// void SetDamageStartPcnt__18carSoundParametersf();
// void SetDamageMaxVolPcnt__18carSoundParametersf();
// void SetDamageStartTrim__18carSoundParametersf();
// void SetDamageMaxTrim__18carSoundParametersf();
// void SetIdleEnginePitch__18carSoundParametersf();
// void SetInAirThrottlePitch__18carSoundParametersf();
// void GetInAirThrottlePitch__18carSoundParameters();
// void SetInAirIdlePitch__18carSoundParametersf();
// void GetInAirIdlePitch__18carSoundParameters();
// void SetInAirThrottleResponseTimeMsecs__18carSoundParametersUi();
// void SetBurnoutMinPitch__18carSoundParametersf();
// void SetBurnoutMaxPitch__18carSoundParametersf();
// void SetPowerslideMinPitch__18carSoundParametersf();
// void GetPowerslideMinPitch__18carSoundParameters();
// void SetPowerslideMaxPitch__18carSoundParametersf();
// void GetPowerslideMaxPitch__18carSoundParameters();
// void CalculateEnginePitch__18carSoundParametersiff();
// void CalculateCurrentGear__18carSoundParametersfffi();
// void GetRevLimit__18carSoundParameters();
// void CarSoundParameterObjCreate__FPP19ICarSoundParametersi();
// void __11SoundAvatarP6Avatar();
// void _$_11SoundAvatar();
// void HandleEvent__11SoundAvatar9EventEnumPv();
// void UpdateOncePerFrame__11SoundAvatarUi();
// void syncCarSoundState__11SoundAvatar();
// void __11EngineState();
// void _$_11EngineState();
// void Initialize__11EngineStateP7VehicleP18carSoundParametersP19SimpsonsSoundPlayerUiP21VehicleSoundDebugPage();
// void SetActive__11EngineStatebf();
// void SetDebugInfo__11EngineState();
// void isAtIdleSpeed__11EngineState();
// void isSkidding__11EngineState();
// void GetCurrentPitch__11EngineState();
// void IsFading__11EngineState();
// void StartFade__11EngineStatefb();
// void ServiceFade__11EngineStateUi();
// void SetTrim__11EngineStatef();
// void __17NormalEngineState();
// void _$_17NormalEngineState();
// void Service__17NormalEngineStateUi();
// void SetDebugInfo__17NormalEngineState();
// void GetCurrentPitch__17NormalEngineState();
// void startup__17NormalEngineStatef();
// void updateCurrentGearFromVehicle__17NormalEngineStateb();
// void __18UpshiftEngineState();
// void _$_18UpshiftEngineState();
// void Service__18UpshiftEngineStateUi();
// void SetDebugInfo__18UpshiftEngineState();
// void startup__18UpshiftEngineStatef();
// void __20DownshiftEngineState();
// void _$_20DownshiftEngineState();
// void Service__20DownshiftEngineStateUi();
// void SetDebugInfo__20DownshiftEngineState();
// void GetCurrentPitch__20DownshiftEngineState();
// void startup__20DownshiftEngineStatef();
// void __16InAirEngineState();
// void _$_16InAirEngineState();
// void Service__16InAirEngineStateUi();
// void SetDebugInfo__16InAirEngineState();
// void startup__16InAirEngineStatef();
// void __18ReverseEngineStateP19SimpsonsSoundPlayer();
// void _$_18ReverseEngineState();
// void Service__18ReverseEngineStateUi();
// void SetDebugInfo__18ReverseEngineState();
// void startup__18ReverseEngineStatef();
// void __15IdleEngineState();
// void _$_15IdleEngineState();
// void Service__15IdleEngineStateUi();
// void SetDebugInfo__15IdleEngineState();
// void GetCurrentPitch__15IdleEngineState();
// void startup__15IdleEngineStatef();
// void __15SkidEngineState();
// void _$_15SkidEngineState();
// void Service__15SkidEngineStateUi();
// void SetDebugInfo__15SkidEngineState();
// void GetCurrentPitch__15SkidEngineState();
// void startup__15SkidEngineStatef();
// void __18VehicleSoundPlayer();
// void _$_18VehicleSoundPlayer();
// void StartCarSounds__18VehicleSoundPlayerP7Vehicle();
// void StopCarSounds__18VehicleSoundPlayer();
// void UpdateSoundParameters__18VehicleSoundPlayerUi();
// void UpdateOncePerFrame__18VehicleSoundPlayerUi();
// void CheckForSkid__18VehicleSoundPlayerUi();
// void CheckHorn__18VehicleSoundPlayer();
// void OnPlaybackComplete__18VehicleSoundPlayer();
// void OnSoundReady__18VehicleSoundPlayer();
// void AddAIVehicleProximityTest__18VehicleSoundPlayerP7Vehicle();
// void DeleteAIVehicleProximityTest__18VehicleSoundPlayerP7Vehicle();
// void checkDamage__18VehicleSoundPlayer();
// void carSoundIsActive__18VehicleSoundPlayer();
// void checkProximity__18VehicleSoundPlayer();
// void getSkidResourceForTerrain__18VehicleSoundPlayer12eTerrainType();
// void func_0022F860();
// void _$_21VehicleSoundDebugPage();
// void fillLineBuffer__21VehicleSoundDebugPageiPc();
// void getNumLines__21VehicleSoundDebugPage();
// void func_0022F9D8();
// void __tf17AvatarSoundPlayer();
// void __tf21VehicleSoundDebugPage();
// void __tf18VehicleSoundPlayer();
// void __tf11SoundAvatar();
// void __tf18carSoundParameters();
// void __tf11EngineState();
// void __tf17NormalEngineState();
// void __tf18UpshiftEngineState();
// void __tf20DownshiftEngineState();
// void __tf16InAirEngineState();
// void __tf18ReverseEngineState();
// void __tf15IdleEngineState();
// void __tf15SkidEngineState();
// void __tft14radLinkedClass1Z18carSoundParameters();
// void func_0022FEA0();
// void __27SimpsonsSoundPlayerCallback();
// void __19ICarSoundParameters();
// void AddRef__18carSoundParameters();
// void Release__18carSoundParameters();
// void SetClipRPM__18carSoundParametersf();
// void func_0022FF70();
// void __tf27SimpsonsSoundPlayerCallback();
// void __tf19ICarSoundParameters();
// void func_00230020();

// rodata

// extern UNK_TYPE D_004721B0;
// extern UNK_TYPE D_004721D8;
// extern UNK_TYPE D_004722A8;
// extern UNK_TYPE D_004722B0;
// extern UNK_TYPE D_004722E8;
// extern UNK_TYPE D_004722F0;
// extern UNK_TYPE D_004722F8;
// extern UNK_TYPE D_00472310;
// extern UNK_TYPE D_00472328;
// extern UNK_TYPE D_00472348;
// extern UNK_TYPE D_00472358;
// extern UNK_TYPE D_00472388;
// extern UNK_TYPE jtbl_004723A0;
// extern UNK_TYPE _vt$15SkidEngineState;
// extern UNK_TYPE _vt$15IdleEngineState;
// extern UNK_TYPE _vt$18ReverseEngineState;
// extern UNK_TYPE _vt$16InAirEngineState;
// extern UNK_TYPE _vt$20DownshiftEngineState;
// extern UNK_TYPE _vt$18UpshiftEngineState;
// extern UNK_TYPE _vt$17NormalEngineState;
// extern UNK_TYPE _vt$11EngineState;
// extern UNK_TYPE _vt$18carSoundParameters$11radRefCount;
// extern UNK_TYPE _vt$18carSoundParameters;
// extern UNK_TYPE _vt$11SoundAvatar;
// extern UNK_TYPE _vt$18VehicleSoundPlayer;
// extern UNK_TYPE _vt$21VehicleSoundDebugPage;
// extern UNK_TYPE _vt$17AvatarSoundPlayer;
// extern UNK_TYPE D_004727D0;
// extern UNK_TYPE D_004727E8;
// extern UNK_TYPE D_00472800;
// extern UNK_TYPE D_00472818;
// extern UNK_TYPE D_00472828;
// extern UNK_TYPE D_00472840;
// extern UNK_TYPE D_00472858;
// extern UNK_TYPE D_00472868;
// extern UNK_TYPE D_00472880;
// extern UNK_TYPE D_00472898;
// extern UNK_TYPE D_004728B0;
// extern UNK_TYPE D_004728C8;
// extern UNK_TYPE D_004728E0;
// extern UNK_TYPE D_004728F8;
// extern UNK_TYPE D_00472910;
// extern UNK_TYPE _vt$19ICarSoundParameters;
// extern UNK_TYPE _vt$27SimpsonsSoundPlayerCallback;
// extern UNK_TYPE D_00472A90;
// extern UNK_TYPE D_00472AB0;

// data

// extern UNK_TYPE _t14radLinkedClass1Z18carSoundParameters$s_pLinkedClassHead;
// extern UNK_TYPE _t14radLinkedClass1Z18carSoundParameters$s_pLinkedClassTail;
// extern UNK_TYPE D_0042E728;
// extern UNK_TYPE D_0042E72C;
// extern UNK_TYPE D_0042E730;
// extern UNK_TYPE D_0042E734;
// extern UNK_TYPE D_0042E738;
// extern UNK_TYPE D_0042E748;

#endif
